import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import http from 'node:http';import path from 'node:path';import {chromium} from 'playwright';
test('real Matrix app boots a full canonical dataset, virtualizes, filters without read calls and patches only one SKU',async()=>{
 const root=path.resolve('mockups/operations-hub');const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404).end();return;}const type=path.extname(file);res.setHeader('Content-Type',type==='.js'?'text/javascript':type==='.css'?'text/css':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});
 try{const page=await browser.newPage({viewport:{width:1600,height:1000}});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',route=>route.fulfill({contentType:'text/javascript',body:'window.supabase={createClient:()=>({rpc:async()=>({data:{}})})};'}));
 await page.addInitScript(()=>{const rows=Array.from({length:23775},(_,i)=>({sellpia_sku_code:i<4?'5566-'+(i+1):'90000-'+i,sellpia_product_name:'상품'+i,sellpia_option_name:'옵션'+i,system_stock:i%13,system_base_price:5000,sellpia_source_purchase_price:2000,sellpia_source_stock:3,sellpia_source_sale_price:4000,smartstore_product_code:i%2?'S'+i:null,smartstore_match_tier:i%2?'EXACT':null,__profile:{sku_tags:i%3?[{tag_id:'T',tag_name:'14K'}]:[]},__hubShadowCompact:i===0,__hubActivePriceRules:{smartstore:false,makeshop:false,ably:false}}));window.fixture=rows;window.readCounts={full:0,patch:0,history:0};const expiresAt=new Date(Date.now()+3600000).toISOString();sessionStorage.setItem('system-v3-operations-session-v1',JSON.stringify({token:'a'.repeat(64),expiresAt}));const data={mode:'live',pageSize:200,setOperationsHubSessionToken:()=>{},checkOperationsHubSession:async()=>({authenticated:true,expiresAt}),loginOperationsHub:async()=>({authenticated:true,expiresAt}),logoutOperationsHub:async()=>{},loadFullMatrixDataset:async()=>{readCounts.full++;return {rows,count:rows.length,elapsed:1,metrics:{requests:1,bytes:1}};},loadProductsBySkus:async skus=>{const history=document.getElementById("product-drawer")?.classList.contains("open");readCounts[history?"history":"patch"]++;return rows.filter(r=>skus.includes(r.sellpia_sku_code)).map(r=>({...r,system_stock:777,...(history?{__hubInternalPrices:{actual_inbound_cost:{value:500,generationId:42}}}:{})}));},loadMappingSyncStatus:async()=>({}),loadSourceStatus:async()=>({events:[],latest:{}}),loadDashboardMetrics:async()=>({total_sku:rows.length}),loadTagCatalog:async()=>({rows:[]}),loadSellerInventoryPolicies:async()=>[],loadPresets:async()=>[]};const api=new Proxy(data,{get:(t,k)=>k in t?t[k]:async()=>({rows:[],count:0})});Object.defineProperty(window,'SystemV3Data',{configurable:true,get:()=>api,set:()=>{}});});
 await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');await page.locator('[data-page="matching"]').first().click();await page.waitForFunction(()=>window.HubMatrixClient?.dataset?.rows.length===23775);await page.waitForFunction(()=>document.querySelectorAll('#matrix-body tr[data-sku]').length>0);assert.equal(await page.evaluate(()=>HubMatrixClient.dataset.bySku.size),23775);assert.ok(await page.locator('#matrix-body tr[data-sku]').count()<60);
 await page.locator('#matrix-body tr[data-sku="5566-1"] .sellpia-option-name-col').click();assert.equal(await page.locator('#selected-count').innerText(),'1');
 await page.locator('.matrix-shell').evaluate(el=>{el.scrollTop=99999999;});await page.waitForFunction(()=>[...document.querySelectorAll('#matrix-body tr[data-sku]')].some(r=>r.dataset.sku==='90000-23774'));assert.equal(await page.locator('#selected-count').innerText(),'1','virtual scroll retains selected SKU');
 await page.locator('.matrix-shell').evaluate(el=>{el.scrollTop=0;});await page.waitForFunction(()=>document.querySelector('#matrix-body tr[data-sku="5566-1"] .sellpia-option-name-col')?.classList.contains('matrix-cell-selected'));assert.equal(await page.evaluate(()=>readCounts.full),1);
 await page.locator('.matrix-shell').evaluate(el=>{el.scrollTop=99999999;});await page.waitForFunction(()=>[...document.querySelectorAll('#matrix-body tr[data-sku]')].some(r=>r.dataset.sku==='90000-23774'));assert.ok(await page.locator('#matrix-body tr[data-sku]').count()<60);await page.locator('#matrix-search-type').selectOption('sku');await page.locator('#matrix-search').fill('5566');await page.waitForFunction(()=>document.getElementById('matrix-total-count').textContent==='4');assert.equal(await page.locator('#matrix-body tr[data-sku]').count(),4);await page.locator('#matrix-body tr[data-sku="5566-1"] .sellpia-name-col').dblclick();await page.waitForFunction(()=>document.getElementById('product-drawer').classList.contains('open'));assert.equal(await page.locator('#drawer-sku').innerText(),'5566-1');await page.waitForFunction(()=>document.querySelector('#product-drawer .shadow-lineage')?.textContent.includes('generation 42'));assert.equal(await page.evaluate(()=>readCounts.history),1);assert.equal(await page.evaluate(()=>HubMatrixClient.dataset.bySku.get('5566-1').system_stock),0,'history hydration must not patch current values');await page.keyboard.press('Escape');await page.locator('#matrix-search').fill('');await page.waitForFunction(()=>document.getElementById('matrix-total-count').textContent.includes('23,775'));assert.equal(await page.evaluate(()=>readCounts.full),1);
 await page.locator('#matrix-client-tag').selectOption('T');await page.waitForFunction(()=>!document.getElementById('matrix-total-count').textContent.includes('23,775'));await page.locator('#matrix-client-tag').selectOption('');await page.locator('#matrix-client-seller').selectOption('smartstore');await page.locator('#matrix-client-seller').selectOption('');assert.equal(await page.evaluate(()=>readCounts.full),1);assert.equal(await page.evaluate(()=>readCounts.patch),0);
 const untouched=await page.evaluate(()=>{window.untouched=HubMatrixClient.dataset.bySku.get('90000-7');window.dispatchEvent(new CustomEvent('hub-matrix-affected',{detail:{skus:['5566-1']}}));window.dispatchEvent(new CustomEvent('hub-rules-changed',{detail:{affectedSkus:['5566-1']}}));return true;});assert.equal(untouched,true);await page.waitForFunction(()=>HubMatrixClient.dataset.bySku.get('5566-1').system_stock===777);assert.equal(await page.evaluate(()=>HubMatrixClient.dataset.bySku.get('90000-7')===untouched),true);assert.equal(await page.evaluate(()=>readCounts.patch),1);assert.equal(await page.evaluate(()=>readCounts.full),1);assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
