import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {fileURLToPath} from 'node:url';
const root=new URL('../mockups/operations-hub/',import.meta.url),browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.route('**/*',r=>r.abort());await page.setContent('<main id="price-rules"></main>');
 await page.addStyleTag({path:fileURLToPath(new URL('rule-workspace.css',root))});
 await page.evaluate(()=>{
  window.qa={writes:[],loads:[],rule:{id:'tag-rule',tag_id:'tag-14k',name:'14k일괄2배테스트',target_field:'calculated_base_price',input_origin:'self',source_field:'purchase_price',source_scope:'',scope:'',version:3,is_active:true,config:{steps:[{op:'divide',value:2}]}},preset:{id:'preset-rule',tag_id:'tag-source-2000',name:'소스_2000',target_field:'platform_registration_price',input_origin:'self',source_field:'calculated_base_price',source_scope:'',scope:'smartstore',version:1,is_active:true,config:{steps:[{op:'add',value:2000}]}}};
  window.SystemV3Data={ruleRegistry:async()=>({rules:[structuredClone(qa.rule),structuredClone(qa.preset)],assignments:Array.from({length:2916},(_,i)=>({sku:'sku-'+i,rule_id:'tag-rule',target_field:qa.rule.target_field,scope:qa.rule.scope})),dependencies:[]}),saveTagRule:async({tag,rule})=>{const tagId=tag.id||'new-tag';qa.writes.push(structuredClone(rule));qa.rule={...structuredClone(rule),id:rule.id||'new-rule',tag_id:tagId,version:qa.rule.version+1};return {tag:{tag_id:tagId,tag_name:tag.name,tag_color:tag.color,tag_group:tag.group},rules:[structuredClone(qa.rule)]};},loadTags:async()=>[{tag_id:'tag-14k',tag_name:'14k일괄2배테스트',tag_color:'#dbeafe',tag_group:'가격 수식'},{tag_id:'tag-source-2000',tag_name:'소스_2000',tag_color:'#dbeafe',tag_group:'가격 수식'}],loadFormulaProducts:async skus=>{qa.loads.push(skus.length);return skus.map(sku=>({sellpia_sku_code:sku,display_name:'14k 상품',sellpia_source_purchase_price:14000}));}};
 });
 for(const file of ['rule-registry.js','rule-workspace.js'])await page.addScriptTag({path:fileURLToPath(new URL(file,root))});
 await page.evaluate(()=>{HubPriceWorkspace.state.selected='tag-rule';return HubPriceWorkspace.refresh();});
 assert.equal(await page.locator('#rw-legacy-rules').inputValue(),'shared:tag-rule','linked formula tag is immediately available inside the formula builder');assert.match(await page.locator('#rw-bulk').innerText(),/이 수식 태그를 SKU에 적용/);
 assert.equal(await page.locator('#rw-target').inputValue(),'calculated_base_price');
 assert.equal(await page.locator('#rw-target').isEnabled(),true,'an assigned shared rule destination remains editable');assert.equal(await page.locator('#rw-origin').isDisabled(),true,'self to parent still requires explicit dependency data');assert.equal(await page.locator('#rw-scope').isDisabled(),true,'internal destination has no platform scope');
 assert.equal(await page.locator('#rw-source-field').isEnabled(),true);assert.equal(await page.locator('.rw-op input').isEnabled(),true);
 assert.match(await page.locator('#rw-stage-note').innerText(),/2,916개 SKU에 적용/);assert.match(await page.locator('#rw-stage-note').innerText(),/연결 정보도 새 위치로 함께 이동/);assert.match(await page.locator('#rw-stage-note').innerText(),/전체 저장을 취소/);
 assert.match(await page.locator('#rw-target option:checked').innerText(),/시스템 기준가격 · 매트릭스/);assert.equal(await page.locator('#rw-target option[value="basis_sku_price"]').count(),0,'advanced intermediate target stays hidden until multistep is enabled');assert.match(await page.locator('#rw-list').innerText(),/태그 · 14k일괄2배테스트/);assert.match(await page.locator('#rw-list').innerText(),/셀피아 매입가 → ÷ 2/);assert.match(await page.locator('#rw-list').innerText(),/시스템 기준가격/);assert.match(await page.locator('#rw-list').innerText(),/적용 2,916 SKU/);assert.match(await page.locator('.rw-rule-link').innerText(),/연결 상품 태그\s*14k일괄2배테스트/);
 assert.match(await page.locator('#rw-flow-summary').innerText(),/셀피아 매입가 → ÷ 2/);assert.match(await page.locator('#rw-flow-summary').innerText(),/시스템 기준가격/);assert.match(await page.locator('#rw-flow-effect').innerText(),/이후 판매처 가격/);
 assert.match(await page.locator('#rw-preview-state').innerText(),/저장된 수식 v3/);assert.match(await page.locator('#rw-preview tr').first().innerText(),/7,000/);assert.deepEqual(await page.evaluate(()=>qa.loads),[200]);assert.deepEqual(await page.evaluate(()=>qa.writes),[]);
 await page.locator('.rw-op input').fill('4');assert.match(await page.locator('#rw-flow-summary').innerText(),/÷ 4/);assert.match(await page.locator('#rw-preview-state').innerText(),/저장 전이며, 아래 표에 반영되지 않았습니다/);assert.match(await page.locator('#rw-preview tr').first().innerText(),/7,000/);assert.deepEqual(await page.evaluate(()=>qa.loads),[200],'draft edit does not fetch unbounded evaluations');
 await page.locator('.rw-op input').fill('2');await page.locator('#rw-name').fill('14k일괄2배테스트 이름 유지');await page.locator('#rw-save').click();await page.waitForFunction(()=>!HubPriceWorkspace.state.busy);
 const saved=await page.evaluate(()=>qa.writes[0]);assert.equal(saved.target_field,'calculated_base_price');assert.equal(saved.input_origin,'self');assert.equal(saved.tag_id,'tag-14k');assert.deepEqual(saved.config.steps,[{op:'divide',value:2}],'tag name never changes mathematical meaning');assert.equal(saved.source_field,'purchase_price');assert.equal(await page.locator('#rw-target').isEnabled(),true);assert.match(await page.locator('#rw-preview-state').innerText(),/저장된 수식 v4/);assert.doesNotMatch(await page.locator('#rw-save-status').innerText(),/assigned|target_field|오류/);
 await page.locator('#rw-new').click();assert.equal(await page.locator('#rw-target').isEnabled(),true);assert.equal(await page.locator('#rw-origin').isEnabled(),true);assert.equal(await page.locator('#rw-stage-note').isVisible(),false);assert.equal(await page.locator('#rw-tag-name').inputValue(),'');const writesBeforeImport=await page.evaluate(()=>qa.writes.length);const sourceBefore=await page.locator('#rw-source-field').inputValue(),targetBefore=await page.locator('#rw-target').inputValue();await page.locator('#rw-legacy-rules').selectOption('shared:preset-rule');assert.deepEqual(await page.locator('.rw-op input').evaluateAll(nodes=>nodes.map(node=>node.value)),['2000']);assert.equal(await page.locator('#rw-source-field').inputValue(),sourceBefore);assert.equal(await page.locator('#rw-target').inputValue(),targetBefore);assert.equal(await page.evaluate(()=>HubPriceWorkspace.state.selected),null);assert.equal(await page.evaluate(()=>qa.writes.length),writesBeforeImport,'formula step import is read-only');assert.match(await page.locator('#rw-status').innerText(),/계산 단계 1개를 가져왔습니다/);await page.locator('#rw-multistep').check();await page.locator('#rw-target').selectOption('basis_sku_price');assert.match(await page.locator('#rw-flow-summary').innerText(),/이전 계산 결과/);assert.match(await page.locator('#rw-preview-state').innerText(),/아직 저장하지 않은 수식/);
 await page.locator('#rw-multistep').uncheck();await page.locator('#rw-tag-name').fill('메이크샵 M15');await page.locator('#rw-name').fill('메이크샵 M15 할인');await page.locator('#rw-target').selectOption('platform_discount_price');assert.equal(await page.locator('#rw-scope option').filter({hasText:'전체 판매처'}).count(),0);await page.locator('#rw-scope').selectOption('makeshop');assert.equal(await page.locator('#rw-source-field').inputValue(),'platform_registration_price');assert.equal(await page.locator('#rw-source-field').isDisabled(),true);assert.equal(await page.locator('#rw-makeshop-discount').isVisible(),true);assert.equal(await page.locator('#rw-ops').isVisible(),false);await page.locator('#rw-makeshop-discount-code').selectOption('M15');assert.match(await page.locator('#rw-flow-summary').innerText(),/메이크샵 M15/);await page.locator('#rw-save').click();await page.waitForFunction(()=>!HubPriceWorkspace.state.busy);const makeshop=await page.evaluate(()=>qa.writes.at(-1));assert.equal(makeshop.scope,'makeshop');assert.equal(makeshop.source_field,'platform_registration_price');assert.equal(makeshop.config.discount_rule_code,'M15');assert.deepEqual(makeshop.config.steps,[{op:'multiply',value:.85},{op:'round',unit:10,rounding:'down'}]);
 console.log('PASS linked formula tag edit uses atomic tag save; new action starts formula tag; saved formula selection copies steps only; discount is seller-scoped; Makeshop uses a code-only editor.');
}finally{await browser.close();}
