import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(process.env.CODEX_NODE_MODULES?`${process.env.CODEX_NODE_MODULES}/ui-test.cjs`:import.meta.url);
const {chromium}=require('playwright');
const xlsxScript=process.env.XLSX_BROWSER_SCRIPT||new URL('../../xlsx.full.min.js',import.meta.url);
const scripts=new URL('../mockups/operations-hub/',import.meta.url);
const html=fs.readFileSync(new URL('index.html',scripts),'utf8');
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage();
 await page.route('**/*',route=>route.abort());
 await page.setContent(html.slice(html.indexOf('<div id="ably-combinations"'),html.indexOf('<div id="attributes"')));
 const xlsxContent=fs.existsSync(xlsxScript)?fs.readFileSync(xlsxScript,'utf8'):await (await fetch('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js')).text();
 await page.addScriptTag({content:xlsxContent});
 await page.addScriptTag({content:fs.readFileSync(require.resolve('jszip/dist/jszip.min.js'),'utf8')});
 await page.evaluate(()=>{
  window.calls=[];window.docs={};window.downloads=[];window.failGet=false;window.failList=false;
  window.componentProducts=Array.from({length:9},(_,i)=>({sellpia_sku_code:`1000-${i+1}`,sellpia_option_name:`옵션${i+1}`,system_stock:i===0?0:20-i,system_base_price:1000+i}));
  window.SystemV3Data={
   async loadAblyComponentStocks(skus){return componentProducts.filter(p=>skus.includes(p.sellpia_sku_code));},
   async workDocument(action,kind,data){calls.push(action);if(action==='save'){const id=data.id||'doc-'+(Object.keys(docs).length+1);docs[id]=structuredClone({...data,id,row_count:data.body.rows.length,updated_at:new Date().toISOString()});return structuredClone(docs[id]);}if(action==='get'){if(failGet){failGet=false;throw Error('QA get failure');}return structuredClone(docs[data.id]);}if(failList){failList=false;throw Error('QA list failure');}return Object.values(docs).map(({body,...d})=>d);}
  };
  window.SystemV3SellerExport={downloadBlob(blob,name){downloads.push({blob,name});}};
  window.confirm=()=>true;
 });
 for(const name of ['ably-stock-export.js','ably-combinations.js','ably-combination-lab.js','ably-pair-generator.js','ably-workspace.js'])await page.addScriptTag({content:fs.readFileSync(new URL(name,scripts),'utf8')});
 await page.evaluate(async()=>{
  const make=(c,e,q,w)=>{const r=Array(35).fill('');r[0]='에이블리';r[1]='original-account';r[2]=c;r[3]='원본 상품';r[4]=e;r[5]=1234;r[9]='조합형';r[10]='원본 명칭';r[11]='첫 값';r[12]='둘째';r[13]='두 값';r[16]=q;r[17]='11502-1+2';r[23]=w;return r;};
  const data=[AblyStockExport.headers,make('sellpia_8149','PRODUCT-1','',77),make('manual-row-2','PRODUCT-1','[broken',88),make('other','PRODUCT-2','[1000-2]',99)];
  data[2][10]='다른 원본 명칭';
  const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(data),'옵션기본');
  const zip=await JSZip.loadAsync(XLSX.write(book,{bookType:'xlsx',type:'array'}));
  const xml=await zip.file('xl/worksheets/sheet1.xml').async('string');
  zip.file('xl/worksheets/sheet1.xml',xml.replace('<row r="2">','<row r="2" ht="31" customHeight="1">').replace('<row r="3">','<row r="3" ht="43" customHeight="1">'));
  window.originalBytes=await zip.generateAsync({type:'uint8array'});window.originalXml=await zip.file('xl/worksheets/sheet1.xml').async('string');
  const transfer=new DataTransfer();transfer.items.add(new File([originalBytes],'original.xlsx'));document.getElementById('ably-combination-file').files=transfer.files;document.getElementById('ably-combination-file').dispatchEvent(new Event('change'));
 });
 await page.waitForFunction(()=>document.querySelectorAll('[data-ably-product]').length===2);
 await page.locator('[data-ably-product="0"]').click();
 await page.waitForSelector('#aw-save');
 assert.equal(await page.locator('#aw-rows input[data-column="2"]').first().getAttribute('readonly'),null);
 await page.locator('#aw-rows input[data-row="0"][data-column="2"]').fill('MANUAL-C');
 await page.locator('#aw-save').click();
 await page.waitForFunction(()=>document.getElementById('ably-saved-status').textContent.includes('재조회 확인 완료'));
 assert.deepEqual(await page.evaluate(()=>calls.slice(-3)),['save','get','list']);
 assert.deepEqual(await page.evaluate(()=>docs['doc-1'].body.rows.map(r=>[r[2],r[16],r[23],r[10]])),[['MANUAL-C','',77,'원본 명칭'],['manual-row-2','[broken',88,'다른 원본 명칭']]);
 await page.locator('[data-saved="doc-1"]').click();
 await page.locator('#aw-download').click();
 await page.waitForFunction(()=>document.getElementById('aw-status').textContent.includes('Q열 연결 SKU 형식'));
 assert.equal(await page.evaluate(()=>downloads.length),0);
 await page.locator('#aw-rows input[data-row="0"][data-column="16"]').fill('[1000-2],[1000-3]');
 await page.locator('#aw-rows input[data-row="1"][data-column="16"]').fill('[1000-1],[1000-1]');
 await page.locator('#aw-stock').click();
 await page.waitForFunction(()=>document.getElementById('aw-status').textContent.includes('현재재고 갱신'));
 await page.locator('#aw-save').click();
 await page.waitForFunction(()=>document.getElementById('ably-saved-status').textContent.includes('재조회 확인 완료')&&document.querySelector('.ably-workspace').hidden);
 assert.equal(await page.evaluate(()=>Object.keys(docs).length),1);
 assert.deepEqual(await page.evaluate(()=>docs['doc-1'].body.rows.map(r=>[r[2],r[16],r[23]])),[['MANUAL-C','[1000-2],[1000-3]',18],['manual-row-2','[1000-1],[1000-1]',0]]);
 await page.locator('[data-saved="doc-1"]').click();
 await page.locator('#aw-download').click();
 await page.waitForFunction(()=>downloads.length===1);
 const preservation=await page.evaluate(async()=>{
  const bytes=await downloads[0].blob.arrayBuffer(),book=XLSX.read(bytes),sheet=book.Sheets['옵션기본'],zip=await JSZip.loadAsync(bytes),xml=await zip.file('xl/worksheets/sheet1.xml').async('string');
  const orig=await JSZip.loadAsync(originalBytes),other=Object.keys(orig.files).filter(n=>!orig.files[n].dir&&n!=='xl/worksheets/sheet1.xml');
  return {values:['C2','Q2','X2','C3','X3','R2','K3','X4'].map(c=>sheet[c]?.v??''),rows:[xml.includes('r="2" ht="31"'),xml.includes('r="3" ht="43"')],untouchedRow:xml.match(/<row r="4"[^]*?<\/row>/)[0]===originalXml.match(/<row r="4"[^]*?<\/row>/)[0],otherParts:(await Promise.all(other.map(async n=>(await zip.file(n).async('base64'))===(await orig.file(n).async('base64'))))).every(Boolean)};
 });
 assert.deepEqual(preservation.values,['MANUAL-C','[1000-2],[1000-3]',18,'manual-row-2',0,'11502-1+2','다른 원본 명칭',99]);
 assert.ok(preservation.rows.every(Boolean)&&preservation.untouchedRow&&preservation.otherParts);
 assert.deepEqual(await page.evaluate(()=>AblyImportedWorkspace.snapshot().groups[0].items.map(i=>[i.row[2],i.memoText])),[['MANUAL-C','[1000-2],[1000-3]'],['manual-row-2','[1000-1],[1000-1]']]);
 await page.locator('#aw-rows input[data-row="0"][data-column="16"]').fill('[unavailable-sku]');
 await page.locator('#aw-download').click();await page.waitForFunction(()=>document.getElementById('aw-status').textContent.includes('현재재고를 확인할 수 없는'));
 assert.equal(await page.evaluate(()=>downloads.length),1);
 console.log('PASS imported card unified editor, varying row C stays in one product, incomplete Q save, C/Q/min-stock re-save/reopen/export, source rows/styles/package preservation');
 await page.locator('#aw-back').click();
 await page.locator('#ably-all-stock-download').click();await page.waitForFunction(()=>downloads.length===2);
 assert.deepEqual(await page.evaluate(async()=>{const sheet=XLSX.read(await downloads[1].blob.arrayBuffer()).Sheets['옵션기본'];return ['C2','Q2','X2','C3','X3'].map(c=>sheet[c]?.v);}),['MANUAL-C','[1000-2],[1000-3]',18,'manual-row-2',0]);
 await page.locator('#ably-virtual-product-open').click();
 await page.locator('#aw-title').fill('81 combinations');await page.locator('#aw-codes').fill(Array.from({length:9},(_,i)=>`1000-${i+1}`).join('\n'));await page.locator('#aw-load').click();
 await page.waitForFunction(()=>document.querySelectorAll('#aw-products input').length===9);
 await page.locator('#aw-generate').click();await page.waitForFunction(()=>document.getElementById('aw-status').textContent.includes('81개 조합 생성'));
 await page.locator('#aw-rows input[data-row="0"][data-column="2"]').fill('manual-generated');
 await page.evaluate(()=>{failGet=true;});await page.locator('#aw-save').click();
 await page.waitForFunction(()=>document.getElementById('aw-status').textContent.includes('재조회 실패'));
 assert.equal(await page.locator('.ably-workspace').evaluate(e=>e.hidden),false);
 await page.locator('#aw-save').click();await page.waitForFunction(()=>document.querySelector('.ably-workspace').hidden);
 assert.equal(await page.evaluate(()=>Object.keys(docs).length),2);
 assert.equal(await page.evaluate(()=>docs['doc-2'].body.rows.length),81);
 assert.equal(await page.evaluate(()=>docs['doc-2'].body.rows[0][2]),'manual-generated');
 await page.locator('[data-saved="doc-2"]').click();
 await page.locator('#aw-size').selectOption('3');await page.locator('#aw-generate').click();await page.waitForFunction(()=>document.getElementById('aw-status').textContent.includes('729개 조합 생성'));
 await page.evaluate(()=>{failList=true;});await page.locator('#aw-save').click();await page.waitForFunction(()=>document.getElementById('aw-status').textContent.includes('QA list failure'));
 assert.equal(await page.locator('.ably-workspace').evaluate(e=>e.hidden),false);
 assert.equal(await page.evaluate(()=>docs['doc-2'].body.rows.length),729);
 await page.locator('#aw-save').click();await page.waitForFunction(()=>document.querySelector('.ably-workspace').hidden);
 assert.equal(await page.evaluate(()=>Object.keys(docs).length),2);
 assert.ok(await page.evaluate(()=>docs['doc-2'].body.rows.every(r=>r[2]==='sellpia_1000'&&r[23]===Math.min(...AblyCombinationModel.parseSkuMemo(r[16]).skus.map(s=>componentProducts.find(p=>p.sellpia_sku_code===s).system_stock)))));
 await page.locator('[data-saved="doc-2"]').click();
 await page.evaluate(()=>{window.fetch=async()=>new Response(originalBytes,{status:200});});
 await page.locator('#aw-download').click();await page.waitForFunction(()=>downloads.length===3);
 assert.deepEqual(await page.evaluate(async()=>{const sheet=XLSX.read(await downloads[2].blob.arrayBuffer()).Sheets['옵션기본'];return [sheet['!ref'],sheet.C730.v,sheet.Q730.v,sheet.X730.v];}),['A1:AI730','sellpia_1000','[1000-9],[1000-9],[1000-9]',12]);
 console.log('PASS generated 9 SKU 81/729 flow, manual row C, minimum stock, failed get/list keeps same document for retry');
}finally{await browser.close();}
