import assert from "node:assert/strict";
import fs from "node:fs";

const migration = fs.readFileSync(new URL("../supabase/migrations/20260827130000_operations_hub_relation_organization.sql", import.meta.url), "utf8");
const optimization = fs.readFileSync(new URL("../supabase/migrations/20260827131500_optimize_relation_matrix_filter.sql", import.meta.url), "utf8");
const integrity = fs.readFileSync(new URL("../supabase/migrations/20260827132000_enforce_relation_parent_integrity.sql", import.meta.url), "utf8");
const graph = fs.readFileSync(new URL("../supabase/migrations/20260827080008_generalize_relation_node_graph.sql", import.meta.url), "utf8");
const dragBoard = fs.readFileSync(new URL("../supabase/migrations/20260827085604_operations_hub_relation_drag_board.sql", import.meta.url), "utf8");
const pageFirstMigration = fs.readFileSync(new URL("../supabase/migrations/20260831151000_operations_hub_matrix_page_v3.sql", import.meta.url), "utf8");
const html = fs.readFileSync(new URL("../mockups/operations-hub/index.html", import.meta.url), "utf8");
const app = fs.readFileSync(new URL("../mockups/operations-hub/app.js", import.meta.url), "utf8");
const data = fs.readFileSync(new URL("../mockups/operations-hub/data-service.js", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("../mockups/operations-hub/style.css", import.meta.url), "utf8");

assert.match(migration, /operations_hub_relation_folders[\s\S]*folder_kind in \('collection', 'one_plus_one', 'set', 'custom'\)/, "relation folders must use a bounded kind vocabulary");
assert.match(migration, /parent_component_id[\s\S]*foreign key \(parent_component_id\)[\s\S]*on delete set null/, "component dependencies must be durable and recoverable");
assert.match(migration, /save_operations_hub_listing_component_parent[\s\S]*same[\s\S]*순환 종속관계는 만들 수 없습니다|save_operations_hub_listing_component_parent[\s\S]*같은 조합[\s\S]*순환 종속관계는 만들 수 없습니다/, "dependency writes must stay inside one listing and reject cycles");
assert.doesNotMatch(migration.slice(migration.indexOf("save_operations_hub_listing_component_parent"), migration.indexOf("list_operations_hub_listing_graph_v2")), /component_qty\s*=|component_role\s*=/, "dependency metadata must not alter stock calculation inputs");
assert.match(migration, /operations_hub_matrix_managed_live[\s\S]*is_dependent_combination_sku[\s\S]*sellpia_sku_prefix_number[\s\S]*sellpia_sku_suffix_number/, "the matrix wrapper must expose explicit dependency filtering and numeric sort keys");
assert.match(migration, /p_exclude_dependent[\s\S]*not matrix\.is_dependent_combination_sku/, "server paging must exclude only explicitly dependent SKUs");
assert.match(migration, /sellpia_sku_prefix_number asc nulls last[\s\S]*sellpia_sku_has_numeric_suffix asc[\s\S]*sellpia_sku_suffix_number asc nulls first/, "SKU ordering must compare numeric prefix and option suffix");
assert.match(migration, /security invoker[\s\S]*revoke all[\s\S]*grant execute/i, "new relationship reads and writes must keep invoker permissions");
assert.match(optimization, /operations_hub_matrix_live matrix[\s\S]*operations_hub_listing_components component[\s\S]*parent_component_id is not null/, "advanced filtering must reuse the established fast matrix and only probe indexed dependency rows");
assert.doesNotMatch(optimization, /operations_hub_matrix_managed_live matrix/, "advanced filtering must not rescan the system overlay across the full catalog");
assert.match(integrity, /validate_operations_hub_component_parent[\s\S]*같은 조합[\s\S]*순환 종속관계[\s\S]*operations_hub_component_parent_guard/, "database triggers must reject cross-listing and cyclic parent writes");
assert.match(integrity, /clear_operations_hub_component_children[\s\S]*parent_component_id = null[\s\S]*operations_hub_component_children_cleanup/, "disconnecting a parent must promote surviving children back to roots");
assert.match(graph, /operations_hub_relation_nodes[\s\S]*node_type in \('sellpia_product', 'seller_listing', 'custom'\)[\s\S]*operations_hub_relation_edges/, "the management model must represent both product and seller nodes with directed edges");
assert.match(graph, /parent_node_id <> child_node_id[\s\S]*with recursive descendants[\s\S]*순환 종속관계는 만들 수 없습니다/, "arbitrary-depth relations must reject self-links and cycles");
assert.match(graph, /ensure_operations_hub_sellpia_relation_node[\s\S]*sellpia_stock_latest[\s\S]*display_name[\s\S]*ensure_operations_hub_seller_relation_node/, "Sellpia product names and seller listings must create reusable relation nodes");
assert.doesNotMatch(graph, /component_qty\s*=|component_role\s*=|sellpia_current_stock\s*=|system_base_price\s*=/, "management-only graph writes must not change calculation inputs");
assert.match(dragBoard, /node_type in \('sellpia_product', 'sellpia_sku', 'seller_listing', 'custom'\)[\s\S]*operations_hub_relation_nodes_sellpia_sku_active_idx/, "Sellpia options must be reusable SKU-level relationship nodes without replacing legacy product nodes");
assert.match(dragBoard, /ensure_operations_hub_sellpia_sku_relation_node[\s\S]*sellpia_stock_latest[\s\S]*apply_operations_hub_relation_board/, "the board must resolve exact Sellpia options and persist one atomic relationship batch");
assert.match(dragBoard, /jsonb_array_length[\s\S]*최대 500개[\s\S]*remove_operations_hub_relation_edge[\s\S]*save_operations_hub_relation_edge/, "relationship board batches must be bounded and reuse cycle-safe edge writers");
assert.doesNotMatch(dragBoard, /component_qty\s*=|component_role\s*=|sellpia_current_stock\s*=|system_base_price\s*=/, "drag-board writes must not alter inventory or price calculation fields");

assert.match(html, /id="relation-folder-list"[\s\S]*class="relation-workspace"[\s\S]*id="relation-edge-list"[\s\S]*id="relation-graph-board"[\s\S]*id="multi-link-organization-form"/, "the default workspace must show scoped one-edge rows before the optional graph and relationship composer");
assert.match(html, /id="relation-workspace-search"[\s\S]*id="relation-view-list"[\s\S]*id="relation-view-graph"/, "search and an explicit view switch must control when the full relationship explorer appears");
assert.match(html, /id="relation-product-loader"[\s\S]*id="relation-board-source"[\s\S]*id="relation-board-product-code"[\s\S]*id="relation-drag-board"[\s\S]*id="relation-board-save"/, "operators must load every option by one exact product code and arrange them on a dedicated board");
assert.match(html, /id="relation-image-modal"[\s\S]*id="relation-image-preview"[\s\S]*id="relation-image-product-name"[\s\S]*id="relation-image-option-name"/, "relationship cards must open a dedicated product image preview");
assert.match(html, /id="relation-sellpia-search"[\s\S]*id="relation-parent-node"[\s\S]*id="relation-child-node"/, "operators must still prepare nodes and choose upper and lower products directly");
assert.match(html, /id="multi-link-workspace-tabs"[\s\S]*class="multi-link-all-workspace"[\s\S]*id="multi-link-body"/, "listing rows must live in the all-connections matrix");
assert.match(html, /id="multi-link-components"[\s\S]*id="multi-link-sku-action-modal"/, "SKU quantity and inventory tools must be hosted by a row-level modal rather than a persistent workspace panel");
assert.match(html, /id="preset-exclude-combination-skus"[^>]*type="checkbox"/, "view settings must expose dependent combination SKU exclusion");
assert.match(html, /999 → 1000 → 10000/, "view settings must explain numeric SKU ordering");
assert.match(app, /excludeCombinationSkus:false[\s\S]*matrixState\.excludeCombinationSkus = Boolean[\s\S]*excludeCombinationSkus:matrixState\.excludeCombinationSkus/, "the exclusion preference must persist into matrix requests");
assert.match(app, /matrixState\.excludeCombinationSkus && !matrixState\.codeListRows\.length[\s\S]*조합 SKU 제외는 현재 매트릭스 보기 전용/, "CSV export must fail closed instead of silently reintroducing hidden dependent SKUs");
assert.match(app, /renderRelationFolders[\s\S]*loadRelationFolders/, "the UI must load and render relation folders");
assert.match(app, /renderRelationEdgeList[\s\S]*renderRelationTree[\s\S]*setRelationViewMode/, "the UI must default to concise edge rows and reveal the column graph only on demand");
assert.match(app, /loadRelationBoardProduct[\s\S]*sellpia-sku\|[\s\S]*loadSellerProductOptions[\s\S]*renderRelationBoard/, "product loading must expand both seller and Sellpia products into option-level staged nodes");
assert.match(app, /normalizeRelationBoardBranch[\s\S]*moveRelationBoardNode[\s\S]*data-board-drop-level[\s\S]*pointerdown[\s\S]*pointermove[\s\S]*pointerup/, "horizontal pointer drag must move the selected node with its descendant branch across browsers");
assert.match(app, /data-board-link-in[\s\S]*data-board-link-out/, "each relationship card must expose an input and output connector port");
assert.match(app, /relationBoardPathData[\s\S]*relation-board-link preview[\s\S]*connectRelationBoardNodes/, "parents and children must be connected with visible staged connector lines instead of repeated parent text lanes");
assert.match(app, /createRelationBoardDragGhost[\s\S]*relation-board-drag-ghost[\s\S]*positionRelationBoardDragGhost/, "card movement must show a cursor-following drag ghost");
assert.match(app, /relationBoardCardLabels[\s\S]*productName[\s\S]*optionName[\s\S]*relation-board-node-copy/, "relationship cards must keep product and option names on separate visible lines");
assert.match(app, /relationBoardCardImage[\s\S]*data-relation-image[\s\S]*openRelationImageModal[\s\S]*closeRelationImageModal/, "relationship thumbnails must open and close an enlarged preview without changing relation data");
assert.doesNotMatch(app, /<span>\$\{escapeHtml\(parent\.displayName\)\}<\/span><b>의 자식<\/b>/, "the board must not repeat the full parent product name above every child list");
assert.doesNotMatch(app, /relation-board-node[^`]*draggable="true"/, "the relationship board must not depend on browser-native HTML5 drag behavior");
assert.match(app, /relationBoardChanges[\s\S]*applyRelationBoard[\s\S]*removeEdgeIds/, "the board must review additions and removals before one atomic save");
assert.match(app, /data-explore-relation-node[\s\S]*relationGraphState\.focusNodeId[\s\S]*setRelationViewMode\('graph'\)/, "a multi-membership badge must open the focused node's full relationship component");
assert.match(app, /const includeLegacy[\s\S]*if \(!includeLegacy\)[\s\S]*loadRelationGraph[\s\S]*loadListingGraph/, "the default relation page must not run the heavy legacy listing query before its details workspace opens");
assert.match(app, /setMultiLinkWorkspaceTab[\s\S]*next === 'all'[\s\S]*loadManagedConnections\(\)[\s\S]*function loadManagedConnections[\s\S]*loadRelationGraph\(\)[\s\S]*loadBundleGraph/, "the all-connections tab must load only managed relationships and bundle composition");
assert.match(app, /ensureSellpiaRelationNode[\s\S]*ensureSellerRelationNode[\s\S]*saveRelationEdge/, "the UI must create either node type and save a user-selected direction");
assert.match(app, /data-remove-relation-edge[\s\S]*removeRelationEdge/, "operators must be able to remove only the selected relation edge");
assert.match(app, /saveListingComponentParent/, "the UI must save component dependencies");
assert.match(data, /list_operations_hub_relation_folders[\s\S]*search_operations_hub_sellpia_product_groups[\s\S]*ensure_operations_hub_sellpia_relation_node[\s\S]*ensure_operations_hub_seller_relation_node[\s\S]*save_operations_hub_relation_edge/, "the data adapter must expose bounded relation-node and edge RPCs");
assert.match(data, /ensure_operations_hub_sellpia_sku_relation_node[\s\S]*apply_operations_hub_relation_board/, "the data adapter must expose exact Sellpia SKU resolution and atomic board persistence");
assert.match(data, /loadSellpiaRelationVisuals[\s\S]*sellpia_sku_code,sellpia_product_name,sellpia_option_name,image_url,sellpia_override_image_url/, "the board must fetch only bounded visual fields for loaded SKUs");
assert.match(pageFirstMigration, /sku_prefix_number asc nulls last[\s\S]*sku_has_numeric_suffix asc[\s\S]*sku_suffix_number asc nulls first/, "ordinary matrix reads must use natural numeric ordering");
assert.match(css, /relation-workspace-head[\s\S]*relation-edge-row[\s\S]*relation-graph-columns[\s\S]*multi-link-workspace-tabs[\s\S]*multi-link-sku-action-modal/, "scoped edges, on-demand graph columns, workspace tabs, and row-level SKU tools must have visible structure");
assert.match(css, /relation-product-loader[\s\S]*relation-drag-board[\s\S]*relation-board-canvas/, "the product loader and staged node canvas must have visible structure");
assert.match(css, /relation-board-link[\s\S]*relation-board-port[\s\S]*relation-board-drag-ghost[\s\S]*relation-board-drop-active/, "connector lines, node ports, and the cursor-following card must have visible drag feedback");
assert.match(css, /relation-board-node-image[\s\S]*relation-board-node-copy[\s\S]*relation-image-modal/, "relationship thumbnails, split labels, and enlarged image preview must have visible structure");
assert.match(css, /multi-link-component\.is-dependent/, "the preserved SKU detail workspace must retain component dependency styling");

console.log("Operations hub relation organization and natural SKU ordering contract: passed");
