import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
import {representativeFixture} from './fixtures/representativeWiringFixture.mjs';
test('bounded real 1181 source -> inbound -> base -> representative -> seller -> discount -> official XLSX reopen, compact drawer and product Rule UI', {skip:!process.env.REP_REAL_SOURCE_FIXTURE||!process.env.SMARTSTORE_MEDIUM_SAMPLE},async()=>{
 const require=createRequire(path.join(process.env.CODEX_NODE_MODULES,'rep-ui.cjs')),{chromium}=require('playwright');
 const sourceRows=JSON.parse(fs.readFileSync(process.env.REP_REAL_SOURCE_FIXTURE,'utf8')),links=JSON.parse(fs.readFileSync('tests/fixtures/sellerMedium1181.json','utf8')).rows;
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',r=>r.request().url().startsWith('http://localhost/')?r.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ko"><meta charset="utf-8"><h1>상품 대표가 bounded QA · mock RPC / 운영 write 없음</h1><div class="rw"><div id="representative"></div></div><div id="lineage"></div><pre id="result"></pre></html>'}):r.abort());await page.goto('http://localhost/representative');
  for(const name of ['style','rule-workspace','matrix-shadow'])await page.addStyleTag({content:fs.readFileSync('mockups/operations-hub/'+name+'.css','utf8')});
  await page.addScriptTag({content:fs.readFileSync(process.env.XLSX_BROWSER_SCRIPT,'utf8')});await page.addScriptTag({content:fs.readFileSync(require.resolve('jszip/dist/jszip.min.js'),'utf8')});
  for(const n of ['representative-price','rule-registry','discount-price-math','platform-rule-service','price-result-materializer','value-state-model','matrix-shadow','price-proof','seller-source-parsers','seller-export-adapter','representative-price-workspace'])await page.addScriptTag({content:fs.readFileSync('mockups/operations-hub/'+n+'.js','utf8')});
  await page.addScriptTag({content:'window.representativeFixture='+representativeFixture.toString()});
  const report=await page.evaluate(async({sourceRows,links,bytes})=>{
   const f=window.fixture=representativeFixture({sourceRows}),M=HubValueStateModel,P=HubPriceProof;
   for(const [sku,option] of links)f.products[sku].__sellerPriceComponents.smartstore.seller_option_code=option;
   const summary=await f.run();if(summary.errorRows||summary.totalSkus!==31)throw Error('full product materialization failed');
   const representative=f.read(),expected=sourceRows.map(r=>(Number(r.purchase_price)+1000)*2).sort((a,b)=>a-b)[15];
   if(representative.value!==expected||representative.contributors.length!==31)throw Error('source -> lower-middle calculation failed');
   const file=new File([new Uint8Array(bytes)],'actual-smartstore-1181.xlsx'),before=(await SystemV3SellerParsers.parseSellerFiles('smartstore',[file],{price:true,discount:true,inventory:true})).normalizedRows;
   if(before.length!==31)throw Error('carrier membership changed');
   const ops=f.skus.map(sku=>{const identity=f.products[sku].__sellerPriceComponents.smartstore,c=before.find(c=>c.product_code===identity.seller_product_code&&c.option_code===identity.seller_option_code),rows=f.writes.filter(r=>r.sku===sku&&r.scope==='smartstore');if(!c||rows.length!==4)throw Error('exact carrier identity failed');const get=field=>rows.find(r=>r.field===field),record=get('platform_final_price'),carrier=M.priceTuple({base:c.base_price,discounted:c.discounted_base_price,option:c.option_price,final:c.final_price,terms:c.discount_terms}),target=M.priceTuple({base:get('platform_registration_price').value,discounted:get('platform_discount_price').value,option:get('platform_option_price').value,final:record.value,terms:record.result_details.discount_terms});return {sku,product_code:c.product_code,option_code:c.option_code,carrier_before:carrier,effective_target:P.facts(target),internal_target:target,record,source_row_no:c.source_row_no};});
   const items=ops.map(o=>M.serializerItem({source_channel:'smartstore',seller_product_code:o.product_code,seller_option_code:o.option_code,sellpia_sku_code:o.sku,field_key:'sellpia_sale_price',before:o.carrier_before,after:o.effective_target},{fileName:file.name,sourceRowNo:o.source_row_no}));
   const serialized=await SystemV3SellerExport.transformSellerFile(file,items);if(serialized.skippedItems.length||serialized.appliedItems.length!==31)throw Error('serializer set mismatch');
   const reopened=(await SystemV3SellerParsers.parseSellerFiles('smartstore',[new File([serialized.blob],file.name)],{price:true,discount:true,inventory:true})).normalizedRows;
   for(const op of ops){const c=reopened.find(c=>c.product_code===op.product_code&&c.option_code===op.option_code);if(!M.equal(P.facts(M.priceTuple({base:c.base_price,discounted:c.discounted_base_price,option:c.option_price,final:c.final_price,terms:c.discount_terms})),op.effective_target)||!M.equal(P.facts(op.internal_target),op.effective_target)||!op.record.rule_versions.some(v=>v.id==='representative'))throw Error('disconnected facts/provenance');if(c.stock!==before.find(b=>b.option_code===c.option_code).stock)throw Error('stock changed outside action');}
   const b1=await JSZip.loadAsync(await file.arrayBuffer()),b2=await JSZip.loadAsync(await serialized.blob.arrayBuffer());let preserved=0;
   for(const name of Object.keys(b1.files))if(!b1.files[name].dir&&!['xl/styles.xml','xl/worksheets/sheet1.xml'].includes(name)){if((await b1.file(name).async('base64'))!==(await b2.file(name).async('base64')))throw Error('workbook part changed '+name);preserved++;}
   document.querySelector('#lineage').innerHTML=HubMatrixShadow.renderDetail({...f.products[f.skus[0]],__hubRepresentativePrice:representative});
   const old=f.base.get(f.skus[0]);old.generation_id++;if(f.read().status!=='stale')throw Error('generation not stale');old.generation_id--;
   f.representative.is_active=false;if(f.read().value!==null||!f.read().stored_history)throw Error('inactive history promoted');f.representative.is_active=true;
   const rpc=SystemV3Data;window.qaUi={calls:[],rules:[{id:'representative',tag_id:'rep-tag',version:1,tag_name:'대표가_중간',selection:'lower_middle'}],product:representative};
   rpc.productPrice=async(action,body)=>{qaUi.calls.push({action,body});if(action==='rules')return {rules:structuredClone(qaUi.rules)};if(['read','inspect'].includes(action))return {rows:[structuredClone(qaUi.product)]};if(action==='save_rule'){const saved={...body,id:'representative',tag_id:'rep-tag',version:2};qaUi.rules=[{...saved,tag_name:body.name}];return saved;}if(action==='assign'){qaUi.product.rule.version++;return {};}throw Error('unexpected UI RPC '+action);};
   await HubRepresentativeWorkspace.mount(document.querySelector('#representative'));
   const outcome={status:'PASS',mock_rpc:true,real_source_skus:31,materializer_rows:summary.persistedRows,representative:expected,artifact_operations:31,reopened_facts:31,preserved_workbook_parts:preserved,stock_mutations:0,baseline_commits:0,marketplace_writes:0,bytes:[...new Uint8Array(await serialized.blob.arrayBuffer())]};document.querySelector('#result').textContent=JSON.stringify({...outcome,bytes:'[omitted]'},null,2);return outcome;
  },{sourceRows,links,bytes:[...fs.readFileSync(process.env.SMARTSTORE_MEDIUM_SAMPLE)]});
  await page.locator('#rep-rule').selectOption('representative');await page.locator('#rep-product').fill('1181');await page.locator('#rep-inspect').click();await page.waitForFunction(()=>document.querySelector('#rep-detail').textContent.includes('옵션 31개'));
  assert.equal(await page.locator('#rep-detail tbody tr').count(),31);assert.equal(await page.locator('#rep-detail tbody tr td:last-child').allTextContents().then(values=>values.every(v=>v==='확인')),true);await page.locator('#rep-name').fill('대표가 QA 이름');await page.locator('#rep-save').click();await page.waitForFunction(()=>qaUi.rules[0].version===2);
  const calls=await page.evaluate(()=>qaUi.calls);assert.equal(calls.find(c=>c.action==='save_rule').body.version,1);assert.equal(calls.filter(c=>c.action==='assign').length,0,'inspection/save never assigns automatically');
  assert.match(await page.locator('#lineage').innerText(),/선택 contributor/);assert.deepEqual(errors,[]);
  const output=process.env.REP_WIRING_OUTPUT;fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'representative-canary.xlsx'),Buffer.from(report.bytes));delete report.bytes;fs.writeFileSync(path.join(output,'browser-qa.json'),JSON.stringify(report,null,2));await page.screenshot({path:path.join(output,'representative-browser.png'),fullPage:true});
 }finally{await browser.close();}
});
