import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const app=fs.readFileSync(new URL('../mockups/operations-hub/app.js',import.meta.url),'utf8');
const start=app.indexOf('const matrixFilterTagState =');
const end=app.indexOf('\nmountMatrixFilterTagAction();',start);
const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{id,value:'',textContent:'',innerHTML:'',disabled:false,hidden:true,focus(){}});return nodes.get(id);};
const initial={search:'1014',searchSources:['sellpia','smartstore'],status:'connected',sort:'sku_asc',advancedFilter:{logic:'and',conditions:[{field:'material',op:'eq',value:'실버'}]},excludeCombinationSkus:true,includeRelatedSkuContext:true,codeListSkus:['input-a'],codeListRows:[{sellpia_sku_code:'input-a',nested:{input:'kept'}}],rows:[{sellpia_sku_code:'page-only'}],total:1};
const skus=Array.from({length:2300},(_,i)=>'SKU'+i);let request,applied,refreshes=0,events=0;
const context={console,structuredClone,Set,Number,String,Boolean,Event:class{constructor(type){this.type=type;}},matrixState:initial,cloneAdvancedFilter:structuredClone,escapeHtml:v=>String(v??''),formatNumber:v=>String(v),materializationWarning:()=>'',document:{getElementById:node,querySelectorAll:()=>[node('close')]},window:{dispatchEvent:e=>{assert.equal(e.type,'hub-rules-changed');events++;}},materializeHubPrices:async(skus,{onProgress})=>{onProgress?.({phase:'batch-complete',totalSkus:skus.length,completedSkus:1150,persistedRows:skus.length*4});assert.match(node('matrix-filter-tag-status').textContent,/1150 \/ 2300 SKU \(50%\)/);return {totalSkus:skus.length,persistedRows:skus.length*4,errorRows:0};},loadLiveMatrix:async()=>{refreshes++;},liveData:{loadAllFilteredSkus:async(options,{onProgress})=>{request=options;onProgress(1000,2300);return {skus,total:2300};},loadTags:async()=>[{tag_id:'uuid-tag',tag_name:'전체 테스트'}],applyTagToSkus:async input=>{applied=input;return {sku_count:input.skus.length};}}};
vm.createContext(context);vm.runInContext(app.slice(start,end)+'\nthis.state=matrixFilterTagState;',context);
await context.openMatrixFilterTag();assert.equal(node('matrix-filter-tag-count').textContent,'필터 결과 전체 2300개 SKU');
assert.equal(request.search,'1014');assert.equal(request.includeRelatedSkuContext,false);assert.equal(request.excludeCombinationSkus,true);assert.equal(request.codeListRows[0].nested.input,'kept');assert.deepEqual([...request.searchSources],['sellpia','smartstore']);
initial.search='changed after opening';initial.searchSources.push('ably');initial.advancedFilter.conditions[0].value='금';initial.codeListRows[0].nested.input='changed';
assert.equal(request.search,'1014');assert.equal(request.advancedFilter.conditions[0].value,'실버');assert.equal(request.codeListRows[0].nested.input,'kept');
node('matrix-filter-tag-select').value='uuid-tag';context.updateMatrixFilterTagApply();assert.equal(node('matrix-filter-tag-apply').disabled,false);
await context.applyMatrixFilterTag();assert.equal(applied.action,'add');assert.equal(applied.tagId,'uuid-tag');assert.equal(applied.skus.length,2300);assert.equal(applied.skus.includes('page-only'),false);assert.equal(applied.skus[2299],'SKU2299');assert.equal(refreshes,1);assert.equal(events,0);assert.equal(node('matrix-filter-tag-apply').disabled,true);
assert.equal(context.state.skus.length,0,'successful application cannot be resubmitted from old snapshot');
context.liveData.loadAllFilteredSkus=async()=>({skus:[],total:0});await context.openMatrixFilterTag();node('matrix-filter-tag-select').value='uuid-tag';context.updateMatrixFilterTagApply();assert.equal(node('matrix-filter-tag-apply').disabled,true);
context.liveData.loadAllFilteredSkus=async()=>{throw Error('lookup failed');};await context.openMatrixFilterTag();assert.match(node('matrix-filter-tag-error').textContent,/lookup failed/);assert.equal(node('matrix-filter-tag-apply').disabled,true);
console.log('PASS filter-all tag action: full2300resolved SKUs, immutable exact filter snapshot, no page/checkbox targeting, one apply action, empty/error handling');
