import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

const js=fs.readFileSync('mockups/operations-hub/tag-management-v2.js','utf8');
const css=fs.readFileSync('mockups/operations-hub/tag-management-v2.css','utf8');
const data=fs.readFileSync('mockups/operations-hub/data-service.js','utf8');
const html=fs.readFileSync('mockups/operations-hub/index.html','utf8');
const rules=fs.readFileSync('mockups/operations-hub/rule-workspace.js','utf8');

test('tag-centric manager exposes saved-assignment download and member editing',()=>{
  assert.match(js,/태그별 관리/);
  assert.match(js,/현재 적용 목록 XLSX/);
  assert.match(js,/전체 적용 해제/);
  assert.match(js,/선택 해제/);
  assert.match(js,/id="tag-new-open"[^>]*>새 태그/);
  assert.match(js,/id="tag-new-formula"[^>]*type="checkbox"/);
  assert.match(js,/가격 수식 사용/);
  assert.match(js,/class="tag-rule-formula"/);
  assert.match(js,/rule\.config\?\.steps/);
  assert.match(js,/결과 →/);
  assert.match(js,/선택 SKU에 현재 태그 적용/);
  assert.match(js,/renameProductTag/);
  assert.match(js,/loadTagMemberSearch\(\{tagId:state\.selectedTagId,page:state\.page/);
  assert.doesNotMatch(js,/loadProducts\(\{page:state\.page/);
  assert.match(js,/→ 그대로 사용/);
  assert.match(js,/data-tag-kind="plain"[^>]*>가격 계산 없음/);
  assert.match(js,/data-tag-kind="formula"[^>]*>가격 계산/);
  assert.doesNotMatch(js,/data-tag-kind="carrier"/);
  assert.match(js,/MATRIX · 가격 계산/);
  assert.match(js,/ABLY EXPORT ·/);
  assert.match(js,/가격 계산 · MATRIX/);
  assert.match(js,/내보내기 정책 · ABLY/);
  assert.match(js,/Matrix 가격 자체는 변경하지 않습니다/);
  assert.doesNotMatch(js,/workDocument\('list','formula'\)/);
  assert.match(js,/createProductTag\(\{name,color,group:'운영'\}\)/);
  assert.match(js,/openForTag\(\{name,color,group:'가격 수식'\}\)/);
  assert.match(js,/loadTagMembers/);
  assert.match(js,/removeTagMembers/);
  assert.match(js,/syncTagAssignments/);
  assert.match(js,/id="tag-ably-policy"/);
  assert.doesNotMatch(js,/>ABLY ·/);
  assert.match(js,/saveAblyCarrierPolicy/);
  assert.match(js,/XLSX\.writeFile/);
  assert.match(css,/tag-manager-v2/);
  assert.match(css,/grid-template-columns:minmax\(0,1fr\) auto!important/);
  assert.match(data,/async function loadTagCatalog/);
  assert.match(data,/async function loadTagMembers/);
  assert.match(data,/async function removeTagMembers/);
  assert.match(data,/carrier-policy:tag:/);
  assert.match(data,/async function loadAblyCarrierPoliciesForSkus/);
  assert.match(data,/async function saveAblyCarrierPolicy/);
  assert.doesNotMatch(data,/hub_rules\.config[^\n]*representativeStrategy/);
  assert.match(js,/id="tag-upload-sync" type="button">엑셀 업로드/);
  assert.match(js,/function openUpload\(\)\{\s*const tag=currentTag\(\);\s*setStatus/);
  assert.match(js,/openTagImport\(\{openFilePicker:true,tagId:tag\?\.tag_id\|\|null\}\)/);
  assert.match(js,/formatTagWorkbookSkuColumn/);
  assert.match(js,/addTagWorkbookMetadata/);
  assert.match(rules,/if\(openFilePicker\)fileInput\.click\(\)/);
  assert.match(rules,/const process=files=>run\(\(\)=>previewTagImportFiles/);
  assert.match(rules,/fileInput\.onchange=\(\)=>process\(fileInput\.files\)/);
  assert.match(rules,/fileRows\(file,\{tagImport:true,withMetadata:true\}\)/);
  assert.match(rules,/id="rw-new">새 수식 태그/);
  assert.match(rules,/const explicitTag=readTagContext\(\),tag=explicitTag\|\|linkedTagContext\(current\(\)\)/);
  assert.match(rules,/state\.steps=structuredClone\(imported\.config\?\.steps\|\|\[\]\)/);
  assert.doesNotMatch(rules,/개별 Rule/);
  assert.doesNotMatch(rules,/D\.ruleRegistry\('save'/);
  assert.match(html,/tag-management-v2\.css/);
  assert.match(html,/rule-workspace\.js\?v=20260918-tag-partial-v2/);
  assert.match(html,/ably-price-projection\.js\?v=20260929-ably-carrier-policy-v1/);
  assert.match(html,/tag-management-v2\.js\?v=20260929-ably-carrier-policy-v1/);
});
