import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {fileURLToPath} from 'node:url';
const root=new URL('../mockups/operations-hub/',import.meta.url),browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.route('**/*',r=>r.abort());await page.setContent('<html><body><main id="attributes" class="page active-page"></main><main id="price-rules" class="page"></main></body></html>');
 await page.addStyleTag({path:fileURLToPath(new URL('rule-workspace.css',root))});
 await page.evaluate(()=>{
  const copy=v=>structuredClone(v);window.qa={tags:[],rules:[],assignments:[],calls:[],simpleCalls:0,fail:false,pages:[]};
  window.SystemV3Data={loadProducts:async()=>({rows:[],count:0}),loadTags:async()=>copy(qa.tags),loadFormulaProducts:async()=>[],ruleRegistry:async action=>{if(action!=='list')throw Error('Use atomic tag-rule save');return copy({rules:qa.rules,assignments:qa.assignments,dependencies:[]});},
   createProductTag:async({name,color,group})=>{qa.simpleCalls++;const tag={tag_id:'simple',tag_name:name,tag_color:color,tag_group:group};qa.tags.push(tag);return tag;},
   saveTagRule:async payload=>{qa.calls.push(copy(payload));if(qa.fail)throw Error('같은 단계 Rule 충돌 · 전체 저장 취소');const {tag,rule}=payload,id=tag.id||'tag-'+qa.calls.length,savedTag={tag_id:id,tag_name:tag.name,tag_color:tag.color,tag_group:tag.group};qa.tags=qa.tags.filter(t=>t.tag_id!==id);qa.tags.push(savedTag);const scopes=HubRuleRegistry.isPlatform(rule.target_field)&&!rule.scope?['smartstore','makeshop','ably']:[rule.scope];const savedRules=scopes.map(scope=>({...copy(rule),id:rule.id||'rule-'+qa.calls.length+'-'+scope,scope,source_scope:HubRuleRegistry.isPlatform(rule.source_field)?rule.source_scope||scope:'',tag_id:id,version:(rule.version||0)+1,is_active:true}));for(const r of savedRules){qa.rules=qa.rules.filter(old=>old.id!==r.id);qa.rules.push(r);qa.assignments=qa.assignments.filter(a=>a.rule_id!==r.id);for(const sku of ['tagged-1','tagged-2'])qa.assignments.push({sku,rule_id:r.id,target_field:r.target_field,scope:r.scope});}return copy({tag:savedTag,rules:savedRules});}
  };window.showPage=id=>{qa.pages.push(id);document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active-page',p.id===id));void HubPriceWorkspace.refresh();};
  window.HubPlatformRules={calculate:async()=>({rows:[],errors:[]})};
  window.HubPriceMaterializer={materialize:async({skus})=>({totalSkus:skus.length,persistedRows:skus.length*4,errorRows:0,status:'complete'})};
 });
 for(const name of ['rule-registry.js','rule-workspace.js','attributes-page.js'])await page.addScriptTag({path:fileURLToPath(new URL(name,root))});
 await page.evaluate(()=>SystemV3AttributesPage.show());
 const idle=()=>page.waitForFunction(()=>!HubPriceWorkspace.state.busy);
 await page.locator('.attributes-new-tag summary').click();await page.locator('#attributes-new-tag-name').fill('공통 순서 수식 태그');await page.locator('#attributes-new-tag-color').fill('#ff99aa');await page.locator('#attributes-new-tag-formula').check();await page.locator('#attributes-create-tag').click();await idle();
 assert.equal(await page.evaluate(()=>qa.tags.length),0,'opening draft must not create orphan tag');assert.equal(await page.evaluate(()=>qa.simpleCalls),0);assert.equal(await page.locator('#rw-tag-name').inputValue(),'공통 순서 수식 태그');assert.equal(await page.locator('#rw-name').inputValue(),'공통 순서 수식 태그 수식');
 await page.locator('#rw-source-field').selectOption('source_base_price');await page.locator('#rw-add-op').click();await page.locator('.rw-op input').nth(0).fill('100');await page.locator('#rw-add-op').click();await page.locator('.rw-op').nth(1).locator('select').first().selectOption('multiply');await page.locator('.rw-op input').nth(1).fill('2');await page.locator('.rw-op [data-up]').nth(1).click();
 await page.evaluate(()=>{qa.fail=true;});await page.locator('#rw-save').click();await idle();assert.equal(await page.evaluate(()=>qa.tags.length),0);assert.equal(await page.locator('#rw-tag-name').inputValue(),'공통 순서 수식 태그');assert.deepEqual(await page.locator('.rw-op input').evaluateAll(nodes=>nodes.map(n=>n.value)),['2','100']);assert.match(await page.locator('#rw-save-status').innerText(),/전체 저장 취소/);
 await page.evaluate(()=>{qa.fail=false;});await page.locator('#rw-save').click();await idle();
 const saved=await page.evaluate(()=>({tag:qa.tags[0],rule:qa.rules[0],assignments:qa.assignments}));assert.equal(saved.tag.tag_name,'공통 순서 수식 태그');assert.equal(saved.tag.tag_color,'#ff99aa');assert.equal(saved.rule.tag_id,saved.tag.tag_id);assert.deepEqual(saved.rule.config.steps,[{op:'multiply',value:2},{op:'add',value:100}]);assert.equal(saved.assignments.length,2);assert.ok(saved.assignments.every(a=>a.rule_id===saved.rule.id&&!a.config),'tagged SKU assignments reference one shared rule');assert.match(await page.locator('#rw-save-status').innerText(),/태그와 수식 저장 완료/);
 await page.locator('#rw-tag-back').click();await idle();await page.locator('#attributes-formula-tag').selectOption(saved.tag.tag_id);await page.locator('#attributes-edit-tag-formula').click();await idle();assert.equal(await page.locator('#rw-tag-rule').inputValue(),saved.rule.id);assert.deepEqual(await page.locator('.rw-op input').evaluateAll(nodes=>nodes.map(n=>n.value)),['2','100']);
 await page.locator('.rw-op input').nth(1).fill('200');await page.locator('#rw-tag-return').check();await page.locator('#rw-save').click();await idle();assert.equal(await page.evaluate(()=>qa.rules.length),1);assert.equal(await page.evaluate(()=>qa.rules[0].version),2);assert.equal(await page.evaluate(()=>qa.calls.at(-1).rule.id),saved.rule.id);assert.equal(await page.evaluate(()=>qa.calls.at(-1).rule.version),1);assert.equal(await page.evaluate(()=>qa.calls.at(-1).rule.tag_id),saved.tag.tag_id);assert.equal(await page.evaluate(()=>HubPriceWorkspace.state.tagContext),null);assert.equal(await page.evaluate(()=>qa.pages.at(-1)),'attributes');
 await page.locator('#attributes-new-tag-name').fill('전체판매처 태그');await page.locator('#attributes-new-tag-formula').check();await page.locator('#attributes-create-tag').click();await idle();await page.locator('#rw-target').selectOption('platform_registration_price');await page.locator('#rw-source-field').selectOption('source_base_price');await page.locator('#rw-add-op').click();await page.locator('#rw-save').click();await idle();const group=await page.evaluate(()=>qa.rules.filter(r=>r.name==='전체판매처 태그 수식'));assert.equal(group.length,3);assert.deepEqual(group.map(r=>r.scope),['smartstore','makeshop','ably']);assert.equal(new Set(group.map(r=>r.tag_id)).size,1);
 await page.locator('#rw-tag-back').click();await idle();await page.locator('#attributes-new-tag-name').fill('단순 태그');await page.locator('#attributes-new-tag-formula').uncheck();await page.locator('#attributes-create-tag').click();await page.waitForFunction(()=>qa.simpleCalls===1);assert.equal(await page.evaluate(()=>qa.tags.find(t=>t.tag_id==='simple').tag_name),'단순 태그');
 const callsBefore=await page.evaluate(()=>qa.calls.length);await page.evaluate(async id=>{HubPriceWorkspace.state.tagContext=null;HubPriceWorkspace.state.selected=id;return HubPriceWorkspace.refresh();},saved.rule.id);
 await page.locator('#rw-save').click();await idle();assert.equal(await page.evaluate(()=>qa.calls.length),callsBefore+1);assert.equal(await page.evaluate(()=>qa.calls.at(-1).tag.id),saved.tag.tag_id,'global editor re-save still goes through linked formula tag');assert.equal(await page.evaluate(()=>qa.calls.at(-1).rule.id),saved.rule.id);assert.equal(await page.evaluate(()=>qa.calls.at(-1).rule.tag_id),saved.tag.tag_id);
 console.log('PASS one new-tag flow branches by formula checkbox; draft no-write; atomic tag+formula save; all-platform3 rules; simple tag creation; global edits cannot bypass linked tag.');
}finally{await browser.close();}
