import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const migrationRoot = new URL('../supabase/migrations/', import.meta.url);
async function migration(name) { return readFile(new URL(name, migrationRoot), 'utf8'); }
function functionDefinition(sql, signature) {
  const start = sql.indexOf(signature);
  assert.notEqual(start, -1, `Migration function not found: ${signature}`);
  const bodyStart = sql.indexOf('as $$', start);
  const end = sql.indexOf('\n$$;', bodyStart);
  assert.ok(bodyStart > start && end > bodyStart, `Could not extract migration function: ${signature}`);
  return sql.slice(start, end + 4);
}

const [mathV2, preserveFinal, safeWriters, discountMode] = await Promise.all([
  migration('20260821110000_operations_hub_seller_discount_terms_v2.sql'),
  migration('20260824043243_preserve_target_price_when_editing_discounts.sql'),
  migration('20260903055337_operations_hub_change_target_safety_v1.sql'),
  migration('20260906151217_operations_hub_discount_calculation_mode_v1.sql')
]);
const functions = [
  functionDefinition(mathV2, 'create or replace function operations_private.calculate_operations_hub_discounted_base('),
  functionDefinition(preserveFinal, 'create or replace function operations_private.gross_operations_hub_discount_base('),
  functionDefinition(safeWriters, 'create or replace function public.save_operations_hub_seller_price_draft_v2('),
  functionDefinition(safeWriters, 'create or replace function public.save_operations_hub_seller_discount_draft('),
  functionDefinition(discountMode, 'create or replace function public.save_operations_hub_seller_product_discount_mode_v1(')
];

const db = new PGlite();
const schema = `
  create schema operations_private;
  create table public.operations_hub_matrix_cached (
    sellpia_sku_code text primary key,
    smartstore_product_code text, smartstore_option_code text,
    makeshop_product_code text, makeshop_option_code text,
    ably_product_code text, ably_option_code text
  );
  create table public.operations_hub_price_rule_sets (
    price_rule_set_id bigint primary key, is_active boolean not null default true
  );
  create table public.seller_inventory_snapshots (
    snapshot_id uuid primary key, source_channel text not null, upload_status text not null,
    completed_at timestamptz, created_at timestamptz not null default now()
  );
  create table public.seller_inventory_snapshot_rows (
    snapshot_id uuid not null, product_code text not null, option_code text not null default '',
    price numeric, base_price numeric, discounted_base_price numeric, option_price numeric,
    final_price numeric, discount_terms jsonb, source_row_no integer, raw_payload jsonb not null default '{}',
    source_discount_fingerprint text,
    primary key(snapshot_id, product_code, option_code)
  );
  create table public.operations_hub_change_queue (
    change_id bigint generated by default as identity primary key,
    change_batch_id uuid, sellpia_sku_code text, field_key text, before_value jsonb, after_value jsonb,
    target_channels text[], status text, requested_by text, requested_at timestamptz,
    updated_at timestamptz, source_channel text, seller_product_code text, seller_option_code text,
    seller_option_code_normalized text generated always as (coalesce(nullif(btrim(seller_option_code), ''), '')) stored,
    status_message text, cancelled_at timestamptz, cancelled_by text,
    price_base_before numeric, price_base_after numeric,
    price_discounted_base_before numeric, price_discounted_base_after numeric,
    price_option_before numeric, price_option_after numeric,
    price_final_before numeric, price_final_after numeric,
    option_price_source text, base_price_source text, price_rule_set_id bigint,
    price_calculation_version integer, pricing_input_mode text,
    source_snapshot_id uuid, source_discount_fingerprint text,
    price_discount_terms_before jsonb, price_discount_terms_after jsonb
  );
`;

try {
  await db.exec(schema);
  await db.exec(functions.join('\n\n'));
  await db.exec(`
    insert into public.operations_hub_matrix_cached
      (sellpia_sku_code,smartstore_product_code,smartstore_option_code)
    values ('SKU-20K','P-20K','O-20K'), ('SKU-RULE','P-RULE','O-RULE');
    insert into public.seller_inventory_snapshots(snapshot_id,source_channel,upload_status,completed_at)
    values ('00000000-0000-4000-8000-000000000001','smartstore','ready',now());
    insert into public.seller_inventory_snapshot_rows
      (snapshot_id,product_code,option_code,price,base_price,discounted_base_price,option_price,final_price,discount_terms,source_row_no,raw_payload,source_discount_fingerprint)
    values
      ('00000000-0000-4000-8000-000000000001','P-20K','O-20K',20000,20000,20000,0,20000,'[]',1,'{}','fp-20k'),
      ('00000000-0000-4000-8000-000000000001','P-RULE','O-RULE',100,100,100,0,100,'[]',2,'{}','fp-rule');
  `);

  const manualStart = await db.query(`select * from public.save_operations_hub_seller_price_draft_v2(
    'SKU-20K','smartstore',20000,'final',null,18900,'manual','manual',null,'10000000-0000-4000-8000-000000000001')`);
  assert.equal(Number(manualStart.rows[0].source_base_price), 20000);
  assert.equal(Number(manualStart.rows[0].draft_base_price), 20000);
  assert.equal(Number(manualStart.rows[0].draft_final_price), 18900,
    'actual legacy V2 saver stores the first manual final price against the original base');

  const ruleUpdate = await db.query(`select * from public.save_operations_hub_seller_price_draft_v2(
    'SKU-20K','smartstore',21500,'option',0,null,'original','tag',null,'20000000-0000-4000-8000-000000000002')`);
  assert.equal(Number(ruleUpdate.rows[0].draft_base_price), 21500);
  assert.equal(Number(ruleUpdate.rows[0].draft_final_price), 21500,
    'a later Rule-priced draft reflects its own recalculated base');
  assert.equal(Number(ruleUpdate.rows[0].cancelled_count), 1,
    'newer seller proposal replaces the earlier pending legacy draft');

  const manualAfterRule = await db.query(`select * from public.save_operations_hub_seller_price_draft_v2(
    'SKU-20K','smartstore',21500,'final',null,19900,'manual','manual',null,'30000000-0000-4000-8000-000000000003')`);
  assert.equal(Number(manualAfterRule.rows[0].source_base_price), 20000,
    'original source tuple remains distinguishable from the current proposed tuple');
  assert.equal(Number(manualAfterRule.rows[0].draft_base_price), 21500);
  assert.equal(Number(manualAfterRule.rows[0].draft_final_price), 19900,
    'actual legacy V2 saver accepts the revised manual final after the Rule draft');
  const manualQueue = await db.query(`select status,price_base_after,price_final_after from public.operations_hub_change_queue
    where sellpia_sku_code='SKU-20K' order by change_id`);
  assert.deepEqual(manualQueue.rows.map(row => row.status), ['cancelled','cancelled','pending']);
  assert.equal(Number(manualQueue.rows[2].price_base_after), 21500);
  assert.equal(Number(manualQueue.rows[2].price_final_after), 19900);

  const ruleBase = await db.query(`select * from public.save_operations_hub_seller_price_draft_v2(
    'SKU-RULE','smartstore',200,'option',0,null,'original','tag',null,'40000000-0000-4000-8000-000000000004')`);
  assert.equal(Number(ruleBase.rows[0].draft_base_price), 200);
  assert.equal(Number(ruleBase.rows[0].draft_final_price), 200);
  const discountTerms = [{
    term_key: 'basic', term_type: 'basic', unit: 'amount', value: 150,
    is_baseline: true, rounding_unit: 1, rounding_mode: 'none'
  }];
  const afterDiscount = await db.query(`select * from public.save_operations_hub_seller_product_discount_mode_v1(
    'smartstore','P-RULE',null,$1::jsonb,null,'forward','50000000-0000-4000-8000-000000000005')`,
  [JSON.stringify(discountTerms)]);
  assert.equal(afterDiscount.rows.length, 1);
  assert.equal(Number(afterDiscount.rows[0].source_base_price), 100);
  assert.equal(Number(afterDiscount.rows[0].draft_base_price), 200,
    'discount wrapper inherits the current Rule draft base rather than the older source base');
  assert.equal(Number(afterDiscount.rows[0].draft_discounted_base_price), 50);
  assert.equal(Number(afterDiscount.rows[0].draft_final_price), 50,
    'amount-150 discount against current Rule base 200 yields final 50');
  const discountQueue = await db.query(`select status,price_base_after,price_discounted_base_after,price_final_after,
      price_discount_terms_after,status_message
    from public.operations_hub_change_queue where sellpia_sku_code='SKU-RULE' order by change_id`);
  assert.deepEqual(discountQueue.rows.map(row => row.status), ['cancelled','pending']);
  assert.equal(Number(discountQueue.rows[1].price_base_after), 200);
  assert.equal(Number(discountQueue.rows[1].price_discounted_base_after), 50);
  assert.equal(Number(discountQueue.rows[1].price_final_after), 50);
  assert.deepEqual(discountQueue.rows[1].price_discount_terms_after, discountTerms);
  assert.match(discountQueue.rows[1].status_message, /판매가 유지/);

  console.log('Price decision legacy DB boundary: PASS (actual migration writer functions).');
} catch (error) {
  console.error(error.message);
  throw error;
} finally {
  await db.close();
}

async function runPriceDecisionApplyIntegration() {
  const contractTest = await readFile(new URL('./operationsHubPriceDecisions.db.test.mjs', import.meta.url), 'utf8');
  const setup = contractTest.match(/await db\.exec\(`([\s\S]*?)`\);\s*await db\.exec\(migration\);/);
  assert.ok(setup, 'Reuse the minimal isolated schema and auth fixture from the price-decision PGlite contract test');
  const integrationDb = new PGlite();
  try {
    await integrationDb.exec(setup[1]);
    await integrationDb.exec(`
      alter table public.operations_hub_change_queue drop column seller_option_code_normalized;
      alter table public.operations_hub_change_queue drop column change_id;
      alter table public.operations_hub_change_queue add column change_id bigint generated by default as identity primary key;
      alter table public.operations_hub_change_queue add column change_batch_id uuid;
      alter table public.operations_hub_change_queue add column sellpia_sku_code text;
      alter table public.operations_hub_change_queue add column seller_option_code text;
      alter table public.operations_hub_change_queue add column seller_option_code_normalized text
        generated always as (coalesce(nullif(btrim(seller_option_code), ''), '')) stored;
      alter table public.operations_hub_change_queue add column before_value jsonb;
      alter table public.operations_hub_change_queue add column target_channels text[];
      alter table public.operations_hub_change_queue add column requested_by text;
      alter table public.operations_hub_change_queue add column requested_at timestamptz;
      alter table public.operations_hub_change_queue add column updated_at timestamptz;
      alter table public.operations_hub_change_queue add column status_message text;
      alter table public.operations_hub_change_queue add column cancelled_at timestamptz;
      alter table public.operations_hub_change_queue add column cancelled_by text;
      alter table public.operations_hub_change_queue add column price_base_before numeric;
      alter table public.operations_hub_change_queue add column price_discounted_base_before numeric;
      alter table public.operations_hub_change_queue add column price_option_before numeric;
      alter table public.operations_hub_change_queue add column price_final_before numeric;
      alter table public.operations_hub_change_queue add column option_price_source text;
      alter table public.operations_hub_change_queue add column base_price_source text;
      alter table public.operations_hub_change_queue add column price_rule_set_id bigint;
      alter table public.operations_hub_change_queue add column price_calculation_version integer;
      alter table public.operations_hub_change_queue add column pricing_input_mode text;
      alter table public.operations_hub_change_queue add column source_snapshot_id uuid;
      alter table public.operations_hub_change_queue add column source_discount_fingerprint text;
      alter table public.operations_hub_change_queue add column price_discount_terms_before jsonb;
      create table public.operations_hub_price_rule_sets(price_rule_set_id bigint primary key,is_active boolean default true);
      alter table public.seller_inventory_snapshot_rows add column source_discount_fingerprint text;

      update public.seller_inventory_snapshot_rows set price=20000,base_price=20000,discounted_base_price=20000,
        option_price=0,final_price=20000,discount_terms='[]'::jsonb
      where snapshot_id='00000000-0000-0000-0000-000000000001' and product_code='P-1';
      insert into public.operations_hub_matrix_cached(sellpia_sku_code,makeshop_product_code,makeshop_option_code,
        ably_product_code,ably_option_code) values ('SKU-MAKE','P-MAKE','O-MAKE',null,null),
          ('SKU-ABLY',null,null,'P-ABLY','O-ABLY');
      insert into public.operations_hub_matrix_cached(sellpia_sku_code,smartstore_product_code,smartstore_option_code)
        values ('SKU-RULE','P-RULE','O-RULE');
      insert into public.operations_hub_listing_component_projection
        (mapping_source,listing_id,component_id,source_channel,product_code,option_code,sellpia_sku_code,component_qty,component_role)
      values ('manual','list-make','component-make','makeshop','P-MAKE','O-MAKE','SKU-MAKE',1,'primary'),
        ('manual','list-ably','component-ably','ably','P-ABLY','O-ABLY','SKU-ABLY',1,'primary'),
        ('manual','list-rule','component-rule','smartstore','P-RULE','O-RULE','SKU-RULE',1,'primary');
      insert into public.seller_inventory_snapshots(snapshot_id,source_channel,upload_status,completed_at,created_at)
        values ('00000000-0000-4000-8000-000000000012','makeshop','ready','2026-10-08 01:00:00+00','2026-10-08 01:00:00+00'),
          ('00000000-0000-4000-8000-000000000013','ably','ready','2026-10-08 01:00:00+00','2026-10-08 01:00:00+00');
      insert into public.seller_inventory_snapshot_rows
        (snapshot_id,product_code,option_code,price,base_price,discounted_base_price,option_price,final_price,discount_terms,source_row_no,raw_payload,source_discount_fingerprint)
      values ('00000000-0000-4000-8000-000000000012','P-MAKE','O-MAKE',20000,20000,20000,0,20000,'[]',1,'{}','fp-make'),
        ('00000000-0000-4000-8000-000000000013','P-ABLY','O-ABLY',20000,20000,20000,0,20000,'[]',1,'{}','fp-ably'),
        ('00000000-0000-0000-0000-000000000001','P-RULE','O-RULE',100,100,100,0,100,'[]',3,'{}','fp-rule');
      insert into public.sellpia_stock_snapshots(snapshot_id,upload_status,completed_at,created_at)
        values ('00000000-0000-4000-8000-000000000011','ready','2026-10-08 01:00:00+00','2026-10-08 01:00:00+00');
      insert into public.sellpia_stock_snapshot_rows(snapshot_id,sellpia_sku_code,price,raw_payload)
        values ('00000000-0000-4000-8000-000000000011','SKU-1',20000,'{"sell_price":"20000"}'),
          ('00000000-0000-4000-8000-000000000011','SKU-2',20000,'{"sell_price":"20000"}'),
          ('00000000-0000-4000-8000-000000000011','SKU-MAKE',20000,'{"sell_price":"20000"}'),
          ('00000000-0000-4000-8000-000000000011','SKU-ABLY',20000,'{"sell_price":"20000"}'),
          ('00000000-0000-4000-8000-000000000011','SKU-RULE',100,'{"sell_price":"100"}');
    `);
    await integrationDb.exec(functions.join('\n\n'));
    await integrationDb.exec(await migration('20261008022010_hub_price_decisions_v1.sql'));

    const readGroup = async (source, sku) => {
      const result = await integrationDb.query(`select public.hub_price_decision_read_v1('test-session',$1,array[$2]) as value`, [source, sku]);
      const group = result.rows[0].value.groups[0];
      assert.ok(group, `A current group read should resolve ${source}/${sku}`);
      return group;
    };
    const groupPayload = (group, priceFor = target => target.current_state?.price || target.price) => ({
      seller_product_code: group.seller_product_code,
      expected_revision: group.revision,
      mapping_fingerprint: group.mapping_fingerprint,
      input_fingerprints: group.input_fingerprints,
      snapshot_id: group.snapshot_id,
      sellpia_snapshot_id: group.sellpia_snapshot_id,
      targets: group.targets.map((target,index) => ({
        sku: target.sku,
        member_skus: target.member_skus,
        seller_product_code: group.seller_product_code,
        seller_option_code: target.seller_option_code,
        price: priceFor(target,index)
      }))
    });
    const apply = async (id, body) => (await integrationDb.query(
      `select public.hub_price_decision_apply_v1('test-session',$1::uuid,$2::jsonb) as value`,
      [id, JSON.stringify(body)]
    )).rows[0].value;
    const eventCount = async product => Number((await integrationDb.query(
      `select count(*) as n from operations_private.hub_price_decision_events where seller_product_code=$1`, [product]
    )).rows[0].n);
    const currentRows = async (source, sku) => (await integrationDb.query(
      `select public.hub_price_decision_matrix_read_v1('test-session',array[$1])->'rows' as rows`, [sku]
    )).rows[0].rows.filter(row => row.source_channel === source);
    const originalTuple = () => ({ base:20000, discounted:20000, option:0, final:20000, terms:[] });
    const ruleTuple = (base, option=0) => ({ base, discounted:base, option, final:base+option, terms:[] });

    // Case 1: explicitly apply a manual final-price decision through the new RPC.
    const firstRead = await readGroup('smartstore','SKU-1');
    assert.equal(firstRead.targets[0].price.base,20000);
    const firstBody = {
      source:'smartstore',decision_source:'matrix_manual',reason:'initial manual final price',
      groups:[groupPayload(firstRead,()=>originalTuple())],
      manual_actions:[{kind:'price',sku:'SKU-1',seller_product_code:'P-1',seller_option_code:'O-1',
        target_base_price:20000,input_mode:'final',target_final_price:18900,option_price_source:'manual',base_price_source:'manual'}]
    };
    const firstResult = await apply('10000000-0000-4000-8000-000000000101',firstBody);
    assert.equal(firstResult.rows.length,1);
    assert.deepEqual(firstResult.rows[0].price, {base:20000,discounted:20000,option:-1100,final:18900,terms:[]});
    const firstQueue = (await integrationDb.query(`select price_base_after,price_final_after from public.operations_hub_change_queue where sellpia_sku_code='SKU-1' and status='pending'`)).rows[0];
    assert.equal(Number(firstQueue.price_final_after),18900);

    // Cases 2 and 6: same-price Sellpia source refresh is read-only for the accepted decision.
    const firstEvents = await eventCount('P-1');
    await integrationDb.exec(`
      insert into public.sellpia_stock_snapshots(snapshot_id,upload_status,completed_at,created_at)
      values ('00000000-0000-4000-8000-000000000014','ready','2026-10-09 01:00:00+00','2026-10-09 01:00:00+00');
      insert into public.sellpia_stock_snapshot_rows(snapshot_id,sellpia_sku_code,price,raw_payload)
      values ('00000000-0000-4000-8000-000000000014','SKU-1',20000,'{"sell_price":"20000"}'),
        ('00000000-0000-4000-8000-000000000014','SKU-2',20000,'{"sell_price":"20000"}');
    `);
    const sameSourceRead = await readGroup('smartstore','SKU-1');
    assert.deepEqual(sameSourceRead.targets[0].current_state.price,{base:20000,discounted:20000,option:-1100,final:18900,terms:[]});
    assert.equal(await eventCount('P-1'),firstEvents,'new same-price Sellpia source data does not emit a price decision event');

    // Case 3: calculate Rule price as a candidate (pure local tuple), then apply it explicitly.
    const ruleRead = await readGroup('smartstore','SKU-1');
    const ruleCandidate = ruleRead.targets.map(() => ruleTuple(21500,0));
    assert.equal(await eventCount('P-1'),firstEvents,'candidate computation alone has no database write');
    const ruleBody = {
      source:'smartstore',decision_source:'pricing_rule',reason:'explicit Rule application',
      groups:[groupPayload(ruleRead,(_target,index)=>ruleCandidate[index])]
    };
    ruleBody.groups[0].targets.forEach(target => { target.intent={rule:'synthetic-rule-v1'}; });
    const priorQueueCount = Number((await integrationDb.query(`select count(*) as n from public.operations_hub_change_queue`)).rows[0].n);
    const appliedRule = await apply('20000000-0000-4000-8000-000000000102',ruleBody);
    assert.equal(appliedRule.rows.length,2);
    assert.equal(Number((await integrationDb.query(`select price_base_after from public.operations_hub_change_queue where sellpia_sku_code='SKU-1' and status='pending' order by change_id desc limit 1`)).rows[0].price_base_after),20000,
      'Rule application updates accepted decision state without changing the legacy manual queue');
    assert.equal(Number((await integrationDb.query(`select count(*) as n from public.operations_hub_change_queue`)).rows[0].n),priorQueueCount);
    const ruleState = await currentRows('smartstore','SKU-1');
    assert.deepEqual(ruleState.find(row=>row.seller_option_code==='O-1').price,ruleTuple(21500,0));

    // Cases 4 and 8: manual final after accepted Rule state seeds the real legacy saver from current base,
    // while the previously captured Rule context fails its revision CAS when reused later.
    const capturedRuleContext = structuredClone(ruleRead);
    const currentRuleRead = await readGroup('smartstore','SKU-1');
    const manualAfterRuleBody = {
      source:'smartstore',decision_source:'matrix_manual',reason:'manual final after Rule',
      groups:[groupPayload(currentRuleRead)],
      manual_actions:[{kind:'price',sku:'SKU-1',seller_product_code:'P-1',seller_option_code:'O-1',
        target_base_price:21500,input_mode:'final',target_final_price:19900,option_price_source:'manual',base_price_source:'manual'}]
    };
    await apply('30000000-0000-4000-8000-000000000103',manualAfterRuleBody);
    const manualState = await currentRows('smartstore','SKU-1');
    assert.deepEqual(manualState.find(row=>row.seller_option_code==='O-1').price,ruleTuple(21500,-1600));
    const latestQueue = (await integrationDb.query(`select status,price_base_after,price_final_after from public.operations_hub_change_queue
      where sellpia_sku_code='SKU-1' order by change_id desc limit 1`)).rows[0];
    assert.equal(latestQueue.status,'pending');
    assert.equal(Number(latestQueue.price_base_after),21500);
    assert.equal(Number(latestQueue.price_final_after),19900);
    const lateRuleBody = structuredClone(ruleBody);
    lateRuleBody.groups[0] = groupPayload(capturedRuleContext,(_target,index)=>ruleCandidate[index]);
    lateRuleBody.groups[0].targets.forEach(target=>{target.intent={rule:'late-rule-v1'};});
    await assert.rejects(apply('40000000-0000-4000-8000-000000000104',lateRuleBody),/revision/i,
      'late Rule apply is rejected against the captured stale revision');

    // Case 5: a new 22,000 Sellpia source is only a candidate until explicitly accepted.
    await integrationDb.exec(`
      insert into public.sellpia_stock_snapshots(snapshot_id,upload_status,completed_at,created_at)
      values ('00000000-0000-4000-8000-000000000015','ready','2026-10-10 01:00:00+00','2026-10-10 01:00:00+00');
      insert into public.sellpia_stock_snapshot_rows(snapshot_id,sellpia_sku_code,price,raw_payload)
      values ('00000000-0000-4000-8000-000000000015','SKU-1',22000,'{"sell_price":"22000"}'),
        ('00000000-0000-4000-8000-000000000015','SKU-2',22000,'{"sell_price":"22000"}');
    `);
    const sellpiaRead = await readGroup('smartstore','SKU-1');
    assert.deepEqual((await currentRows('smartstore','SKU-1')).find(row=>row.seller_option_code==='O-1').price,ruleTuple(21500,-1600));
    assert.equal(await eventCount('P-1'),4,'a changed Sellpia source snapshot does not apply itself');
    const observedAt = sellpiaRead.source_observed_at;
    const sourcePrices = Object.fromEntries(sellpiaRead.targets.map(target=>[target.sku,22000]));
    const sellpiaBody = {
      source:'smartstore',decision_source:'sellpia_apply',reason:'explicit Sellpia application',
      groups:[groupPayload(sellpiaRead,target=>ruleTuple(22000,target.current_state?.price.option||0))]
    };
    sellpiaBody.groups[0].targets.forEach(target=>{target.intent={input_mode:'explicit_sellpia',source_prices:sourcePrices,source_observed_at:observedAt};});
    const sellpiaResult=await apply('50000000-0000-4000-8000-000000000105',sellpiaBody);
    assert.equal(sellpiaResult.rows.length,2);
    assert.ok(sellpiaResult.rows.every(row=>row.decision_source==='sellpia_apply'));
    const afterSellpia=await currentRows('smartstore','SKU-1');
    assert.deepEqual(afterSellpia.find(row=>row.seller_option_code==='O-1').price,ruleTuple(22000,-1600));

    // Case 9: replay the same request UUID and body after later decisions returns the stored result unchanged.
    const eventsBeforeReplay=await eventCount('P-1');
    const replay=await apply('10000000-0000-4000-8000-000000000101',firstBody);
    assert.deepEqual(replay,firstResult);
    assert.equal(await eventCount('P-1'),eventsBeforeReplay);

    // Case 10: same numeric tuple from a distinct explicit Rule apply records new provenance.
    const provenanceRead=await readGroup('smartstore','SKU-1');
    const provenanceBody={source:'smartstore',decision_source:'pricing_rule',reason:'same price from revised Rule',
      groups:[groupPayload(provenanceRead,target=>ruleTuple(22000,target.current_state?.price.option||0))]};
    provenanceBody.groups[0].targets.forEach(target=>{target.intent={rule:'synthetic-rule-v2'};});
    const provenanceApply=await apply('60000000-0000-4000-8000-000000000106',provenanceBody);
    assert.ok(provenanceApply.rows.every(row=>row.decision_source==='pricing_rule'));
    const finalCurrent=await currentRows('smartstore','SKU-1');
    const finalOption=finalCurrent.find(row=>row.seller_option_code==='O-1');
    assert.equal(finalOption.decision_source,'pricing_rule');
    assert.deepEqual(finalOption.price,ruleTuple(22000,-1600));
    const finalIntent=(await integrationDb.query(`select intent from operations_private.hub_effective_price_states
      where source_channel='smartstore' and seller_product_code='P-1' and seller_option_code='O-1'`)).rows[0].intent;
    assert.equal(finalIntent.rule,'synthetic-rule-v2');

    // Fresh Rule decision has no legacy queue row: a manual amount discount must seed the actual
    // legacy saver from the accepted current base 200, not the older source base 100.
    const discountRuleRead=await readGroup('smartstore','SKU-RULE');
    const discountRuleBody={source:'smartstore',decision_source:'pricing_rule',reason:'Rule base 200 over source base 100',
      groups:[groupPayload(discountRuleRead,()=>ruleTuple(200,0))]};
    discountRuleBody.groups[0].targets.forEach(target=>{target.intent={rule:'discount-base-200'};});
    await apply('70000000-0000-4000-8000-000000000107',discountRuleBody);
    assert.equal(Number((await integrationDb.query(`select count(*) as n from public.operations_hub_change_queue where sellpia_sku_code='SKU-RULE'`)).rows[0].n),0,
      'a new Rule apply must leave no legacy queue draft');
    const discountCurrent=await readGroup('smartstore','SKU-RULE');
    assert.equal(discountCurrent.targets[0].current_state.price.base,200);
    const amount150=[{term_key:'basic',term_type:'basic',unit:'amount',value:150,is_baseline:true,rounding_unit:1,rounding_mode:'none'}];
    const manualDiscountBody={source:'smartstore',decision_source:'matrix_manual',reason:'manual amount discount against accepted Rule base',
      groups:[groupPayload(discountCurrent)],
      manual_actions:[{kind:'discount',sku:'SKU-RULE',seller_product_code:'P-RULE',seller_option_code:'O-RULE',
        discount_terms:amount150,input_mode:'option',option_price:0}]};
    await apply('80000000-0000-4000-8000-000000000108',manualDiscountBody);
    const discountedCurrent=await currentRows('smartstore','SKU-RULE');
    assert.deepEqual(discountedCurrent[0].price,{base:200,discounted:50,option:0,final:50,terms:amount150});
    const seededAndSaved=(await integrationDb.query(`select status,price_base_after,price_discounted_base_after,price_option_after,
        price_final_after,price_discount_terms_after from public.operations_hub_change_queue where sellpia_sku_code='SKU-RULE' order by change_id desc limit 1`)).rows[0];
    assert.equal(seededAndSaved.status,'pending');
    assert.equal(Number(seededAndSaved.price_base_after),200);
    assert.equal(Number(seededAndSaved.price_discounted_base_after),50);
    assert.equal(Number(seededAndSaved.price_option_after),0);
    assert.equal(Number(seededAndSaved.price_final_after),50);
    assert.deepEqual(seededAndSaved.price_discount_terms_after,amount150);

    // The native discount helper preserves the same 20,000 -> 18,900 -> -1,100 tuple across channels.
    for(const source of ['smartstore','makeshop','ably']){
      const math=(await integrationDb.query(`select operations_private.calculate_operations_hub_discounted_base($1,20000,'[]'::jsonb,null) as discounted`,[source])).rows[0];
      assert.equal(Number(math.discounted)+(-1100),18900,`${source} manual final tuple keeps the signed option adjustment`);
    }
    console.log('Price decision apply integration: PASS (Cases 1-6, 8-10; preview purity covered separately).');
  } finally {
    await integrationDb.close();
  }
}

await runPriceDecisionApplyIntegration();
