import assert from 'node:assert/strict';
await import('../mockups/operations-hub/discount-price-math.js');
await import('../mockups/operations-hub/platform-price-formula.js');
await import('../mockups/operations-hub/tag-price-workspace.js');
const compose=globalThis.PlatformPriceFormula.compose;
const rows=[{sku:'6mm',value:15000},{sku:'8mm',value:17000}];
const settings={mode:'forward',multiplier:1,add:2000,anchor:'lowest',discount:'amount',discountValue:2000};
const forward=compose(rows,settings);
assert.deepEqual(forward.map(r=>[r.platformBase,r.platformOption,r.platformFinal]),[[17000,0,15000],[17000,2000,17000]]);
assert.equal(forward[0].platformTerms[0].value,2000);
const reverse=compose(rows,{...settings,mode:'reverse',add:0});
assert.deepEqual(reverse.map(r=>r.platformFinal),[15000,17000]);
assert.equal(reverse[0].platformBase,17000);
const percentage=compose(rows,{...settings,add:0,discount:'percent',discountValue:10});
assert.deepEqual(percentage.map(r=>r.platformFinal),[13500,15500]);
assert.throws(()=>compose(rows,{...settings,discount:'percent',discountValue:100}));
const price=globalThis.TagPriceModel.calculate('6mm',{'6mm':{actual_inbound_cost:5000,__profile:{sku_tags:[{tag_id:1}]}}},{1:{enabled:true,basis:'inbound',multiplier:3,add:0,unit:1}},{});
assert.equal(price.value,15000);
console.log('PASS inbound basis; platform +2000 then -2000; reverse pricing; percentage and option split');
