alter table public.operations_hub_change_queue
  add column if not exists change_batch_id uuid,
  add column if not exists validation_errors jsonb not null default '[]'::jsonb,
  add column if not exists validated_at timestamptz,
  add column if not exists retry_count integer not null default 0,
  add column if not exists max_retry_count integer not null default 3,
  add column if not exists last_attempt_at timestamptz,
  add column if not exists next_retry_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by text,
  add column if not exists status_message text,
  add column if not exists updated_at timestamptz not null default now();

update public.operations_hub_change_queue
set change_batch_id = gen_random_uuid()
where change_batch_id is null;

alter table public.operations_hub_change_queue
  alter column change_batch_id set default gen_random_uuid(),
  alter column change_batch_id set not null;

alter table public.operations_hub_change_queue
  drop constraint if exists operations_hub_change_queue_status_check;

alter table public.operations_hub_change_queue
  add constraint operations_hub_change_queue_status_check check (
    status in ('pending', 'validated', 'processing', 'applied', 'failed', 'saved', 'cancelled')
  ),
  add constraint operations_hub_change_queue_validation_errors_check check (
    jsonb_typeof(validation_errors) = 'array'
  ),
  add constraint operations_hub_change_queue_retry_count_check check (
    retry_count >= 0 and max_retry_count between 1 and 10 and retry_count <= max_retry_count
  ),
  add constraint operations_hub_change_queue_targets_check check (
    target_channels <@ array['smartstore', 'makeshop', 'ably']::text[]
  );

create unique index if not exists operations_hub_change_queue_batch_item_uidx
  on public.operations_hub_change_queue (
    change_batch_id,
    sellpia_sku_code,
    field_key,
    coalesce(source_channel, ''),
    coalesce(seller_product_code, ''),
    coalesce(seller_option_code, '')
  );

create index if not exists operations_hub_change_queue_workflow_idx
  on public.operations_hub_change_queue (status, updated_at desc, change_id desc);

create index if not exists operations_hub_change_queue_sku_history_idx
  on public.operations_hub_change_queue (sellpia_sku_code, requested_at desc, change_id desc);

create table if not exists public.operations_hub_change_events (
  event_id bigint generated by default as identity primary key,
  change_id bigint not null references public.operations_hub_change_queue(change_id) on delete cascade,
  change_batch_id uuid not null,
  event_type text not null,
  from_status text,
  to_status text,
  message text,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  actor text not null default 'operations_hub_frontend',
  created_at timestamptz not null default now()
);

create index if not exists operations_hub_change_events_change_idx
  on public.operations_hub_change_events (change_id, created_at desc, event_id desc);

create index if not exists operations_hub_change_events_batch_idx
  on public.operations_hub_change_events (change_batch_id, created_at desc, event_id desc);

alter table public.operations_hub_change_events enable row level security;

drop policy if exists "operations hub change events readable" on public.operations_hub_change_events;
create policy "operations hub change events readable"
  on public.operations_hub_change_events for select
  to anon, authenticated
  using (true);

drop policy if exists "operations hub change events insertable" on public.operations_hub_change_events;
create policy "operations hub change events insertable"
  on public.operations_hub_change_events for insert
  to anon, authenticated
  with check (actor = 'operations_hub_frontend');

drop policy if exists "operations hub queue updatable" on public.operations_hub_change_queue;
create policy "operations hub queue updatable"
  on public.operations_hub_change_queue for update
  to anon, authenticated
  using (requested_by = 'operations_hub_frontend')
  with check (requested_by = 'operations_hub_frontend');

revoke all on table public.operations_hub_change_events from public;
grant select, insert on table public.operations_hub_change_events to anon, authenticated;
grant usage, select on sequence public.operations_hub_change_events_event_id_seq to anon, authenticated;
grant select, insert, update on table public.operations_hub_change_queue to anon, authenticated;

create or replace function public.log_operations_hub_change_event()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_event_type text;
begin
  if tg_op = 'INSERT' then
    v_event_type := 'created';
    insert into public.operations_hub_change_events (
      change_id, change_batch_id, event_type, from_status, to_status, message, payload, actor, created_at
    ) values (
      new.change_id, new.change_batch_id, v_event_type, null, new.status, new.status_message,
      jsonb_build_object('field_key', new.field_key, 'target_channels', new.target_channels),
      new.requested_by, new.requested_at
    );
    return new;
  end if;

  if old.status is not distinct from new.status
     and old.error_message is not distinct from new.error_message
     and old.validation_errors is not distinct from new.validation_errors
     and old.retry_count is not distinct from new.retry_count then
    return new;
  end if;

  v_event_type := case
    when old.status = 'failed' and new.status = 'pending' then 'retried'
    when new.status = 'validated' then 'validated'
    when new.status = 'processing' then 'processing'
    when new.status = 'applied' then 'applied'
    when new.status = 'failed' then 'failed'
    when new.status = 'cancelled' then 'cancelled'
    else 'status_changed'
  end;

  insert into public.operations_hub_change_events (
    change_id, change_batch_id, event_type, from_status, to_status, message, payload, actor
  ) values (
    new.change_id, new.change_batch_id, v_event_type, old.status, new.status,
    coalesce(new.status_message, new.error_message),
    jsonb_build_object(
      'validation_errors', new.validation_errors,
      'retry_count', new.retry_count,
      'last_attempt_at', new.last_attempt_at,
      'next_retry_at', new.next_retry_at
    ),
    coalesce(new.cancelled_by, new.requested_by, 'operations_hub_frontend')
  );
  return new;
end;
$$;

drop trigger if exists operations_hub_change_queue_event_trigger on public.operations_hub_change_queue;
create trigger operations_hub_change_queue_event_trigger
after insert or update of status, error_message, validation_errors, retry_count
on public.operations_hub_change_queue
for each row execute function public.log_operations_hub_change_event();

drop function if exists public.apply_operations_hub_sellpia_changes(text, jsonb);
create function public.apply_operations_hub_sellpia_changes(
  p_sku text,
  p_changes jsonb,
  p_batch_id uuid default null
)
returns table(saved_count integer, queued_count integer, saved_at timestamptz, change_batch_id uuid)
language plpgsql
security invoker
set search_path = public, operations_private, pg_temp
as $$
declare
  v_change jsonb;
  v_field text;
  v_after text;
  v_targets text[];
  v_status text;
  v_saved integer := 0;
  v_queued integer := 0;
  v_inserted integer := 0;
  v_saved_at timestamptz := now();
  v_batch_id uuid := coalesce(p_batch_id, gen_random_uuid());
begin
  p_sku := btrim(p_sku);
  if nullif(p_sku, '') is null then raise exception '셀피아 SKU가 필요합니다.'; end if;
  if not exists (
    select 1 from operations_private.operations_hub_matrix_core matrix
    where matrix.sellpia_sku_code = p_sku
  ) then raise exception '매트릭스에 없는 셀피아 SKU입니다: %', p_sku; end if;
  if jsonb_typeof(p_changes) <> 'array' or jsonb_array_length(p_changes) = 0 then
    raise exception '저장할 변경사항이 없습니다.';
  end if;

  select array_remove(array[
    case when matrix.smartstore_product_code is not null then 'smartstore' end,
    case when matrix.makeshop_product_code is not null then 'makeshop' end,
    case when matrix.ably_product_code is not null then 'ably' end
  ], null)
  into v_targets
  from operations_private.operations_hub_matrix_core matrix
  where matrix.sellpia_sku_code = p_sku;

  for v_change in select value from jsonb_array_elements(p_changes)
  loop
    v_field := v_change ->> 'field_key';
    v_after := v_change ->> 'after';
    if v_field not in (
      'sellpia_own_code', 'sellpia_product_name', 'sellpia_option_name',
      'sellpia_current_stock', 'sellpia_sale_price', 'sellpia_image'
    ) then raise exception '지원하지 않는 셀피아 필드입니다: %', v_field; end if;
    if v_field in ('sellpia_current_stock', 'sellpia_sale_price')
       and (v_after !~ '^\d+(\.\d+)?$' or v_after::numeric < 0) then
      raise exception '재고와 판매가는 0 이상의 숫자여야 합니다.';
    end if;
    if v_field = 'sellpia_image' and v_after !~ '^sellpia/[0-9A-Za-z._-]+[.]jpg$' then
      raise exception '이미지 저장 경로가 올바르지 않습니다.';
    end if;

    insert into public.operations_hub_sellpia_overrides (
      sellpia_sku_code, own_code, product_name, option_name,
      current_stock, sale_price, image_storage_path, updated_by, updated_at
    ) values (
      p_sku,
      case when v_field = 'sellpia_own_code' then nullif(v_after, '') end,
      case when v_field = 'sellpia_product_name' then nullif(v_after, '') end,
      case when v_field = 'sellpia_option_name' then nullif(v_after, '') end,
      case when v_field = 'sellpia_current_stock' then v_after::integer end,
      case when v_field = 'sellpia_sale_price' then v_after::numeric end,
      case when v_field = 'sellpia_image' then v_after end,
      'operations_hub_frontend', v_saved_at
    )
    on conflict (sellpia_sku_code) do update set
      own_code = case when v_field = 'sellpia_own_code' then nullif(v_after, '') else operations_hub_sellpia_overrides.own_code end,
      product_name = case when v_field = 'sellpia_product_name' then nullif(v_after, '') else operations_hub_sellpia_overrides.product_name end,
      option_name = case when v_field = 'sellpia_option_name' then nullif(v_after, '') else operations_hub_sellpia_overrides.option_name end,
      current_stock = case when v_field = 'sellpia_current_stock' then v_after::integer else operations_hub_sellpia_overrides.current_stock end,
      sale_price = case when v_field = 'sellpia_sale_price' then v_after::numeric else operations_hub_sellpia_overrides.sale_price end,
      image_storage_path = case when v_field = 'sellpia_image' then v_after else operations_hub_sellpia_overrides.image_storage_path end,
      updated_by = 'operations_hub_frontend',
      updated_at = v_saved_at;

    v_status := case
      when v_field in ('sellpia_current_stock', 'sellpia_sale_price') and cardinality(coalesce(v_targets, '{}'::text[])) > 0 then 'pending'
      else 'saved'
    end;

    if v_status = 'pending' then
      update public.operations_hub_change_queue queue
      set status = 'cancelled', cancelled_at = v_saved_at, cancelled_by = 'operations_hub_frontend',
          status_message = '더 최신 변경으로 대체됨', updated_at = v_saved_at
      where queue.sellpia_sku_code = p_sku
        and queue.field_key = v_field
        and queue.source_channel is null
        and queue.status in ('pending', 'validated', 'failed')
        and queue.change_batch_id <> v_batch_id;
    end if;

    insert into public.operations_hub_change_queue (
      change_batch_id, sellpia_sku_code, field_key, before_value, after_value,
      target_channels, status, requested_by, requested_at, updated_at
    ) values (
      v_batch_id, p_sku, v_field, v_change -> 'before', to_jsonb(v_after),
      case when v_status = 'pending' then coalesce(v_targets, '{}'::text[]) else '{}'::text[] end,
      v_status, 'operations_hub_frontend', v_saved_at, v_saved_at
    ) on conflict do nothing;
    get diagnostics v_inserted = row_count;
    v_saved := v_saved + 1;
    if v_status = 'pending' then v_queued := v_queued + v_inserted; end if;
  end loop;

  return query select v_saved, v_queued, v_saved_at, v_batch_id;
end;
$$;

revoke all on function public.apply_operations_hub_sellpia_changes(text, jsonb, uuid) from public;
grant execute on function public.apply_operations_hub_sellpia_changes(text, jsonb, uuid) to anon, authenticated;

drop function if exists public.save_operations_hub_seller_listing(text, text, text, text, text, text, boolean);
create function public.save_operations_hub_seller_listing(
  p_sku text,
  p_source text,
  p_product_code text,
  p_option_code text,
  p_product_name text,
  p_option_name text,
  p_queue boolean default false,
  p_batch_id uuid default null
)
returns table(saved_count integer, queued_count integer, saved_at timestamptz, change_batch_id uuid)
language plpgsql
security invoker
set search_path = public, operations_private, pg_temp
as $$
declare
  v_current public.seller_inventory_latest%rowtype;
  v_saved integer := 0;
  v_queued integer := 0;
  v_inserted integer := 0;
  v_saved_at timestamptz := now();
  v_batch_id uuid := coalesce(p_batch_id, gen_random_uuid());
  v_status text := case when p_queue then 'pending' else 'saved' end;
begin
  p_sku := btrim(p_sku);
  p_source := lower(btrim(p_source));
  if p_source not in ('smartstore', 'makeshop', 'ably') then
    raise exception '지원하지 않는 판매처입니다: %', p_source;
  end if;
  if not exists (
    select 1 from operations_private.operations_hub_matrix_core matrix
    where matrix.sellpia_sku_code = p_sku
  ) then raise exception '매트릭스에 없는 셀피아 SKU입니다: %', p_sku; end if;

  select item.* into v_current
  from public.seller_inventory_latest item
  where item.source_channel = p_source
    and item.product_code = btrim(p_product_code)
    and item.option_code = coalesce(btrim(p_option_code), '')
  limit 1;
  if not found then raise exception '최신 판매처 원본에서 편집 대상을 찾을 수 없습니다.'; end if;

  insert into public.operations_hub_seller_listing_overrides (
    source_channel, product_code, option_code, product_name, option_name, updated_by, updated_at
  ) values (
    p_source, v_current.product_code, v_current.option_code,
    nullif(btrim(p_product_name), ''), nullif(btrim(p_option_name), ''),
    'operations_hub_frontend', v_saved_at
  ) on conflict (source_channel, product_code, option_code) do update set
    product_name = excluded.product_name,
    option_name = excluded.option_name,
    updated_by = 'operations_hub_frontend',
    updated_at = excluded.updated_at;

  if coalesce(btrim(p_product_name), '') is distinct from coalesce(btrim(v_current.product_name), '') then
    if p_queue then
      update public.operations_hub_change_queue queue
      set status = 'cancelled', cancelled_at = v_saved_at, cancelled_by = 'operations_hub_frontend',
          status_message = '더 최신 변경으로 대체됨', updated_at = v_saved_at
      where queue.sellpia_sku_code = p_sku and queue.field_key = 'seller_product_name'
        and queue.source_channel = p_source
        and queue.seller_product_code = v_current.product_code
        and queue.seller_option_code = v_current.option_code
        and queue.status in ('pending', 'validated', 'failed')
        and queue.change_batch_id <> v_batch_id;
    end if;
    insert into public.operations_hub_change_queue (
      change_batch_id, sellpia_sku_code, field_key, before_value, after_value, target_channels,
      status, requested_by, requested_at, updated_at, source_channel, seller_product_code, seller_option_code
    ) values (
      v_batch_id, p_sku, 'seller_product_name', to_jsonb(v_current.product_name), to_jsonb(p_product_name), array[p_source],
      v_status, 'operations_hub_frontend', v_saved_at, v_saved_at, p_source, v_current.product_code, v_current.option_code
    ) on conflict do nothing;
    get diagnostics v_inserted = row_count;
    v_saved := v_saved + 1;
    if p_queue then v_queued := v_queued + v_inserted; end if;
  end if;

  if coalesce(btrim(p_option_name), '') is distinct from coalesce(btrim(v_current.option_name), '') then
    if p_queue then
      update public.operations_hub_change_queue queue
      set status = 'cancelled', cancelled_at = v_saved_at, cancelled_by = 'operations_hub_frontend',
          status_message = '더 최신 변경으로 대체됨', updated_at = v_saved_at
      where queue.sellpia_sku_code = p_sku and queue.field_key = 'seller_option_name'
        and queue.source_channel = p_source
        and queue.seller_product_code = v_current.product_code
        and queue.seller_option_code = v_current.option_code
        and queue.status in ('pending', 'validated', 'failed')
        and queue.change_batch_id <> v_batch_id;
    end if;
    insert into public.operations_hub_change_queue (
      change_batch_id, sellpia_sku_code, field_key, before_value, after_value, target_channels,
      status, requested_by, requested_at, updated_at, source_channel, seller_product_code, seller_option_code
    ) values (
      v_batch_id, p_sku, 'seller_option_name', to_jsonb(v_current.option_name), to_jsonb(p_option_name), array[p_source],
      v_status, 'operations_hub_frontend', v_saved_at, v_saved_at, p_source, v_current.product_code, v_current.option_code
    ) on conflict do nothing;
    get diagnostics v_inserted = row_count;
    v_saved := v_saved + 1;
    if p_queue then v_queued := v_queued + v_inserted; end if;
  end if;

  return query select v_saved, v_queued, v_saved_at, v_batch_id;
end;
$$;

revoke all on function public.save_operations_hub_seller_listing(text, text, text, text, text, text, boolean, uuid) from public;
grant execute on function public.save_operations_hub_seller_listing(text, text, text, text, text, text, boolean, uuid) to anon, authenticated;

create or replace function public.validate_operations_hub_changes(p_change_ids bigint[])
returns table(validated_count integer, failed_count integer)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_row public.operations_hub_change_queue%rowtype;
  v_errors jsonb;
  v_validated integer := 0;
  v_failed integer := 0;
  v_after text;
begin
  if cardinality(coalesce(p_change_ids, '{}'::bigint[])) = 0 then
    raise exception '검증할 변경사항을 선택해주세요.';
  end if;
  for v_row in
    select * from public.operations_hub_change_queue queue
    where queue.change_id = any(p_change_ids)
      and queue.status in ('pending', 'failed')
    order by queue.change_id
    for update skip locked
  loop
    v_errors := '[]'::jsonb;
    v_after := v_row.after_value #>> '{}';
    if v_row.before_value is not distinct from v_row.after_value then
      v_errors := v_errors || jsonb_build_array('변경 전후 값이 같습니다.');
    end if;
    if v_row.field_key in ('sellpia_current_stock', 'sellpia_sale_price')
       and (coalesce(v_after, '') !~ '^\d+(\.\d+)?$' or v_after::numeric < 0) then
      v_errors := v_errors || jsonb_build_array('재고와 판매가는 0 이상의 숫자여야 합니다.');
    end if;
    if v_row.field_key in ('sellpia_current_stock', 'sellpia_sale_price', 'seller_product_name', 'seller_option_name')
       and cardinality(v_row.target_channels) = 0 then
      v_errors := v_errors || jsonb_build_array('반영할 판매처가 없습니다.');
    end if;
    if v_row.field_key in ('seller_product_name', 'seller_option_name')
       and (v_row.source_channel is null or v_row.seller_product_code is null) then
      v_errors := v_errors || jsonb_build_array('판매처 상품 식별자가 없습니다.');
    end if;

    if jsonb_array_length(v_errors) = 0 then
      update public.operations_hub_change_queue
      set status = 'validated', validation_errors = '[]'::jsonb, validated_at = now(),
          error_message = null, status_message = '검증 완료', updated_at = now()
      where change_id = v_row.change_id;
      v_validated := v_validated + 1;
    else
      update public.operations_hub_change_queue
      set status = 'failed', validation_errors = v_errors, validated_at = now(),
          error_message = v_errors ->> 0, status_message = '검증 실패', updated_at = now()
      where change_id = v_row.change_id;
      v_failed := v_failed + 1;
    end if;
  end loop;
  return query select v_validated, v_failed;
end;
$$;

create or replace function public.cancel_operations_hub_changes(p_change_ids bigint[], p_reason text default '사용자 취소')
returns table(cancelled_count integer)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare v_count integer := 0;
begin
  if cardinality(coalesce(p_change_ids, '{}'::bigint[])) = 0 then
    raise exception '취소할 변경사항을 선택해주세요.';
  end if;
  update public.operations_hub_change_queue
  set status = 'cancelled', cancelled_at = now(), cancelled_by = 'operations_hub_frontend',
      status_message = coalesce(nullif(btrim(p_reason), ''), '사용자 취소'), updated_at = now()
  where change_id = any(p_change_ids) and status in ('pending', 'validated', 'failed');
  get diagnostics v_count = row_count;
  return query select v_count;
end;
$$;

create or replace function public.retry_operations_hub_changes(p_change_ids bigint[])
returns table(retried_count integer, skipped_count integer)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare v_retried integer := 0; v_total integer := 0;
begin
  if cardinality(coalesce(p_change_ids, '{}'::bigint[])) = 0 then
    raise exception '재시도할 변경사항을 선택해주세요.';
  end if;
  select count(*) into v_total from public.operations_hub_change_queue where change_id = any(p_change_ids);
  update public.operations_hub_change_queue
  set status = 'pending', retry_count = retry_count + 1, validation_errors = '[]'::jsonb,
      error_message = null, status_message = '재시도 대기', next_retry_at = null, updated_at = now()
  where change_id = any(p_change_ids) and status = 'failed' and retry_count < max_retry_count;
  get diagnostics v_retried = row_count;
  return query select v_retried, greatest(0, v_total - v_retried);
end;
$$;

create or replace function public.claim_operations_hub_changes(p_limit integer default 100, p_worker text default 'export_adapter')
returns setof public.operations_hub_change_queue
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  return query
  with candidates as (
    select change_id from public.operations_hub_change_queue
    where status = 'validated' and (next_retry_at is null or next_retry_at <= now())
    order by requested_at, change_id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 100), 500))
  )
  update public.operations_hub_change_queue queue
  set status = 'processing', last_attempt_at = now(), status_message = '처리자 ' || coalesce(nullif(btrim(p_worker), ''), 'export_adapter'), updated_at = now()
  from candidates
  where queue.change_id = candidates.change_id
  returning queue.*;
end;
$$;

create or replace function public.complete_operations_hub_change(
  p_change_id bigint,
  p_success boolean,
  p_error_message text default null,
  p_worker text default 'export_adapter'
)
returns setof public.operations_hub_change_queue
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  return query
  update public.operations_hub_change_queue queue
  set status = case when p_success then 'applied' else 'failed' end,
      processed_at = case when p_success then now() else queue.processed_at end,
      retry_count = case when p_success then queue.retry_count else least(queue.max_retry_count, queue.retry_count + 1) end,
      next_retry_at = case when p_success then null else now() + make_interval(mins => least(60, (2 ^ least(queue.retry_count, 5))::integer)) end,
      error_message = case when p_success then null else coalesce(nullif(btrim(p_error_message), ''), '판매처 반영 실패') end,
      status_message = case when p_success then '반영 완료' else '반영 실패 · ' || coalesce(nullif(btrim(p_worker), ''), 'export_adapter') end,
      updated_at = now()
  where queue.change_id = p_change_id and queue.status = 'processing'
  returning queue.*;
end;
$$;

revoke all on function public.validate_operations_hub_changes(bigint[]) from public;
revoke all on function public.cancel_operations_hub_changes(bigint[], text) from public;
revoke all on function public.retry_operations_hub_changes(bigint[]) from public;
revoke all on function public.claim_operations_hub_changes(integer, text) from public;
revoke all on function public.complete_operations_hub_change(bigint, boolean, text, text) from public;

grant execute on function public.validate_operations_hub_changes(bigint[]) to anon, authenticated;
grant execute on function public.cancel_operations_hub_changes(bigint[], text) to anon, authenticated;
grant execute on function public.retry_operations_hub_changes(bigint[]) to anon, authenticated;
grant execute on function public.claim_operations_hub_changes(integer, text) to service_role;
grant execute on function public.complete_operations_hub_change(bigint, boolean, text, text) to service_role;

notify pgrst, 'reload schema';
