alter table public.sellpia_stock_snapshot_rows
  add column if not exists purchase_price numeric,
  add column if not exists order_unit numeric,
  add column if not exists minimum_order_unit numeric;

update public.sellpia_stock_snapshot_rows
set purchase_price = nullif(regexp_replace(coalesce(raw_payload ->> 'purchase_price', ''), '[^0-9.-]', '', 'g'), '')::numeric
where purchase_price is null
  and nullif(regexp_replace(coalesce(raw_payload ->> 'purchase_price', ''), '[^0-9.-]', '', 'g'), '') is not null;

create or replace view public.sellpia_stock_latest
with (security_invoker = true)
as
select
  r.snapshot_id,
  r.sellpia_sku_code,
  r.sellpia_product_code,
  r.sellpia_product_name,
  r.sellpia_option_name,
  r.own_sku,
  r.stock,
  r.available_stock,
  r.integrated_available_stock,
  r.safety_stock,
  r.source_row_no,
  r.raw_payload,
  r.created_at,
  s.source_file_name,
  s.source_row_count,
  s.valid_row_count,
  s.invalid_row_count,
  s.created_at as snapshot_created_at,
  s.completed_at as snapshot_completed_at,
  r.supplier_code,
  r.supplier_name,
  r.supplier_group,
  r.supplier_address,
  r.supplier_market_name,
  r.supplier_phone,
  r.purchase_product_name,
  r.purchase_option_name,
  r.purchase_price,
  r.order_unit,
  r.minimum_order_unit
from public.sellpia_stock_snapshot_rows r
join public.sellpia_stock_snapshots s on s.snapshot_id = r.snapshot_id
where s.snapshot_id = (
  select snapshot_id
  from public.sellpia_stock_snapshots
  where upload_status = 'ready'
  order by created_at desc
  limit 1
);

create table if not exists public.operations_hub_inbound_cost_formula_tags (
  tag_id bigint generated by default as identity primary key,
  tag_name text not null unique,
  tag_color text not null default '#7c3aed',
  multiply_value numeric not null default 1 check (multiply_value > 0),
  divide_value numeric not null default 1 check (divide_value > 0),
  add_value numeric not null default 0,
  rounding_unit numeric not null default 1 check (rounding_unit > 0),
  rounding_mode text not null default 'nearest' check (rounding_mode in ('nearest', 'up', 'down')),
  is_active boolean not null default true,
  description text,
  created_by text not null default 'operations-hub',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.operations_hub_inbound_cost_settings (
  sellpia_sku_code text primary key,
  manual_cost numeric check (manual_cost is null or manual_cost >= 0),
  formula_tag_id bigint references public.operations_hub_inbound_cost_formula_tags(tag_id) on delete restrict,
  updated_by text not null default 'operations-hub',
  updated_at timestamptz not null default now(),
  constraint operations_hub_inbound_cost_settings_one_mode check (
    not (manual_cost is not null and formula_tag_id is not null)
  )
);

create index if not exists operations_hub_inbound_cost_settings_formula_idx
  on public.operations_hub_inbound_cost_settings(formula_tag_id)
  where formula_tag_id is not null;

alter table public.operations_hub_inbound_cost_formula_tags enable row level security;
alter table public.operations_hub_inbound_cost_settings enable row level security;

drop policy if exists "operations hub inbound cost formula tags all" on public.operations_hub_inbound_cost_formula_tags;
create policy "operations hub inbound cost formula tags all"
  on public.operations_hub_inbound_cost_formula_tags
  for all to anon, authenticated
  using (true) with check (true);

drop policy if exists "operations hub inbound cost settings all" on public.operations_hub_inbound_cost_settings;
create policy "operations hub inbound cost settings all"
  on public.operations_hub_inbound_cost_settings
  for all to anon, authenticated
  using (true) with check (true);

grant select, insert, update, delete on public.operations_hub_inbound_cost_formula_tags to anon, authenticated;
grant select, insert, update, delete on public.operations_hub_inbound_cost_settings to anon, authenticated;
grant usage, select on sequence public.operations_hub_inbound_cost_formula_tags_tag_id_seq to anon, authenticated;

create or replace function public.calculate_operations_hub_inbound_cost(
  p_purchase_price numeric,
  p_multiply_value numeric,
  p_divide_value numeric,
  p_add_value numeric,
  p_rounding_unit numeric,
  p_rounding_mode text
)
returns numeric
language sql
immutable
set search_path = public, pg_temp
as $$
  with calculated as (
    select ((p_purchase_price * coalesce(p_multiply_value, 1)) / nullif(coalesce(p_divide_value, 1), 0)) + coalesce(p_add_value, 0) as value,
           greatest(coalesce(p_rounding_unit, 1), 1) as unit
  )
  select case coalesce(p_rounding_mode, 'nearest')
    when 'up' then ceil(value / unit) * unit
    when 'down' then floor(value / unit) * unit
    else round(value / unit) * unit
  end
  from calculated
  where p_purchase_price is not null;
$$;

grant execute on function public.calculate_operations_hub_inbound_cost(numeric,numeric,numeric,numeric,numeric,text) to anon, authenticated;

create or replace function public.save_operations_hub_inbound_cost(
  p_sellpia_sku_code text,
  p_manual_cost numeric default null,
  p_formula_tag_id bigint default null,
  p_actor text default 'operations-hub'
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_sku text := nullif(btrim(p_sellpia_sku_code), '');
begin
  if v_sku is null then
    raise exception '셀피아 SKU가 필요합니다.';
  end if;
  if p_manual_cost is not null and p_manual_cost < 0 then
    raise exception '실입고가는 0 이상이어야 합니다.';
  end if;
  if p_manual_cost is not null and p_formula_tag_id is not null then
    raise exception '직접 입력과 수식태그는 동시에 선택할 수 없습니다.';
  end if;
  if p_formula_tag_id is not null and not exists (
    select 1 from public.operations_hub_inbound_cost_formula_tags
    where tag_id = p_formula_tag_id and is_active
  ) then
    raise exception '사용할 수 없는 실입고가 수식태그입니다.';
  end if;

  if p_manual_cost is null and p_formula_tag_id is null then
    delete from public.operations_hub_inbound_cost_settings where sellpia_sku_code = v_sku;
    return jsonb_build_object('sellpia_sku_code', v_sku, 'mode', 'empty');
  end if;

  insert into public.operations_hub_inbound_cost_settings (
    sellpia_sku_code, manual_cost, formula_tag_id, updated_by, updated_at
  ) values (
    v_sku, p_manual_cost, p_formula_tag_id, coalesce(nullif(btrim(p_actor), ''), 'operations-hub'), clock_timestamp()
  )
  on conflict (sellpia_sku_code) do update set
    manual_cost = excluded.manual_cost,
    formula_tag_id = excluded.formula_tag_id,
    updated_by = excluded.updated_by,
    updated_at = excluded.updated_at;

  return jsonb_build_object(
    'sellpia_sku_code', v_sku,
    'mode', case when p_manual_cost is not null then 'manual' else 'formula' end,
    'manual_cost', p_manual_cost,
    'formula_tag_id', p_formula_tag_id
  );
end;
$$;

grant execute on function public.save_operations_hub_inbound_cost(text,numeric,bigint,text) to anon, authenticated;

create or replace view public.operations_hub_inbound_cost_live
with (security_invoker = true)
as
select
  stock.sellpia_sku_code,
  stock.purchase_price as sellpia_purchase_price,
  stock.order_unit as sellpia_order_unit,
  stock.minimum_order_unit as sellpia_minimum_order_unit,
  settings.manual_cost as actual_inbound_manual_cost,
  settings.formula_tag_id as inbound_cost_formula_tag_id,
  formula.tag_name as inbound_cost_formula_tag_name,
  formula.tag_color as inbound_cost_formula_tag_color,
  case
    when settings.manual_cost is not null then settings.manual_cost
    when settings.formula_tag_id is not null then public.calculate_operations_hub_inbound_cost(
      stock.purchase_price,
      formula.multiply_value,
      formula.divide_value,
      formula.add_value,
      formula.rounding_unit,
      formula.rounding_mode
    )
    else null
  end as actual_inbound_cost,
  case
    when settings.manual_cost is not null then 'manual'
    when settings.formula_tag_id is not null then 'formula'
    else null
  end as actual_inbound_cost_mode,
  settings.updated_at as actual_inbound_cost_updated_at
from public.sellpia_stock_latest stock
left join public.operations_hub_inbound_cost_settings settings
  on settings.sellpia_sku_code = stock.sellpia_sku_code
left join public.operations_hub_inbound_cost_formula_tags formula
  on formula.tag_id = settings.formula_tag_id and formula.is_active;

grant select on public.operations_hub_inbound_cost_live to anon, authenticated;

create or replace function public.finalize_operations_hub_sellpia_patch(
  p_patch_snapshot_id uuid,
  p_selected_fields jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_patch public.sellpia_stock_snapshots%rowtype;
  v_base_snapshot_id uuid;
  v_inventory boolean := coalesce((p_selected_fields ->> 'inventory')::boolean, false);
  v_price boolean := coalesce((p_selected_fields ->> 'price')::boolean, false);
  v_basic boolean := coalesce((p_selected_fields ->> 'basic')::boolean, false);
  v_status boolean := coalesce((p_selected_fields ->> 'status')::boolean, false);
  v_uploaded_count integer;
  v_preserved_count integer;
  v_final_count integer;
begin
  if p_patch_snapshot_id is null then raise exception '부분 갱신 스냅샷 ID가 필요합니다.'; end if;
  if not (v_inventory or v_price or v_basic or v_status) then raise exception '부분 갱신할 항목을 하나 이상 선택해주세요.'; end if;
  perform pg_advisory_xact_lock(hashtextextended('operations_hub_sellpia_patch', 0));

  select * into v_patch from public.sellpia_stock_snapshots
  where snapshot_id = p_patch_snapshot_id for update;
  if not found or v_patch.upload_status <> 'uploading' then raise exception '처리 가능한 셀피아 부분 갱신 스냅샷이 아닙니다.'; end if;

  select snapshot_id into v_base_snapshot_id from public.sellpia_stock_snapshots
  where upload_status = 'ready' and snapshot_id <> p_patch_snapshot_id
  order by created_at desc limit 1;
  if v_base_snapshot_id is null then raise exception '부분 갱신의 기준이 될 이전 셀피아 원본이 없습니다. 최초 1회는 전체 교체로 업로드해주세요.'; end if;

  select count(*)::integer into v_uploaded_count from public.sellpia_stock_snapshot_rows where snapshot_id = p_patch_snapshot_id;
  if v_uploaded_count = 0 then raise exception '부분 갱신할 셀피아 SKU가 없습니다.'; end if;

  update public.sellpia_stock_snapshot_rows patch_row set
    sellpia_product_code = case when v_basic then patch_row.sellpia_product_code else base_row.sellpia_product_code end,
    sellpia_product_name = case when v_basic then patch_row.sellpia_product_name else base_row.sellpia_product_name end,
    sellpia_option_name = case when v_basic then patch_row.sellpia_option_name else base_row.sellpia_option_name end,
    own_sku = case when v_basic then patch_row.own_sku else base_row.own_sku end,
    stock = case when v_inventory then patch_row.stock else base_row.stock end,
    available_stock = case when v_inventory then patch_row.available_stock else base_row.available_stock end,
    integrated_available_stock = case when v_inventory then patch_row.integrated_available_stock else base_row.integrated_available_stock end,
    safety_stock = case when v_inventory then patch_row.safety_stock else base_row.safety_stock end,
    source_row_no = coalesce(patch_row.source_row_no, base_row.source_row_no),
    supplier_code = case when v_basic then patch_row.supplier_code else base_row.supplier_code end,
    supplier_name = case when v_basic then patch_row.supplier_name else base_row.supplier_name end,
    supplier_group = case when v_basic then patch_row.supplier_group else base_row.supplier_group end,
    supplier_address = case when v_basic then patch_row.supplier_address else base_row.supplier_address end,
    supplier_market_name = case when v_basic then patch_row.supplier_market_name else base_row.supplier_market_name end,
    supplier_phone = case when v_basic then patch_row.supplier_phone else base_row.supplier_phone end,
    purchase_product_name = case when v_basic then patch_row.purchase_product_name else base_row.purchase_product_name end,
    purchase_option_name = case when v_basic then patch_row.purchase_option_name else base_row.purchase_option_name end,
    purchase_price = case when v_price then patch_row.purchase_price else base_row.purchase_price end,
    order_unit = case when v_basic then patch_row.order_unit else base_row.order_unit end,
    minimum_order_unit = case when v_basic then patch_row.minimum_order_unit else base_row.minimum_order_unit end,
    raw_payload = coalesce(base_row.raw_payload, '{}'::jsonb)
      || case when v_price then jsonb_build_object(
        'base_price', patch_row.raw_payload -> 'base_price',
        'sell_price', patch_row.raw_payload -> 'sell_price',
        'purchase_price', patch_row.raw_payload -> 'purchase_price',
        'commission', patch_row.raw_payload -> 'commission',
        'purchase_vat', patch_row.raw_payload -> 'purchase_vat'
      ) else '{}'::jsonb end
      || case when v_basic then jsonb_build_object(
        'order_unit', patch_row.raw_payload -> 'order_unit',
        'minimum_order_unit', patch_row.raw_payload -> 'minimum_order_unit'
      ) else '{}'::jsonb end
      || case when v_status then jsonb_build_object('sale_status', patch_row.raw_payload -> 'sale_status') else '{}'::jsonb end
      || jsonb_build_object('source_file_name', patch_row.raw_payload -> 'source_file_name', 'patch_snapshot_id', p_patch_snapshot_id)
  from public.sellpia_stock_snapshot_rows base_row
  where patch_row.snapshot_id = p_patch_snapshot_id
    and base_row.snapshot_id = v_base_snapshot_id
    and base_row.sellpia_sku_code = patch_row.sellpia_sku_code;

  insert into public.sellpia_stock_snapshot_rows (
    snapshot_id, sellpia_sku_code, sellpia_product_code, sellpia_product_name, sellpia_option_name,
    own_sku, stock, available_stock, integrated_available_stock, safety_stock, source_row_no, raw_payload,
    supplier_code, supplier_name, supplier_group, supplier_address, supplier_market_name, supplier_phone,
    purchase_product_name, purchase_option_name, purchase_price, order_unit, minimum_order_unit
  )
  select
    p_patch_snapshot_id, base_row.sellpia_sku_code, base_row.sellpia_product_code, base_row.sellpia_product_name,
    base_row.sellpia_option_name, base_row.own_sku, base_row.stock, base_row.available_stock,
    base_row.integrated_available_stock, base_row.safety_stock, base_row.source_row_no,
    base_row.raw_payload || jsonb_build_object('preserved_from_snapshot_id', v_base_snapshot_id),
    base_row.supplier_code, base_row.supplier_name, base_row.supplier_group, base_row.supplier_address,
    base_row.supplier_market_name, base_row.supplier_phone, base_row.purchase_product_name,
    base_row.purchase_option_name, base_row.purchase_price, base_row.order_unit, base_row.minimum_order_unit
  from public.sellpia_stock_snapshot_rows base_row
  where base_row.snapshot_id = v_base_snapshot_id
    and not exists (
      select 1 from public.sellpia_stock_snapshot_rows patch_row
      where patch_row.snapshot_id = p_patch_snapshot_id
        and patch_row.sellpia_sku_code = base_row.sellpia_sku_code
    );

  get diagnostics v_preserved_count = row_count;
  select count(*)::integer into v_final_count from public.sellpia_stock_snapshot_rows where snapshot_id = p_patch_snapshot_id;

  update public.sellpia_stock_snapshots set
    valid_row_count = v_final_count,
    invalid_row_count = 0,
    upload_status = 'ready',
    upload_note = format('부분 갱신 %s개 SKU · 기존 %s개 SKU 유지', v_uploaded_count, v_preserved_count),
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'upload_mode', 'patch', 'base_snapshot_id', v_base_snapshot_id,
      'uploaded_row_count', v_uploaded_count, 'preserved_row_count', v_preserved_count,
      'final_row_count', v_final_count, 'selected_fields', p_selected_fields
    ),
    completed_at = clock_timestamp()
  where snapshot_id = p_patch_snapshot_id;

  return jsonb_build_object(
    'snapshot_id', p_patch_snapshot_id, 'base_snapshot_id', v_base_snapshot_id,
    'upload_mode', 'patch', 'uploaded_row_count', v_uploaded_count,
    'preserved_row_count', v_preserved_count, 'row_count', v_final_count
  );
end;
$$;

notify pgrst, 'reload schema';
