create table if not exists public.operations_hub_manual_links (
  source_channel text not null check (source_channel in ('smartstore', 'makeshop', 'ably')),
  sellpia_sku_code text not null,
  product_code text not null,
  option_code text not null default '',
  product_name text,
  option_name text,
  updated_by text not null default 'operations_hub_frontend',
  updated_at timestamptz not null default now(),
  primary key (source_channel, sellpia_sku_code)
);

create index if not exists operations_hub_manual_links_listing_idx
  on public.operations_hub_manual_links (source_channel, product_code, option_code);

create table if not exists public.operations_hub_link_history (
  link_event_id bigint generated by default as identity primary key,
  sellpia_sku_code text not null,
  source_channel text not null check (source_channel in ('smartstore', 'makeshop', 'ably')),
  before_link jsonb,
  after_link jsonb not null,
  changed_by text not null default 'operations_hub_frontend',
  changed_at timestamptz not null default now()
);

create index if not exists operations_hub_link_history_sku_idx
  on public.operations_hub_link_history (sellpia_sku_code, changed_at desc);

create table if not exists public.operations_hub_seller_listing_overrides (
  source_channel text not null check (source_channel in ('smartstore', 'makeshop', 'ably')),
  product_code text not null,
  option_code text not null default '',
  product_name text,
  option_name text,
  updated_by text not null default 'operations_hub_frontend',
  updated_at timestamptz not null default now(),
  primary key (source_channel, product_code, option_code)
);

alter table public.operations_hub_change_queue
  add column if not exists source_channel text,
  add column if not exists seller_product_code text,
  add column if not exists seller_option_code text;

alter table public.operations_hub_change_queue
  drop constraint if exists operations_hub_change_queue_field_key_check;

alter table public.operations_hub_change_queue
  add constraint operations_hub_change_queue_field_key_check check (field_key in (
    'sellpia_own_code', 'sellpia_product_name', 'sellpia_option_name',
    'sellpia_current_stock', 'sellpia_sale_price', 'sellpia_image',
    'seller_product_name', 'seller_option_name'
  ));

alter table public.operations_hub_change_queue
  drop constraint if exists operations_hub_change_queue_source_channel_check;

alter table public.operations_hub_change_queue
  add constraint operations_hub_change_queue_source_channel_check check (
    source_channel is null or source_channel in ('smartstore', 'makeshop', 'ably')
  );

alter table public.operations_hub_manual_links enable row level security;
alter table public.operations_hub_link_history enable row level security;
alter table public.operations_hub_seller_listing_overrides enable row level security;

drop policy if exists "operations hub manual links readable" on public.operations_hub_manual_links;
create policy "operations hub manual links readable"
  on public.operations_hub_manual_links for select
  to anon, authenticated
  using (true);

drop policy if exists "operations hub manual links insertable" on public.operations_hub_manual_links;
create policy "operations hub manual links insertable"
  on public.operations_hub_manual_links for insert
  to anon, authenticated
  with check (updated_by = 'operations_hub_frontend');

drop policy if exists "operations hub manual links updatable" on public.operations_hub_manual_links;
create policy "operations hub manual links updatable"
  on public.operations_hub_manual_links for update
  to anon, authenticated
  using (updated_by = 'operations_hub_frontend')
  with check (updated_by = 'operations_hub_frontend');

drop policy if exists "operations hub link history readable" on public.operations_hub_link_history;
create policy "operations hub link history readable"
  on public.operations_hub_link_history for select
  to anon, authenticated
  using (true);

drop policy if exists "operations hub link history insertable" on public.operations_hub_link_history;
create policy "operations hub link history insertable"
  on public.operations_hub_link_history for insert
  to anon, authenticated
  with check (changed_by = 'operations_hub_frontend');

drop policy if exists "operations hub seller overrides readable" on public.operations_hub_seller_listing_overrides;
create policy "operations hub seller overrides readable"
  on public.operations_hub_seller_listing_overrides for select
  to anon, authenticated
  using (true);

drop policy if exists "operations hub seller overrides insertable" on public.operations_hub_seller_listing_overrides;
create policy "operations hub seller overrides insertable"
  on public.operations_hub_seller_listing_overrides for insert
  to anon, authenticated
  with check (updated_by = 'operations_hub_frontend');

drop policy if exists "operations hub seller overrides updatable" on public.operations_hub_seller_listing_overrides;
create policy "operations hub seller overrides updatable"
  on public.operations_hub_seller_listing_overrides for update
  to anon, authenticated
  using (updated_by = 'operations_hub_frontend')
  with check (updated_by = 'operations_hub_frontend');

revoke all on table public.operations_hub_manual_links from public;
revoke all on table public.operations_hub_link_history from public;
revoke all on table public.operations_hub_seller_listing_overrides from public;
grant select, insert, update on table public.operations_hub_manual_links to anon, authenticated;
grant select, insert on table public.operations_hub_link_history to anon, authenticated;
grant select, insert, update on table public.operations_hub_seller_listing_overrides to anon, authenticated;
grant usage, select on sequence public.operations_hub_link_history_link_event_id_seq to anon, authenticated;
grant select, insert on table public.operations_hub_change_queue to anon, authenticated;

create or replace function public.search_operations_hub_seller_items(
  p_source text,
  p_query text default '',
  p_limit integer default 20
)
returns table (
  source_channel text,
  product_code text,
  option_code text,
  product_name text,
  option_name text,
  stock integer,
  price numeric,
  sale_status text,
  snapshot_completed_at timestamptz,
  linked_skus text[]
)
language sql
security invoker
set search_path = public, operations_private, pg_temp
as $$
  with effective_links as (
    select 'smartstore'::text as source_channel,
           matrix.sellpia_sku_code,
           matrix.smartstore_product_code as product_code,
           coalesce(matrix.smartstore_option_code, '') as option_code
    from operations_private.operations_hub_matrix_core matrix
    where matrix.smartstore_product_code is not null
      and not exists (
        select 1 from public.operations_hub_manual_links manual
        where manual.source_channel = 'smartstore'
          and manual.sellpia_sku_code = matrix.sellpia_sku_code
      )
    union all
    select 'makeshop', matrix.sellpia_sku_code, matrix.makeshop_product_code, coalesce(matrix.makeshop_option_code, '')
    from operations_private.operations_hub_matrix_core matrix
    where matrix.makeshop_product_code is not null
      and not exists (
        select 1 from public.operations_hub_manual_links manual
        where manual.source_channel = 'makeshop'
          and manual.sellpia_sku_code = matrix.sellpia_sku_code
      )
    union all
    select 'ably', matrix.sellpia_sku_code, matrix.ably_product_code, coalesce(matrix.ably_option_code, '')
    from operations_private.operations_hub_matrix_core matrix
    where matrix.ably_product_code is not null
      and not exists (
        select 1 from public.operations_hub_manual_links manual
        where manual.source_channel = 'ably'
          and manual.sellpia_sku_code = matrix.sellpia_sku_code
      )
    union all
    select manual.source_channel, manual.sellpia_sku_code, manual.product_code, manual.option_code
    from public.operations_hub_manual_links manual
  ), linked as (
    select link.source_channel, link.product_code, link.option_code,
           array_agg(distinct link.sellpia_sku_code order by link.sellpia_sku_code) as linked_skus
    from effective_links link
    group by link.source_channel, link.product_code, link.option_code
  )
  select item.source_channel,
         item.product_code,
         item.option_code,
         item.product_name,
         item.option_name,
         item.stock,
         item.price,
         item.sale_status,
         item.snapshot_completed_at,
         coalesce(linked.linked_skus, '{}'::text[]) as linked_skus
  from public.seller_inventory_latest item
  left join linked
    on linked.source_channel = item.source_channel
   and linked.product_code = item.product_code
   and linked.option_code = item.option_code
  where item.source_channel = p_source
    and (
      nullif(btrim(p_query), '') is null
      or item.product_code ilike '%' || btrim(p_query) || '%'
      or item.option_code ilike '%' || btrim(p_query) || '%'
      or coalesce(item.product_name, '') ilike '%' || btrim(p_query) || '%'
      or coalesce(item.option_name, '') ilike '%' || btrim(p_query) || '%'
      or coalesce(item.seller_code, '') ilike '%' || btrim(p_query) || '%'
    )
  order by
    case when item.product_code = btrim(p_query) then 0
         when item.option_code = btrim(p_query) then 1
         else 2 end,
    item.product_code,
    item.option_code
  limit greatest(1, least(coalesce(p_limit, 20), 50));
$$;

revoke all on function public.search_operations_hub_seller_items(text, text, integer) from public;
grant execute on function public.search_operations_hub_seller_items(text, text, integer) to anon, authenticated;

create or replace function public.link_operations_hub_seller_item(
  p_sku text,
  p_source text,
  p_product_code text,
  p_option_code text default ''
)
returns table (
  source_channel text,
  sellpia_sku_code text,
  product_code text,
  option_code text,
  product_name text,
  option_name text,
  stock integer,
  price numeric,
  linked_at timestamptz
)
language plpgsql
security invoker
set search_path = public, operations_private, pg_temp
as $$
declare
  v_item public.seller_inventory_latest%rowtype;
  v_before jsonb;
  v_linked_at timestamptz := now();
begin
  if p_source not in ('smartstore', 'makeshop', 'ably') then
    raise exception '지원하지 않는 판매처입니다: %', p_source;
  end if;
  if nullif(btrim(p_sku), '') is null then
    raise exception '셀피아 SKU가 필요합니다.';
  end if;
  if not exists (
    select 1 from operations_private.operations_hub_matrix_core matrix
    where matrix.sellpia_sku_code = btrim(p_sku)
  ) then
    raise exception '매트릭스에 없는 셀피아 SKU입니다: %', p_sku;
  end if;

  select item.* into v_item
  from public.seller_inventory_latest item
  where item.source_channel = p_source
    and item.product_code = btrim(p_product_code)
    and item.option_code = coalesce(btrim(p_option_code), '')
  limit 1;

  if not found then
    raise exception '최신 판매처 원본에서 선택한 상품을 찾을 수 없습니다.';
  end if;

  select to_jsonb(existing.*) into v_before
  from public.operations_hub_manual_links existing
  where existing.source_channel = p_source
    and existing.sellpia_sku_code = btrim(p_sku);

  insert into public.operations_hub_manual_links (
    source_channel, sellpia_sku_code, product_code, option_code,
    product_name, option_name, updated_by, updated_at
  ) values (
    p_source, btrim(p_sku), v_item.product_code, v_item.option_code,
    v_item.product_name, v_item.option_name, 'operations_hub_frontend', v_linked_at
  )
  on conflict on constraint operations_hub_manual_links_pkey do update set
    product_code = excluded.product_code,
    option_code = excluded.option_code,
    product_name = excluded.product_name,
    option_name = excluded.option_name,
    updated_by = 'operations_hub_frontend',
    updated_at = excluded.updated_at;

  insert into public.operations_hub_link_history (
    sellpia_sku_code, source_channel, before_link, after_link, changed_by, changed_at
  ) values (
    btrim(p_sku), p_source, v_before,
    jsonb_build_object(
      'product_code', v_item.product_code,
      'option_code', v_item.option_code,
      'product_name', v_item.product_name,
      'option_name', v_item.option_name
    ),
    'operations_hub_frontend', v_linked_at
  );

  return query select
    p_source, btrim(p_sku), v_item.product_code, v_item.option_code,
    v_item.product_name, v_item.option_name, v_item.stock, v_item.price, v_linked_at;
end;
$$;

revoke all on function public.link_operations_hub_seller_item(text, text, text, text) from public;
grant execute on function public.link_operations_hub_seller_item(text, text, text, text) to anon, authenticated;

create or replace function public.save_operations_hub_seller_listing(
  p_sku text,
  p_source text,
  p_product_code text,
  p_option_code text,
  p_product_name text,
  p_option_name text,
  p_queue boolean default false
)
returns table (saved_count integer, queued_count integer, saved_at timestamptz)
language plpgsql
security invoker
set search_path = public, operations_private, pg_temp
as $$
declare
  v_current public.seller_inventory_latest%rowtype;
  v_saved integer := 0;
  v_queued integer := 0;
  v_saved_at timestamptz := now();
begin
  if p_source not in ('smartstore', 'makeshop', 'ably') then
    raise exception '지원하지 않는 판매처입니다: %', p_source;
  end if;
  if not exists (
    select 1 from operations_private.operations_hub_matrix_core matrix
    where matrix.sellpia_sku_code = btrim(p_sku)
  ) then
    raise exception '매트릭스에 없는 셀피아 SKU입니다: %', p_sku;
  end if;

  select item.* into v_current
  from public.seller_inventory_latest item
  where item.source_channel = p_source
    and item.product_code = btrim(p_product_code)
    and item.option_code = coalesce(btrim(p_option_code), '')
  limit 1;

  if not found then
    raise exception '최신 판매처 원본에서 편집 대상을 찾을 수 없습니다.';
  end if;

  insert into public.operations_hub_seller_listing_overrides (
    source_channel, product_code, option_code, product_name, option_name, updated_by, updated_at
  ) values (
    p_source, v_current.product_code, v_current.option_code,
    nullif(btrim(p_product_name), ''), nullif(btrim(p_option_name), ''),
    'operations_hub_frontend', v_saved_at
  )
  on conflict (source_channel, product_code, option_code) do update set
    product_name = excluded.product_name,
    option_name = excluded.option_name,
    updated_by = 'operations_hub_frontend',
    updated_at = excluded.updated_at;

  if coalesce(btrim(p_product_name), '') is distinct from coalesce(btrim(v_current.product_name), '') then
    insert into public.operations_hub_change_queue (
      sellpia_sku_code, field_key, before_value, after_value, target_channels,
      status, requested_by, requested_at, source_channel, seller_product_code, seller_option_code
    ) values (
      btrim(p_sku), 'seller_product_name', to_jsonb(v_current.product_name), to_jsonb(p_product_name), array[p_source],
      case when p_queue then 'pending' else 'saved' end,
      'operations_hub_frontend', v_saved_at, p_source, v_current.product_code, v_current.option_code
    );
    v_saved := v_saved + 1;
    if p_queue then v_queued := v_queued + 1; end if;
  end if;

  if coalesce(btrim(p_option_name), '') is distinct from coalesce(btrim(v_current.option_name), '') then
    insert into public.operations_hub_change_queue (
      sellpia_sku_code, field_key, before_value, after_value, target_channels,
      status, requested_by, requested_at, source_channel, seller_product_code, seller_option_code
    ) values (
      btrim(p_sku), 'seller_option_name', to_jsonb(v_current.option_name), to_jsonb(p_option_name), array[p_source],
      case when p_queue then 'pending' else 'saved' end,
      'operations_hub_frontend', v_saved_at, p_source, v_current.product_code, v_current.option_code
    );
    v_saved := v_saved + 1;
    if p_queue then v_queued := v_queued + 1; end if;
  end if;

  return query select v_saved, v_queued, v_saved_at;
end;
$$;

revoke all on function public.save_operations_hub_seller_listing(text, text, text, text, text, text, boolean) from public;
grant execute on function public.save_operations_hub_seller_listing(text, text, text, text, text, text, boolean) to anon, authenticated;

drop view if exists public.operations_hub_dashboard_metrics;
drop view if exists public.operations_hub_matrix_live;

create view public.operations_hub_matrix_live
with (security_invoker = true)
as
with effective as (
  select
    matrix.sellpia_sku_code,
    matrix.own_code,
    matrix.image_url,
    matrix.display_name,
    coalesce(smart_link.product_code, matrix.smartstore_product_code) as smartstore_product_code,
    coalesce(smart_link.option_code, matrix.smartstore_option_code, '') as smartstore_option_code,
    case when smart_link.sellpia_sku_code is not null then 'MANUAL_LINKED' else matrix.smartstore_match_tier end as smartstore_match_tier,
    case when smart_link.sellpia_sku_code is not null then 100::numeric else matrix.smartstore_match_score end as smartstore_match_score,
    case when smart_link.sellpia_sku_code is not null then 1 else matrix.smartstore_listing_count end as smartstore_listing_count,
    coalesce(make_link.product_code, matrix.makeshop_product_code) as makeshop_product_code,
    coalesce(make_link.option_code, matrix.makeshop_option_code, '') as makeshop_option_code,
    case when make_link.sellpia_sku_code is not null then 'MANUAL_LINKED' else matrix.makeshop_match_tier end as makeshop_match_tier,
    case when make_link.sellpia_sku_code is not null then 100::numeric else matrix.makeshop_match_score end as makeshop_match_score,
    case when make_link.sellpia_sku_code is not null then 1 else matrix.makeshop_listing_count end as makeshop_listing_count,
    coalesce(ably_link.product_code, matrix.ably_product_code) as ably_product_code,
    coalesce(ably_link.option_code, matrix.ably_option_code, '') as ably_option_code,
    case when ably_link.sellpia_sku_code is not null then 'MANUAL_LINKED' else matrix.ably_match_tier end as ably_match_tier,
    case when ably_link.sellpia_sku_code is not null then 100::numeric else matrix.ably_match_score end as ably_match_score,
    case when ably_link.sellpia_sku_code is not null then 1 else matrix.ably_listing_count end as ably_listing_count,
    greatest(
      coalesce(matrix.updated_at, '-infinity'::timestamptz),
      coalesce(smart_link.updated_at, '-infinity'::timestamptz),
      coalesce(make_link.updated_at, '-infinity'::timestamptz),
      coalesce(ably_link.updated_at, '-infinity'::timestamptz)
    ) as updated_at
  from operations_private.operations_hub_matrix_core matrix
  left join public.operations_hub_manual_links smart_link
    on smart_link.source_channel = 'smartstore' and smart_link.sellpia_sku_code = matrix.sellpia_sku_code
  left join public.operations_hub_manual_links make_link
    on make_link.source_channel = 'makeshop' and make_link.sellpia_sku_code = matrix.sellpia_sku_code
  left join public.operations_hub_manual_links ably_link
    on ably_link.source_channel = 'ably' and ably_link.sellpia_sku_code = matrix.sellpia_sku_code
)
select
  effective.sellpia_sku_code,
  effective.own_code,
  effective.image_url,
  effective.display_name,
  coalesce(smart_override.product_name, smartstore.product_name) as smartstore_name,
  coalesce(smart_override.option_name, smartstore.option_name) as smartstore_option_name,
  effective.smartstore_product_code,
  nullif(effective.smartstore_option_code, '') as smartstore_option_code,
  effective.smartstore_match_tier,
  effective.smartstore_match_score,
  effective.smartstore_listing_count,
  smart_override.updated_at is not null as smartstore_name_is_draft,
  coalesce(make_override.product_name, makeshop.product_name) as makeshop_name,
  coalesce(make_override.option_name, makeshop.option_name) as makeshop_option_name,
  effective.makeshop_product_code,
  nullif(effective.makeshop_option_code, '') as makeshop_option_code,
  effective.makeshop_match_tier,
  effective.makeshop_match_score,
  effective.makeshop_listing_count,
  make_override.updated_at is not null as makeshop_name_is_draft,
  coalesce(ably_override.product_name, ably.product_name) as ably_name,
  coalesce(ably_override.option_name, ably.option_name) as ably_option_name,
  effective.ably_product_code,
  nullif(effective.ably_option_code, '') as ably_option_code,
  effective.ably_match_tier,
  effective.ably_match_score,
  effective.ably_listing_count,
  ably_override.updated_at is not null as ably_name_is_draft,
  greatest(
    effective.updated_at,
    coalesce(smart_override.updated_at, '-infinity'::timestamptz),
    coalesce(make_override.updated_at, '-infinity'::timestamptz),
    coalesce(ably_override.updated_at, '-infinity'::timestamptz)
  ) as updated_at,
  coalesce(nullif(btrim(override_row.product_name), ''), nullif(btrim(stock.sellpia_product_name), '')) as sellpia_product_name,
  coalesce(nullif(btrim(override_row.option_name), ''), nullif(btrim(stock.sellpia_option_name), '')) as sellpia_option_name,
  coalesce(nullif(btrim(override_row.own_code), ''), nullif(btrim(stock.own_sku), '')) as sellpia_own_code,
  coalesce(override_row.current_stock, stock.stock) as sellpia_current_stock,
  case when override_row.current_stock is not null then override_row.current_stock
       else coalesce(stock.available_stock, stock.integrated_available_stock, stock.stock) end as sellpia_available_stock,
  stock.safety_stock as sellpia_safety_stock,
  coalesce(override_row.sale_price, nullif(regexp_replace(coalesce(stock.raw_payload ->> 'sell_price', ''), '[^0-9.-]', '', 'g'), '')::numeric) as sellpia_sale_price,
  stock.snapshot_completed_at as sellpia_inventory_at,
  smartstore.stock as smartstore_stock,
  smartstore.price as smartstore_price,
  smartstore.sale_status as smartstore_sale_status,
  smartstore.snapshot_completed_at as smartstore_inventory_at,
  makeshop.stock as makeshop_stock,
  makeshop.price as makeshop_price,
  makeshop.sale_status as makeshop_sale_status,
  makeshop.snapshot_completed_at as makeshop_inventory_at,
  ably.stock as ably_stock,
  ably.price as ably_price,
  ably.sale_status as ably_sale_status,
  ably.snapshot_completed_at as ably_inventory_at,
  case
    when effective.smartstore_match_tier = 'FAST_REVIEW'
      or effective.makeshop_match_tier = 'FAST_REVIEW'
      or effective.ably_match_tier = 'FAST_REVIEW' then 'review'
    when effective.smartstore_match_tier is null
      and effective.makeshop_match_tier is null
      and effective.ably_match_tier is null then 'unmatched'
    else 'connected'
  end::text as overall_status,
  case when override_row.image_storage_path is null then null
       else 'https://bpgvqmtsjgegnrdzmpep.supabase.co/storage/v1/object/public/product-images/' || override_row.image_storage_path end as sellpia_override_image_url,
  override_row.updated_at as sellpia_override_updated_at
from effective
left join public.sellpia_stock_latest stock
  on stock.sellpia_sku_code = effective.sellpia_sku_code
left join public.operations_hub_sellpia_overrides override_row
  on override_row.sellpia_sku_code = effective.sellpia_sku_code
left join public.seller_inventory_latest smartstore
  on smartstore.source_channel = 'smartstore'
 and smartstore.product_code = effective.smartstore_product_code
 and smartstore.option_code = effective.smartstore_option_code
left join public.operations_hub_seller_listing_overrides smart_override
  on smart_override.source_channel = 'smartstore'
 and smart_override.product_code = effective.smartstore_product_code
 and smart_override.option_code = effective.smartstore_option_code
left join public.seller_inventory_latest makeshop
  on makeshop.source_channel = 'makeshop'
 and makeshop.product_code = effective.makeshop_product_code
 and makeshop.option_code = effective.makeshop_option_code
left join public.operations_hub_seller_listing_overrides make_override
  on make_override.source_channel = 'makeshop'
 and make_override.product_code = effective.makeshop_product_code
 and make_override.option_code = effective.makeshop_option_code
left join public.seller_inventory_latest ably
  on ably.source_channel = 'ably'
 and ably.product_code = effective.ably_product_code
 and ably.option_code = effective.ably_option_code
left join public.operations_hub_seller_listing_overrides ably_override
  on ably_override.source_channel = 'ably'
 and ably_override.product_code = effective.ably_product_code
 and ably_override.option_code = effective.ably_option_code;

revoke all on public.operations_hub_matrix_live from public;
grant select on public.operations_hub_matrix_live to anon, authenticated;

create view public.operations_hub_dashboard_metrics
with (security_invoker = true)
as
select
  count(*)::integer as total_sku,
  count(*) filter (where overall_status <> 'unmatched')::integer as connected_sku,
  count(*) filter (where overall_status = 'unmatched')::integer as unmatched_sku,
  count(*) filter (
    where sellpia_current_stock is not null
      and (
        (smartstore_stock is not null and smartstore_stock <> sellpia_current_stock)
        or (makeshop_stock is not null and makeshop_stock <> sellpia_current_stock)
        or (ably_stock is not null and ably_stock <> sellpia_current_stock)
      )
  )::integer as inventory_mismatch_sku,
  max(greatest(
    coalesce(sellpia_inventory_at, '-infinity'::timestamptz),
    coalesce(smartstore_inventory_at, '-infinity'::timestamptz),
    coalesce(makeshop_inventory_at, '-infinity'::timestamptz),
    coalesce(ably_inventory_at, '-infinity'::timestamptz),
    coalesce(sellpia_override_updated_at, '-infinity'::timestamptz)
  )) as latest_sync_at,
  null::integer as today_picked,
  null::integer as shortage_drawer_qty
from public.operations_hub_matrix_live;

revoke all on public.operations_hub_dashboard_metrics from public;
grant select on public.operations_hub_dashboard_metrics to anon, authenticated;

notify pgrst, 'reload schema';
