create table if not exists public.operations_hub_sellpia_overrides (
  sellpia_sku_code text primary key,
  own_code text,
  product_name text,
  option_name text,
  current_stock integer check (current_stock is null or current_stock >= 0),
  sale_price numeric check (sale_price is null or sale_price >= 0),
  image_storage_path text,
  updated_by text not null default 'operations_hub_frontend',
  updated_at timestamptz not null default now()
);

create table if not exists public.operations_hub_change_queue (
  change_id bigint generated by default as identity primary key,
  sellpia_sku_code text not null,
  field_key text not null check (field_key in (
    'sellpia_own_code', 'sellpia_product_name', 'sellpia_option_name',
    'sellpia_current_stock', 'sellpia_sale_price', 'sellpia_image'
  )),
  before_value jsonb,
  after_value jsonb,
  target_channels text[] not null default '{}'::text[],
  status text not null default 'pending' check (status in ('pending', 'processing', 'applied', 'failed', 'saved', 'cancelled')),
  requested_by text not null default 'operations_hub_frontend',
  requested_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text
);

create index if not exists operations_hub_change_queue_pending_idx
  on public.operations_hub_change_queue (status, requested_at, sellpia_sku_code)
  where status in ('pending', 'failed');

alter table public.operations_hub_sellpia_overrides enable row level security;
alter table public.operations_hub_change_queue enable row level security;

drop policy if exists "operations hub overrides readable" on public.operations_hub_sellpia_overrides;
create policy "operations hub overrides readable"
  on public.operations_hub_sellpia_overrides for select
  to anon, authenticated
  using (true);

drop policy if exists "operations hub overrides insertable" on public.operations_hub_sellpia_overrides;
create policy "operations hub overrides insertable"
  on public.operations_hub_sellpia_overrides for insert
  to anon, authenticated
  with check (updated_by = 'operations_hub_frontend');

drop policy if exists "operations hub overrides updatable" on public.operations_hub_sellpia_overrides;
create policy "operations hub overrides updatable"
  on public.operations_hub_sellpia_overrides for update
  to anon, authenticated
  using (updated_by = 'operations_hub_frontend')
  with check (updated_by = 'operations_hub_frontend');

drop policy if exists "operations hub queue readable" on public.operations_hub_change_queue;
create policy "operations hub queue readable"
  on public.operations_hub_change_queue for select
  to anon, authenticated
  using (true);

drop policy if exists "operations hub queue insertable" on public.operations_hub_change_queue;
create policy "operations hub queue insertable"
  on public.operations_hub_change_queue for insert
  to anon, authenticated
  with check (requested_by = 'operations_hub_frontend');

revoke all on table public.operations_hub_sellpia_overrides from public;
revoke all on table public.operations_hub_change_queue from public;
grant select, insert, update on table public.operations_hub_sellpia_overrides to anon, authenticated;
grant select, insert on table public.operations_hub_change_queue to anon, authenticated;
grant usage, select on sequence public.operations_hub_change_queue_change_id_seq to anon, authenticated;

create or replace function public.apply_operations_hub_sellpia_changes(p_sku text, p_changes jsonb)
returns table(saved_count integer, queued_count integer, saved_at timestamptz)
language plpgsql
security invoker
set search_path = public, operations_private, pg_temp
as $$
declare
  v_change jsonb;
  v_field text;
  v_after text;
  v_targets text[];
  v_saved integer := 0;
  v_queued integer := 0;
  v_saved_at timestamptz := now();
begin
  if nullif(btrim(p_sku), '') is null then
    raise exception '셀피아 SKU가 필요합니다.';
  end if;

  if not exists (
    select 1 from operations_private.operations_hub_matrix_core matrix
    where matrix.sellpia_sku_code = p_sku
  ) then
    raise exception '매트릭스에 없는 셀피아 SKU입니다: %', p_sku;
  end if;

  if jsonb_typeof(p_changes) <> 'array' or jsonb_array_length(p_changes) = 0 then
    raise exception '저장할 변경사항이 없습니다.';
  end if;

  select array_remove(array[
    case when matrix.smartstore_product_code is not null then 'smartstore' end,
    case when matrix.makeshop_product_code is not null then 'makeshop' end,
    case when matrix.ably_product_code is not null then 'ably' end
  ], null)
  into v_targets
  from operations_private.operations_hub_matrix_core matrix
  where matrix.sellpia_sku_code = p_sku;

  for v_change in select value from jsonb_array_elements(p_changes)
  loop
    v_field := v_change ->> 'field_key';
    v_after := v_change ->> 'after';

    if v_field not in (
      'sellpia_own_code', 'sellpia_product_name', 'sellpia_option_name',
      'sellpia_current_stock', 'sellpia_sale_price', 'sellpia_image'
    ) then
      raise exception '지원하지 않는 셀피아 필드입니다: %', v_field;
    end if;

    if v_field in ('sellpia_current_stock', 'sellpia_sale_price')
       and (v_after !~ '^\d+(\.\d+)?$' or v_after::numeric < 0) then
      raise exception '재고와 판매가는 0 이상의 숫자여야 합니다.';
    end if;

    if v_field = 'sellpia_image'
       and v_after !~ '^sellpia/[0-9A-Za-z._-]+[.]jpg$' then
      raise exception '이미지 저장 경로가 올바르지 않습니다.';
    end if;

    insert into public.operations_hub_sellpia_overrides (
      sellpia_sku_code, own_code, product_name, option_name,
      current_stock, sale_price, image_storage_path, updated_by, updated_at
    ) values (
      p_sku,
      case when v_field = 'sellpia_own_code' then nullif(v_after, '') end,
      case when v_field = 'sellpia_product_name' then nullif(v_after, '') end,
      case when v_field = 'sellpia_option_name' then nullif(v_after, '') end,
      case when v_field = 'sellpia_current_stock' then v_after::integer end,
      case when v_field = 'sellpia_sale_price' then v_after::numeric end,
      case when v_field = 'sellpia_image' then v_after end,
      'operations_hub_frontend', v_saved_at
    )
    on conflict (sellpia_sku_code) do update set
      own_code = case when v_field = 'sellpia_own_code' then nullif(v_after, '') else operations_hub_sellpia_overrides.own_code end,
      product_name = case when v_field = 'sellpia_product_name' then nullif(v_after, '') else operations_hub_sellpia_overrides.product_name end,
      option_name = case when v_field = 'sellpia_option_name' then nullif(v_after, '') else operations_hub_sellpia_overrides.option_name end,
      current_stock = case when v_field = 'sellpia_current_stock' then v_after::integer else operations_hub_sellpia_overrides.current_stock end,
      sale_price = case when v_field = 'sellpia_sale_price' then v_after::numeric else operations_hub_sellpia_overrides.sale_price end,
      image_storage_path = case when v_field = 'sellpia_image' then v_after else operations_hub_sellpia_overrides.image_storage_path end,
      updated_by = 'operations_hub_frontend',
      updated_at = v_saved_at;

    insert into public.operations_hub_change_queue (
      sellpia_sku_code, field_key, before_value, after_value,
      target_channels, status, requested_by, requested_at
    ) values (
      p_sku, v_field, v_change -> 'before', to_jsonb(v_after),
      case when v_field = 'sellpia_image' then '{}'::text[] else coalesce(v_targets, '{}'::text[]) end,
      case when v_field = 'sellpia_image' then 'saved' else 'pending' end,
      'operations_hub_frontend', v_saved_at
    );

    v_saved := v_saved + 1;
    if v_field <> 'sellpia_image' then v_queued := v_queued + 1; end if;
  end loop;

  return query select v_saved, v_queued, v_saved_at;
end;
$$;

revoke all on function public.apply_operations_hub_sellpia_changes(text, jsonb) from public;
grant execute on function public.apply_operations_hub_sellpia_changes(text, jsonb) to anon, authenticated;

create or replace view public.operations_hub_matrix_live
with (security_invoker = true)
as
select
  matrix.*,
  coalesce(nullif(btrim(override_row.product_name), ''), nullif(btrim(stock.sellpia_product_name), '')) as sellpia_product_name,
  coalesce(nullif(btrim(override_row.option_name), ''), nullif(btrim(stock.sellpia_option_name), '')) as sellpia_option_name,
  coalesce(nullif(btrim(override_row.own_code), ''), nullif(btrim(stock.own_sku), '')) as sellpia_own_code,
  coalesce(override_row.current_stock, stock.stock) as sellpia_current_stock,
  case when override_row.current_stock is not null then override_row.current_stock
       else coalesce(stock.available_stock, stock.integrated_available_stock, stock.stock) end as sellpia_available_stock,
  stock.safety_stock as sellpia_safety_stock,
  coalesce(override_row.sale_price, nullif(regexp_replace(coalesce(stock.raw_payload ->> 'sell_price', ''), '[^0-9.-]', '', 'g'), '')::numeric) as sellpia_sale_price,
  stock.snapshot_completed_at as sellpia_inventory_at,
  smartstore.stock as smartstore_stock,
  smartstore.price as smartstore_price,
  smartstore.snapshot_completed_at as smartstore_inventory_at,
  makeshop.stock as makeshop_stock,
  makeshop.price as makeshop_price,
  makeshop.snapshot_completed_at as makeshop_inventory_at,
  ably.stock as ably_stock,
  ably.price as ably_price,
  ably.snapshot_completed_at as ably_inventory_at,
  case
    when matrix.smartstore_match_tier = 'FAST_REVIEW'
      or matrix.makeshop_match_tier = 'FAST_REVIEW'
      or matrix.ably_match_tier = 'FAST_REVIEW' then 'review'
    when matrix.smartstore_match_tier is null
      and matrix.makeshop_match_tier is null
      and matrix.ably_match_tier is null then 'unmatched'
    else 'connected'
  end::text as overall_status,
  case when override_row.image_storage_path is null then null
       else 'https://bpgvqmtsjgegnrdzmpep.supabase.co/storage/v1/object/public/product-images/' || override_row.image_storage_path end as sellpia_override_image_url,
  override_row.updated_at as sellpia_override_updated_at
from operations_private.operations_hub_matrix_core matrix
left join public.sellpia_stock_latest stock
  on stock.sellpia_sku_code = matrix.sellpia_sku_code
left join public.operations_hub_sellpia_overrides override_row
  on override_row.sellpia_sku_code = matrix.sellpia_sku_code
left join public.seller_inventory_latest smartstore
  on smartstore.source_channel = 'smartstore'
  and smartstore.product_code = matrix.smartstore_product_code
  and smartstore.option_code = coalesce(matrix.smartstore_option_code, '')
left join public.seller_inventory_latest makeshop
  on makeshop.source_channel = 'makeshop'
  and makeshop.product_code = matrix.makeshop_product_code
  and makeshop.option_code = coalesce(matrix.makeshop_option_code, '')
left join public.seller_inventory_latest ably
  on ably.source_channel = 'ably'
  and ably.product_code = matrix.ably_product_code
  and ably.option_code = coalesce(matrix.ably_option_code, '');

revoke all on public.operations_hub_matrix_live from public;
grant select on public.operations_hub_matrix_live to anon, authenticated;

create or replace view public.operations_hub_dashboard_metrics
with (security_invoker = true)
as
select
  count(*)::integer as total_sku,
  count(*) filter (where overall_status <> 'unmatched')::integer as connected_sku,
  count(*) filter (where overall_status = 'unmatched')::integer as unmatched_sku,
  count(*) filter (
    where sellpia_current_stock is not null
      and (
        (smartstore_stock is not null and smartstore_stock <> sellpia_current_stock)
        or (makeshop_stock is not null and makeshop_stock <> sellpia_current_stock)
        or (ably_stock is not null and ably_stock <> sellpia_current_stock)
      )
  )::integer as inventory_mismatch_sku,
  max(greatest(
    coalesce(sellpia_inventory_at, '-infinity'::timestamptz),
    coalesce(smartstore_inventory_at, '-infinity'::timestamptz),
    coalesce(makeshop_inventory_at, '-infinity'::timestamptz),
    coalesce(ably_inventory_at, '-infinity'::timestamptz),
    coalesce(sellpia_override_updated_at, '-infinity'::timestamptz)
  )) as latest_sync_at,
  null::integer as today_picked,
  null::integer as shortage_drawer_qty
from public.operations_hub_matrix_live;

revoke all on public.operations_hub_dashboard_metrics from public;
grant select on public.operations_hub_dashboard_metrics to anon, authenticated;

notify pgrst, 'reload schema';
