-- Extend the System-owned operational master beyond price/stock while keeping
-- uploaded Sellpia snapshots immutable. The source-refresh RPC is deliberately
-- all-SKU and dry-run by default because one execution can touch tens of
-- thousands of rows.

create extension if not exists pgcrypto with schema extensions;

create table if not exists operations_private.operations_hub_operator_credentials (
  credential_id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  is_active boolean not null default true,
  session_ttl interval not null default interval '8 hours',
  password_changed_at timestamptz not null default clock_timestamp(),
  last_login_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint operations_hub_operator_credentials_username_check
    check (username = lower(btrim(username)) and length(username) between 1 and 128),
  constraint operations_hub_operator_credentials_password_hash_check
    check (password_hash ~ '^[$]2[aby][$][0-9]{2}[$]'),
  constraint operations_hub_operator_credentials_password_hash_format_check
    check (password_hash ~ '^[$]2[aby][$](0[4-9]|[12][0-9]|3[01])[$][./A-Za-z0-9]{53}$'),
  constraint operations_hub_operator_credentials_session_ttl_check
    check (session_ttl between interval '5 minutes' and interval '24 hours')
);

create table if not exists operations_private.operations_hub_operator_login_guard (
  guard_id boolean primary key default true check (guard_id),
  failed_attempt_count integer not null default 0 check (failed_attempt_count >= 0),
  failure_window_started_at timestamptz not null default clock_timestamp(),
  last_failed_at timestamptz,
  locked_until timestamptz,
  updated_at timestamptz not null default clock_timestamp()
);

insert into operations_private.operations_hub_operator_login_guard (guard_id)
values (true)
on conflict (guard_id) do nothing;

create table if not exists operations_private.operations_hub_operator_sessions (
  session_id uuid primary key default gen_random_uuid(),
  credential_id bigint not null references operations_private.operations_hub_operator_credentials (credential_id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default clock_timestamp(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  revoke_reason text,
  constraint operations_hub_operator_sessions_token_hash_check
    check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint operations_hub_operator_sessions_expiry_check
    check (expires_at > created_at),
  constraint operations_hub_operator_sessions_revocation_check
    check (
      (revoked_at is null and revoke_reason is null)
      or (revoked_at is not null and revoke_reason is not null)
    )
);

create index if not exists operations_hub_operator_sessions_credential_active_idx
  on operations_private.operations_hub_operator_sessions (credential_id, expires_at desc)
  where revoked_at is null;

alter table operations_private.operations_hub_operator_credentials enable row level security;
alter table operations_private.operations_hub_operator_login_guard enable row level security;
alter table operations_private.operations_hub_operator_sessions enable row level security;

revoke all on table operations_private.operations_hub_operator_credentials from public, anon, authenticated;
revoke all on table operations_private.operations_hub_operator_login_guard from public, anon, authenticated;
revoke all on table operations_private.operations_hub_operator_sessions from public, anon, authenticated;
revoke all on sequence operations_private.operations_hub_operator_credentials_credential_id_seq from public, anon, authenticated;

comment on table operations_private.operations_hub_operator_credentials is
  'Private shared-operator credentials. Initial credentials are provisioned separately by an administrator; no secret seed belongs in migrations.';
comment on column operations_private.operations_hub_operator_credentials.username is
  'Lowercased, trimmed shared operator username used as the server-derived audit actor.';
comment on column operations_private.operations_hub_operator_credentials.password_hash is
  'bcrypt password hash created with extensions.crypt and extensions.gen_salt.';
comment on table operations_private.operations_hub_operator_sessions is
  'Expiring and revocable operator sessions. Stores only SHA-256 token hashes, never raw bearer tokens.';
comment on table operations_private.operations_hub_operator_login_guard is
  'Global shared-operator login throttle: five failures in fifteen minutes locks all username attempts for fifteen minutes.';

create or replace function operations_private.prepare_operations_hub_operator_credential()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  new.username := lower(btrim(new.username));
  new.updated_at := clock_timestamp();

  if tg_op = 'UPDATE' and new.password_hash is distinct from old.password_hash then
    new.password_changed_at := clock_timestamp();
  end if;

  return new;
end;
$$;

revoke all on function operations_private.prepare_operations_hub_operator_credential() from public, anon, authenticated;

drop trigger if exists operations_hub_operator_credentials_prepare
  on operations_private.operations_hub_operator_credentials;
create trigger operations_hub_operator_credentials_prepare
before insert or update on operations_private.operations_hub_operator_credentials
for each row execute function operations_private.prepare_operations_hub_operator_credential();

create or replace function operations_private.revoke_operations_hub_sessions_after_credential_change()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  update operations_private.operations_hub_operator_sessions
  set revoked_at = coalesce(revoked_at, clock_timestamp()),
      revoke_reason = coalesce(
        revoke_reason,
        case when not new.is_active then 'credential_disabled' else 'password_changed' end
      )
  where credential_id = new.credential_id
    and revoked_at is null;

  return new;
end;
$$;

revoke all on function operations_private.revoke_operations_hub_sessions_after_credential_change() from public, anon, authenticated;

drop trigger if exists operations_hub_operator_credentials_revoke_sessions
  on operations_private.operations_hub_operator_credentials;
create trigger operations_hub_operator_credentials_revoke_sessions
after update of password_hash, is_active on operations_private.operations_hub_operator_credentials
for each row
when (
  old.password_hash is distinct from new.password_hash
  or (old.is_active and not new.is_active)
)
execute function operations_private.revoke_operations_hub_sessions_after_credential_change();

create or replace function operations_private.require_operations_hub_operator_session(
  p_session_token text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_token_hash text;
  v_session_id uuid;
  v_username text;
begin
  if p_session_token is null
     or length(p_session_token) <> 64
     or p_session_token !~ '^[0-9a-f]{64}$' then
    raise exception using
      errcode = '42501',
      message = '유효한 운영 세션이 필요합니다.';
  end if;

  v_token_hash := encode(
    extensions.digest(p_session_token, 'sha256'),
    'hex'
  );

  select operator_session.session_id, credential.username
  into v_session_id, v_username
  from operations_private.operations_hub_operator_sessions operator_session
  join operations_private.operations_hub_operator_credentials credential
    on credential.credential_id = operator_session.credential_id
  where operator_session.token_hash = v_token_hash
    and operator_session.revoked_at is null
    and operator_session.expires_at > clock_timestamp()
    and credential.is_active
    and operator_session.created_at >= credential.password_changed_at;

  if v_session_id is null then
    raise exception using
      errcode = '42501',
      message = '운영 세션이 만료되었거나 회수되었습니다.';
  end if;

  return jsonb_build_object('session_id', v_session_id, 'username', v_username);
end;
$$;

revoke all on function operations_private.require_operations_hub_operator_session(text) from public, anon, authenticated;

create or replace function public.operations_hub_login_v1(
  p_username text,
  p_password text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
set statement_timeout = '5s'
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_credential operations_private.operations_hub_operator_credentials%rowtype;
  v_guard operations_private.operations_hub_operator_login_guard%rowtype;
  v_password_matches boolean := false;
  v_next_failed_count integer;
  v_raw_token text;
  v_token_hash text;
  v_session_id uuid;
  v_expires_at timestamptz;
begin
  select guard.*
  into v_guard
  from operations_private.operations_hub_operator_login_guard guard
  where guard.guard_id
  for update;

  v_now := clock_timestamp();

  if v_guard.locked_until is not null and v_guard.locked_until > v_now then
    return jsonb_build_object(
      'authenticated', false,
      'error_code', 'rate_limited',
      'rate_limit_scope', 'shared_operator',
      'retry_after_seconds', greatest(ceil(extract(epoch from (v_guard.locked_until - v_now)))::integer, 1)
    );
  end if;

  if p_username is not null
     and length(btrim(p_username)) between 1 and 128
     and p_password is not null
     and octet_length(p_password) between 1 and 72 then
    select credential.*
    into v_credential
    from operations_private.operations_hub_operator_credentials credential
    where credential.username = lower(btrim(p_username))
      and credential.is_active
    limit 1;
  end if;

  -- An unknown username still performs one bcrypt operation so the response
  -- does not provide a cheap username-existence timing oracle.
  if v_credential.credential_id is null then
    perform extensions.crypt(coalesce(p_password, ''), extensions.gen_salt('bf', 12));
    v_password_matches := false;
  else
    v_password_matches := extensions.crypt(p_password, v_credential.password_hash) = v_credential.password_hash;
  end if;

  if not coalesce(v_password_matches, false) then
    if v_guard.failure_window_started_at <= v_now - interval '15 minutes' then
      v_next_failed_count := 1;
      v_guard.failure_window_started_at := v_now;
    else
      v_next_failed_count := v_guard.failed_attempt_count + 1;
    end if;

    update operations_private.operations_hub_operator_login_guard
    set failed_attempt_count = v_next_failed_count,
        failure_window_started_at = v_guard.failure_window_started_at,
        last_failed_at = v_now,
        locked_until = case when v_next_failed_count >= 5 then v_now + interval '15 minutes' else null end,
        updated_at = v_now
    where guard_id;

    if v_next_failed_count >= 5 then
      return jsonb_build_object(
        'authenticated', false,
        'error_code', 'rate_limited',
        'rate_limit_scope', 'shared_operator',
        'retry_after_seconds', 900
      );
    end if;

    return jsonb_build_object(
      'authenticated', false,
      'error_code', 'invalid_credentials',
      'rate_limit_scope', 'shared_operator',
      'retry_after_seconds', 0
    );
  end if;

  update operations_private.operations_hub_operator_login_guard
  set failed_attempt_count = 0,
      failure_window_started_at = v_now,
      last_failed_at = null,
      locked_until = null,
      updated_at = v_now
  where guard_id;

  update operations_private.operations_hub_operator_credentials
  set last_login_at = v_now,
      updated_at = v_now
  where credential_id = v_credential.credential_id;

  update operations_private.operations_hub_operator_sessions
  set revoked_at = v_now,
      revoke_reason = 'expired_cleanup'
  where credential_id = v_credential.credential_id
    and revoked_at is null
    and expires_at <= v_now;

  v_raw_token := encode(extensions.gen_random_bytes(32), 'hex');
  v_token_hash := encode(extensions.digest(v_raw_token, 'sha256'), 'hex');
  v_expires_at := v_now + v_credential.session_ttl;

  insert into operations_private.operations_hub_operator_sessions (
    credential_id,
    token_hash,
    created_at,
    expires_at
  ) values (
    v_credential.credential_id,
    v_token_hash,
    v_now,
    v_expires_at
  )
  returning session_id into v_session_id;

  return jsonb_build_object(
    'authenticated', true,
    'session_token', v_raw_token,
    'session_id', v_session_id,
    'expires_at', v_expires_at
  );
end;
$$;

comment on function public.operations_hub_login_v1(text,text) is
  'Authenticates the shared Operations Hub operator with bcrypt and returns one raw expiring token exactly once.';
revoke all on function public.operations_hub_login_v1(text,text) from public;
grant execute on function public.operations_hub_login_v1(text,text) to anon, authenticated;

create or replace function public.operations_hub_check_session_v1(
  p_session_token text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_token_hash text;
  v_session record;
begin
  if p_session_token is null
     or length(p_session_token) <> 64
     or p_session_token !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('authenticated', false, 'error_code', 'invalid_session');
  end if;

  v_token_hash := encode(extensions.digest(p_session_token, 'sha256'), 'hex');

  select
    operator_session.session_id,
    operator_session.created_at,
    operator_session.expires_at,
    operator_session.revoked_at,
    credential.is_active,
    credential.password_changed_at
  into v_session
  from operations_private.operations_hub_operator_sessions operator_session
  join operations_private.operations_hub_operator_credentials credential
    on credential.credential_id = operator_session.credential_id
  where operator_session.token_hash = v_token_hash;

  if v_session.session_id is null then
    return jsonb_build_object('authenticated', false, 'error_code', 'invalid_session');
  end if;
  if v_session.revoked_at is not null or not v_session.is_active or v_session.created_at < v_session.password_changed_at then
    return jsonb_build_object('authenticated', false, 'error_code', 'revoked_session');
  end if;
  if v_session.expires_at <= v_now then
    return jsonb_build_object('authenticated', false, 'error_code', 'expired_session');
  end if;

  return jsonb_build_object(
    'authenticated', true,
    'session_id', v_session.session_id,
    'expires_at', v_session.expires_at
  );
end;
$$;

comment on function public.operations_hub_check_session_v1(text) is
  'Checks an Operations Hub bearer token without returning or persisting the raw token.';
revoke all on function public.operations_hub_check_session_v1(text) from public;
grant execute on function public.operations_hub_check_session_v1(text) to anon, authenticated;

create or replace function public.operations_hub_logout_v1(
  p_session_token text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_token_hash text;
begin
  if p_session_token is not null
     and length(p_session_token) = 64
     and p_session_token ~ '^[0-9a-f]{64}$' then
    v_token_hash := encode(extensions.digest(p_session_token, 'sha256'), 'hex');

    update operations_private.operations_hub_operator_sessions
    set revoked_at = coalesce(revoked_at, v_now),
        revoke_reason = coalesce(revoke_reason, 'logout')
    where token_hash = v_token_hash;
  end if;

  -- Idempotent and deliberately non-enumerating.
  return jsonb_build_object('logged_out', true);
end;
$$;

comment on function public.operations_hub_logout_v1(text) is
  'Idempotently revokes an Operations Hub bearer token by its SHA-256 hash.';
revoke all on function public.operations_hub_logout_v1(text) from public;
grant execute on function public.operations_hub_logout_v1(text) to anon, authenticated;

alter table public.operations_hub_sku_operational_master
  add column if not exists purchase_price numeric,
  add column if not exists order_unit numeric,
  add column if not exists minimum_order_unit numeric,
  add column if not exists purchase_price_version bigint not null default 0,
  add column if not exists order_unit_version bigint not null default 0,
  add column if not exists minimum_order_unit_version bigint not null default 0,
  add column if not exists purchase_price_updated_at timestamptz,
  add column if not exists order_unit_updated_at timestamptz,
  add column if not exists minimum_order_unit_updated_at timestamptz;

alter table public.operations_hub_sku_operational_master
  drop constraint if exists operations_hub_sku_operational_master_purchase_price_check,
  drop constraint if exists operations_hub_sku_operational_master_order_unit_check,
  drop constraint if exists operations_hub_sku_operational_master_minimum_order_unit_check,
  drop constraint if exists operations_hub_sku_operational_master_purchase_price_version_check,
  drop constraint if exists operations_hub_sku_operational_master_order_unit_version_check,
  drop constraint if exists operations_hub_sku_operational_master_minimum_order_unit_version_check,
  add constraint operations_hub_sku_operational_master_purchase_price_check
    check (purchase_price is null or purchase_price >= 0),
  add constraint operations_hub_sku_operational_master_order_unit_check
    check (order_unit is null or order_unit >= 0),
  add constraint operations_hub_sku_operational_master_minimum_order_unit_check
    check (minimum_order_unit is null or minimum_order_unit >= 0),
  add constraint operations_hub_sku_operational_master_purchase_price_version_check
    check (purchase_price_version >= 0),
  add constraint operations_hub_sku_operational_master_order_unit_version_check
    check (order_unit_version >= 0),
  add constraint operations_hub_sku_operational_master_minimum_order_unit_version_check
    check (minimum_order_unit_version >= 0);

alter table public.operations_hub_sku_operational_events
  drop constraint if exists operations_hub_sku_operational_events_field_key_check;

alter table public.operations_hub_sku_operational_events
  add constraint operations_hub_sku_operational_events_field_key_check
  check (field_key in (
    'system_base_price',
    'system_stock',
    'sellpia_purchase_price',
    'sellpia_order_unit',
    'sellpia_minimum_order_unit'
  ));

create or replace view public.operations_hub_sku_operational_live
with (security_invoker = true)
as
select
  master.sellpia_sku_code,
  master.base_price as system_base_price,
  master.stock_quantity as system_stock,
  master.price_version as system_price_version,
  master.stock_version as system_stock_version,
  master.price_updated_at as system_price_updated_at,
  master.stock_updated_at as system_stock_updated_at,
  master.updated_by as system_updated_by,
  master.updated_at as system_updated_at,
  source_stock.purchase_price as sellpia_source_purchase_price,
  source_stock.order_unit as sellpia_source_order_unit,
  source_stock.minimum_order_unit as sellpia_source_minimum_order_unit,
  coalesce(master.purchase_price, source_stock.purchase_price) as sellpia_purchase_price,
  coalesce(master.order_unit, source_stock.order_unit) as sellpia_order_unit,
  coalesce(master.minimum_order_unit, source_stock.minimum_order_unit) as sellpia_minimum_order_unit,
  master.purchase_price as sellpia_purchase_price_override,
  master.order_unit as sellpia_order_unit_override,
  master.minimum_order_unit as sellpia_minimum_order_unit_override,
  master.purchase_price_version as sellpia_purchase_price_version,
  master.order_unit_version as sellpia_order_unit_version,
  master.minimum_order_unit_version as sellpia_minimum_order_unit_version,
  master.purchase_price_updated_at as sellpia_purchase_price_updated_at,
  master.order_unit_updated_at as sellpia_order_unit_updated_at,
  master.minimum_order_unit_updated_at as sellpia_minimum_order_unit_updated_at,
  master.purchase_price is not null as sellpia_purchase_price_is_overridden,
  master.order_unit is not null as sellpia_order_unit_is_overridden,
  master.minimum_order_unit is not null as sellpia_minimum_order_unit_is_overridden
from public.operations_hub_sku_operational_master master
left join public.sellpia_stock_latest source_stock
  on source_stock.sellpia_sku_code = master.sellpia_sku_code;

revoke all on public.operations_hub_sku_operational_live from public, anon, authenticated;
grant select on public.operations_hub_sku_operational_live to anon, authenticated;

drop function if exists public.save_operations_hub_sku_operational_value(text,text,numeric,text,text,jsonb);

create or replace function public.save_operations_hub_sku_operational_value(
  p_session_token text,
  p_sellpia_sku_code text,
  p_field_key text,
  p_value numeric,
  p_change_source text default 'manual',
  p_actor text default 'operations-hub',
  p_metadata jsonb default '{}'::jsonb
)
returns setof public.operations_hub_sku_operational_live
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  v_session jsonb;
  v_session_id uuid;
  v_sku text := nullif(btrim(p_sellpia_sku_code), '');
  v_field text := lower(btrim(coalesce(p_field_key, '')));
  v_source text := lower(btrim(coalesce(p_change_source, 'manual')));
  v_actor text;
  v_before numeric;
  v_metadata jsonb;
  v_now timestamptz := clock_timestamp();
begin
  v_session := operations_private.require_operations_hub_operator_session(p_session_token);
  v_session_id := (v_session ->> 'session_id')::uuid;
  -- p_actor remains in the wire contract for client compatibility only. Audit
  -- identity is always derived from the verified credential.
  v_actor := v_session ->> 'username';

  if v_sku is null then raise exception '셀피아 SKU가 필요합니다.'; end if;
  if position(p_session_token in v_sku) > 0 then
    raise exception '세션 토큰은 SKU 값에 포함할 수 없습니다.';
  end if;
  if v_field not in (
    'system_base_price',
    'system_stock',
    'sellpia_purchase_price',
    'sellpia_order_unit',
    'sellpia_minimum_order_unit'
  ) then
    raise exception '지원하지 않는 시스템 기준 필드입니다: %', v_field;
  end if;
  if v_source not in ('manual', 'source_accept', 'bulk_import', 'reset') then
    raise exception '지원하지 않는 변경 출처입니다: %', v_source;
  end if;
  if p_value is not null and p_value < 0 then
    raise exception '운영 기준값은 0 이상이어야 합니다.';
  end if;
  if v_field = 'system_stock' and p_value is not null and p_value <> trunc(p_value) then
    raise exception '재고는 정수여야 합니다.';
  end if;
  if jsonb_typeof(coalesce(p_metadata, '{}'::jsonb)) <> 'object' then
    raise exception '변경 메타데이터는 JSON 객체여야 합니다.';
  end if;
  if position(p_session_token in coalesce(p_metadata, '{}'::jsonb)::text) > 0 then
    raise exception '세션 토큰은 변경 메타데이터에 포함할 수 없습니다.';
  end if;

  v_metadata := (
    coalesce(p_metadata, '{}'::jsonb)
      - array['session_token', 'p_session_token', 'authorization', 'token']::text[]
  ) || jsonb_build_object('session_id', v_session_id);

  -- Concurrent single-cell saves may proceed together, while a bulk refresh
  -- takes the exclusive lock for the same field.
  perform pg_advisory_xact_lock_shared(
    hashtextextended('operations_hub_master_field:' || v_field, 0)
  );

  select case v_field
    when 'system_base_price' then master.base_price
    when 'system_stock' then master.stock_quantity::numeric
    when 'sellpia_purchase_price' then master.purchase_price
    when 'sellpia_order_unit' then master.order_unit
    when 'sellpia_minimum_order_unit' then master.minimum_order_unit
  end
  into v_before
  from public.operations_hub_sku_operational_master master
  where master.sellpia_sku_code = v_sku
  for update;

  insert into public.operations_hub_sku_operational_master (
    sellpia_sku_code,
    base_price,
    stock_quantity,
    purchase_price,
    order_unit,
    minimum_order_unit,
    price_version,
    stock_version,
    purchase_price_version,
    order_unit_version,
    minimum_order_unit_version,
    price_updated_at,
    stock_updated_at,
    purchase_price_updated_at,
    order_unit_updated_at,
    minimum_order_unit_updated_at,
    updated_by,
    created_at,
    updated_at
  ) values (
    v_sku,
    case when v_field = 'system_base_price' then p_value else null end,
    case when v_field = 'system_stock' then p_value::integer else null end,
    case when v_field = 'sellpia_purchase_price' then p_value else null end,
    case when v_field = 'sellpia_order_unit' then p_value else null end,
    case when v_field = 'sellpia_minimum_order_unit' then p_value else null end,
    case when v_field = 'system_base_price' then 1 else 0 end,
    case when v_field = 'system_stock' then 1 else 0 end,
    case when v_field = 'sellpia_purchase_price' then 1 else 0 end,
    case when v_field = 'sellpia_order_unit' then 1 else 0 end,
    case when v_field = 'sellpia_minimum_order_unit' then 1 else 0 end,
    case when v_field = 'system_base_price' then v_now else null end,
    case when v_field = 'system_stock' then v_now else null end,
    case when v_field = 'sellpia_purchase_price' then v_now else null end,
    case when v_field = 'sellpia_order_unit' then v_now else null end,
    case when v_field = 'sellpia_minimum_order_unit' then v_now else null end,
    v_actor,
    v_now,
    v_now
  )
  on conflict (sellpia_sku_code) do update set
    base_price = case when v_field = 'system_base_price' then excluded.base_price else operations_hub_sku_operational_master.base_price end,
    stock_quantity = case when v_field = 'system_stock' then excluded.stock_quantity else operations_hub_sku_operational_master.stock_quantity end,
    purchase_price = case when v_field = 'sellpia_purchase_price' then excluded.purchase_price else operations_hub_sku_operational_master.purchase_price end,
    order_unit = case when v_field = 'sellpia_order_unit' then excluded.order_unit else operations_hub_sku_operational_master.order_unit end,
    minimum_order_unit = case when v_field = 'sellpia_minimum_order_unit' then excluded.minimum_order_unit else operations_hub_sku_operational_master.minimum_order_unit end,
    price_version = operations_hub_sku_operational_master.price_version + case when v_field = 'system_base_price' and operations_hub_sku_operational_master.base_price is distinct from excluded.base_price then 1 else 0 end,
    stock_version = operations_hub_sku_operational_master.stock_version + case when v_field = 'system_stock' and operations_hub_sku_operational_master.stock_quantity is distinct from excluded.stock_quantity then 1 else 0 end,
    purchase_price_version = operations_hub_sku_operational_master.purchase_price_version + case when v_field = 'sellpia_purchase_price' and operations_hub_sku_operational_master.purchase_price is distinct from excluded.purchase_price then 1 else 0 end,
    order_unit_version = operations_hub_sku_operational_master.order_unit_version + case when v_field = 'sellpia_order_unit' and operations_hub_sku_operational_master.order_unit is distinct from excluded.order_unit then 1 else 0 end,
    minimum_order_unit_version = operations_hub_sku_operational_master.minimum_order_unit_version + case when v_field = 'sellpia_minimum_order_unit' and operations_hub_sku_operational_master.minimum_order_unit is distinct from excluded.minimum_order_unit then 1 else 0 end,
    price_updated_at = case when v_field = 'system_base_price' and operations_hub_sku_operational_master.base_price is distinct from excluded.base_price then v_now else operations_hub_sku_operational_master.price_updated_at end,
    stock_updated_at = case when v_field = 'system_stock' and operations_hub_sku_operational_master.stock_quantity is distinct from excluded.stock_quantity then v_now else operations_hub_sku_operational_master.stock_updated_at end,
    purchase_price_updated_at = case when v_field = 'sellpia_purchase_price' and operations_hub_sku_operational_master.purchase_price is distinct from excluded.purchase_price then v_now else operations_hub_sku_operational_master.purchase_price_updated_at end,
    order_unit_updated_at = case when v_field = 'sellpia_order_unit' and operations_hub_sku_operational_master.order_unit is distinct from excluded.order_unit then v_now else operations_hub_sku_operational_master.order_unit_updated_at end,
    minimum_order_unit_updated_at = case when v_field = 'sellpia_minimum_order_unit' and operations_hub_sku_operational_master.minimum_order_unit is distinct from excluded.minimum_order_unit then v_now else operations_hub_sku_operational_master.minimum_order_unit_updated_at end,
    updated_by = case when (
      (v_field = 'system_base_price' and operations_hub_sku_operational_master.base_price is distinct from excluded.base_price)
      or (v_field = 'system_stock' and operations_hub_sku_operational_master.stock_quantity is distinct from excluded.stock_quantity)
      or (v_field = 'sellpia_purchase_price' and operations_hub_sku_operational_master.purchase_price is distinct from excluded.purchase_price)
      or (v_field = 'sellpia_order_unit' and operations_hub_sku_operational_master.order_unit is distinct from excluded.order_unit)
      or (v_field = 'sellpia_minimum_order_unit' and operations_hub_sku_operational_master.minimum_order_unit is distinct from excluded.minimum_order_unit)
    ) then v_actor else operations_hub_sku_operational_master.updated_by end,
    updated_at = case when (
      (v_field = 'system_base_price' and operations_hub_sku_operational_master.base_price is distinct from excluded.base_price)
      or (v_field = 'system_stock' and operations_hub_sku_operational_master.stock_quantity is distinct from excluded.stock_quantity)
      or (v_field = 'sellpia_purchase_price' and operations_hub_sku_operational_master.purchase_price is distinct from excluded.purchase_price)
      or (v_field = 'sellpia_order_unit' and operations_hub_sku_operational_master.order_unit is distinct from excluded.order_unit)
      or (v_field = 'sellpia_minimum_order_unit' and operations_hub_sku_operational_master.minimum_order_unit is distinct from excluded.minimum_order_unit)
    ) then v_now else operations_hub_sku_operational_master.updated_at end;

  if v_before is distinct from p_value then
    insert into public.operations_hub_sku_operational_events (
      sellpia_sku_code,
      field_key,
      before_value,
      after_value,
      change_source,
      actor,
      metadata,
      created_at
    ) values (
      v_sku,
      v_field,
      v_before,
      p_value,
      v_source,
      v_actor,
      v_metadata,
      v_now
    );
  end if;

  if v_field in ('system_base_price', 'system_stock') then
    insert into public.operations_hub_sellpia_overrides (
      sellpia_sku_code,
      current_stock,
      sale_price,
      updated_by,
      updated_at
    ) values (
      v_sku,
      case when v_field = 'system_stock' then p_value::integer else null end,
      case when v_field = 'system_base_price' then p_value else null end,
      v_actor,
      v_now
    )
    on conflict (sellpia_sku_code) do update set
      current_stock = case when v_field = 'system_stock' then excluded.current_stock else operations_hub_sellpia_overrides.current_stock end,
      sale_price = case when v_field = 'system_base_price' then excluded.sale_price else operations_hub_sellpia_overrides.sale_price end,
      updated_by = v_actor,
      updated_at = v_now;
  end if;

  return query
  select live_row.*
  from public.operations_hub_sku_operational_live live_row
  where live_row.sellpia_sku_code = v_sku;
end;
$$;

comment on function public.save_operations_hub_sku_operational_value(text,text,text,numeric,text,text,jsonb) is
  'Requires an expiring operator session, then immediately saves one whitelisted System-owned price, stock, or procurement override with an audit event.';

revoke all on function public.save_operations_hub_sku_operational_value(text,text,text,numeric,text,text,jsonb) from public;
grant execute on function public.save_operations_hub_sku_operational_value(text,text,text,numeric,text,text,jsonb) to anon, authenticated;

-- Fail closed with SQLSTATE 42501 for callers still using the former no-token
-- signature. This overload performs no read or write and exists only to make a
-- missing token an authorization error instead of a PostgREST lookup error.
create or replace function public.save_operations_hub_sku_operational_value(
  p_sellpia_sku_code text,
  p_field_key text,
  p_value numeric,
  p_change_source text default 'manual',
  p_actor text default 'operations-hub',
  p_metadata jsonb default '{}'::jsonb
)
returns setof public.operations_hub_sku_operational_live
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  raise exception using
    errcode = '42501',
    message = '운영 세션 토큰이 필요합니다.';
end;
$$;

comment on function public.save_operations_hub_sku_operational_value(text,text,numeric,text,text,jsonb) is
  'Fail-closed compatibility overload. It never writes and always raises SQLSTATE 42501 because the session token is missing.';
revoke all on function public.save_operations_hub_sku_operational_value(text,text,numeric,text,text,jsonb) from public;
grant execute on function public.save_operations_hub_sku_operational_value(text,text,numeric,text,text,jsonb) to anon, authenticated;

drop function if exists public.refresh_operations_hub_master_column_from_source_v1(text,text,uuid,boolean);

create or replace function public.refresh_operations_hub_master_column_from_source_v1(
  p_session_token text,
  p_field_key text,
  p_actor text default 'operations-hub',
  p_request_id uuid default gen_random_uuid(),
  p_dry_run boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
set statement_timeout = '45s'
as $$
declare
  v_session jsonb;
  v_session_id uuid;
  v_field text := lower(btrim(coalesce(p_field_key, '')));
  v_actor text;
  v_request_id uuid := coalesce(p_request_id, gen_random_uuid());
  v_dry_run boolean := coalesce(p_dry_run, true);
  v_now timestamptz := clock_timestamp();
  v_total integer := 0;
  v_source_count integer := 0;
  v_affected integer := 0;
begin
  v_session := operations_private.require_operations_hub_operator_session(p_session_token);
  v_session_id := (v_session ->> 'session_id')::uuid;
  -- Never trust the caller-provided p_actor for a privileged bulk operation.
  v_actor := v_session ->> 'username';

  if v_field not in (
    'system_base_price',
    'system_stock',
    'sellpia_purchase_price',
    'sellpia_order_unit',
    'sellpia_minimum_order_unit'
  ) then
    raise exception '원본값 전체 갱신을 지원하지 않는 필드입니다: %', v_field;
  end if;

  if v_dry_run then
    with source_values as materialized (
    select
      source_stock.sellpia_sku_code,
      case v_field
        when 'system_base_price' then nullif(
          regexp_replace(coalesce(source_stock.raw_payload ->> 'sell_price', ''), '[^0-9.-]', '', 'g'),
          ''
        )::numeric
        when 'system_stock' then source_stock.stock::numeric
        when 'sellpia_purchase_price' then source_stock.purchase_price
        when 'sellpia_order_unit' then source_stock.order_unit
        when 'sellpia_minimum_order_unit' then source_stock.minimum_order_unit
      end as source_value
    from public.sellpia_stock_latest source_stock
  ), compared as (
    select
      source_values.source_value,
      case v_field
        when 'system_base_price' then master.base_price
        when 'system_stock' then master.stock_quantity::numeric
        when 'sellpia_purchase_price' then master.purchase_price
        when 'sellpia_order_unit' then master.order_unit
        when 'sellpia_minimum_order_unit' then master.minimum_order_unit
      end as current_value
    from source_values
    left join public.operations_hub_sku_operational_master master
      on master.sellpia_sku_code = source_values.sellpia_sku_code
  )
  select
    count(*)::integer,
    count(*) filter (where source_value is not null)::integer,
    count(*) filter (
      where source_value is not null
        and current_value is distinct from source_value
    )::integer
  into v_total, v_source_count, v_affected
    from compared;
  else
    -- One exclusive field lock makes the preview-to-write operation internally
    -- consistent with all single-cell saves that use the shared counterpart.
    perform pg_advisory_xact_lock(
      hashtextextended('operations_hub_master_field:' || v_field, 0)
    );

    with source_values as materialized (
      select
        source_stock.sellpia_sku_code,
        case v_field
          when 'system_base_price' then nullif(
            regexp_replace(coalesce(source_stock.raw_payload ->> 'sell_price', ''), '[^0-9.-]', '', 'g'),
            ''
          )::numeric
          when 'system_stock' then source_stock.stock::numeric
          when 'sellpia_purchase_price' then source_stock.purchase_price
          when 'sellpia_order_unit' then source_stock.order_unit
          when 'sellpia_minimum_order_unit' then source_stock.minimum_order_unit
        end as source_value
      from public.sellpia_stock_latest source_stock
    ), compared as materialized (
      select
        source_values.sellpia_sku_code,
        source_values.source_value,
        case v_field
          when 'system_base_price' then master.base_price
          when 'system_stock' then master.stock_quantity::numeric
          when 'sellpia_purchase_price' then master.purchase_price
          when 'sellpia_order_unit' then master.order_unit
          when 'sellpia_minimum_order_unit' then master.minimum_order_unit
        end as current_value
      from source_values
      left join public.operations_hub_sku_operational_master master
        on master.sellpia_sku_code = source_values.sellpia_sku_code
    ), stats as (
      select
        count(*)::integer as total_sku_count,
        count(*) filter (where source_value is not null)::integer as source_value_count
      from compared
    ), changed as materialized (
      select sellpia_sku_code, source_value, current_value
      from compared
      where source_value is not null
        and current_value is distinct from source_value
    ), logged as (
      insert into public.operations_hub_sku_operational_events (
        sellpia_sku_code,
        field_key,
        before_value,
        after_value,
        change_source,
        actor,
        metadata,
        created_at
      )
      select
        changed.sellpia_sku_code,
        v_field,
        changed.current_value,
        changed.source_value,
        'source_accept',
        v_actor,
        jsonb_build_object(
          'operation', 'bulk_source_refresh',
          'request_id', v_request_id,
          'field_key', v_field,
          'dry_run', false,
          'session_id', v_session_id
        ),
        v_now
      from changed
      returning 1
    ), saved as (
      insert into public.operations_hub_sku_operational_master (
        sellpia_sku_code,
        base_price,
        stock_quantity,
        purchase_price,
        order_unit,
        minimum_order_unit,
        price_version,
        stock_version,
        purchase_price_version,
        order_unit_version,
        minimum_order_unit_version,
        price_updated_at,
        stock_updated_at,
        purchase_price_updated_at,
        order_unit_updated_at,
        minimum_order_unit_updated_at,
        updated_by,
        created_at,
        updated_at
      )
      select
        changed.sellpia_sku_code,
        case when v_field = 'system_base_price' then changed.source_value else null end,
        case when v_field = 'system_stock' then changed.source_value::integer else null end,
        case when v_field = 'sellpia_purchase_price' then changed.source_value else null end,
        case when v_field = 'sellpia_order_unit' then changed.source_value else null end,
        case when v_field = 'sellpia_minimum_order_unit' then changed.source_value else null end,
        case when v_field = 'system_base_price' then 1 else 0 end,
        case when v_field = 'system_stock' then 1 else 0 end,
        case when v_field = 'sellpia_purchase_price' then 1 else 0 end,
        case when v_field = 'sellpia_order_unit' then 1 else 0 end,
        case when v_field = 'sellpia_minimum_order_unit' then 1 else 0 end,
        case when v_field = 'system_base_price' then v_now else null end,
        case when v_field = 'system_stock' then v_now else null end,
        case when v_field = 'sellpia_purchase_price' then v_now else null end,
        case when v_field = 'sellpia_order_unit' then v_now else null end,
        case when v_field = 'sellpia_minimum_order_unit' then v_now else null end,
        v_actor,
        v_now,
        v_now
      from changed
      on conflict (sellpia_sku_code) do update set
        base_price = case when v_field = 'system_base_price' then excluded.base_price else operations_hub_sku_operational_master.base_price end,
        stock_quantity = case when v_field = 'system_stock' then excluded.stock_quantity else operations_hub_sku_operational_master.stock_quantity end,
        purchase_price = case when v_field = 'sellpia_purchase_price' then excluded.purchase_price else operations_hub_sku_operational_master.purchase_price end,
        order_unit = case when v_field = 'sellpia_order_unit' then excluded.order_unit else operations_hub_sku_operational_master.order_unit end,
        minimum_order_unit = case when v_field = 'sellpia_minimum_order_unit' then excluded.minimum_order_unit else operations_hub_sku_operational_master.minimum_order_unit end,
        price_version = operations_hub_sku_operational_master.price_version + case when v_field = 'system_base_price' then 1 else 0 end,
        stock_version = operations_hub_sku_operational_master.stock_version + case when v_field = 'system_stock' then 1 else 0 end,
        purchase_price_version = operations_hub_sku_operational_master.purchase_price_version + case when v_field = 'sellpia_purchase_price' then 1 else 0 end,
        order_unit_version = operations_hub_sku_operational_master.order_unit_version + case when v_field = 'sellpia_order_unit' then 1 else 0 end,
        minimum_order_unit_version = operations_hub_sku_operational_master.minimum_order_unit_version + case when v_field = 'sellpia_minimum_order_unit' then 1 else 0 end,
        price_updated_at = case when v_field = 'system_base_price' then v_now else operations_hub_sku_operational_master.price_updated_at end,
        stock_updated_at = case when v_field = 'system_stock' then v_now else operations_hub_sku_operational_master.stock_updated_at end,
        purchase_price_updated_at = case when v_field = 'sellpia_purchase_price' then v_now else operations_hub_sku_operational_master.purchase_price_updated_at end,
        order_unit_updated_at = case when v_field = 'sellpia_order_unit' then v_now else operations_hub_sku_operational_master.order_unit_updated_at end,
        minimum_order_unit_updated_at = case when v_field = 'sellpia_minimum_order_unit' then v_now else operations_hub_sku_operational_master.minimum_order_unit_updated_at end,
        updated_by = v_actor,
        updated_at = v_now
      returning sellpia_sku_code
    ), mirrored as (
      insert into public.operations_hub_sellpia_overrides (
        sellpia_sku_code,
        current_stock,
        sale_price,
        updated_by,
        updated_at
      )
      select
        changed.sellpia_sku_code,
        case when v_field = 'system_stock' then changed.source_value::integer else null end,
        case when v_field = 'system_base_price' then changed.source_value else null end,
        v_actor,
        v_now
      from changed
      where v_field in ('system_base_price', 'system_stock')
      on conflict (sellpia_sku_code) do update set
        current_stock = case when v_field = 'system_stock' then excluded.current_stock else operations_hub_sellpia_overrides.current_stock end,
        sale_price = case when v_field = 'system_base_price' then excluded.sale_price else operations_hub_sellpia_overrides.sale_price end,
        updated_by = v_actor,
        updated_at = v_now
      returning sellpia_sku_code
    )
    select
      stats.total_sku_count,
      stats.source_value_count,
      (select count(*)::integer from saved)
    into v_total, v_source_count, v_affected
    from stats;
  end if;

  return jsonb_build_object(
    'request_id', v_request_id,
    'field_key', v_field,
    'dry_run', v_dry_run,
    'total_sku_count', v_total,
    'source_value_count', v_source_count,
    'affected_count', v_affected,
    'skipped_count', greatest(v_source_count - v_affected, 0),
    'source_missing_count', greatest(v_total - v_source_count, 0),
    'completed_at', clock_timestamp()
  );
end;
$$;

comment on function public.refresh_operations_hub_master_column_from_source_v1(text,text,text,uuid,boolean) is
  'Requires an expiring operator session, then previews by default or atomically refreshes one whitelisted System master column for every SKU from the latest immutable Sellpia snapshot.';

revoke all on function public.refresh_operations_hub_master_column_from_source_v1(text,text,text,uuid,boolean) from public;
grant execute on function public.refresh_operations_hub_master_column_from_source_v1(text,text,text,uuid,boolean) to anon, authenticated;

create or replace function public.refresh_operations_hub_master_column_from_source_v1(
  p_field_key text,
  p_actor text default 'operations-hub',
  p_request_id uuid default gen_random_uuid(),
  p_dry_run boolean default true
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  raise exception using
    errcode = '42501',
    message = '운영 세션 토큰이 필요합니다.';
end;
$$;

comment on function public.refresh_operations_hub_master_column_from_source_v1(text,text,uuid,boolean) is
  'Fail-closed compatibility overload. It never previews or writes and always raises SQLSTATE 42501 because the session token is missing.';
revoke all on function public.refresh_operations_hub_master_column_from_source_v1(text,text,uuid,boolean) from public;
grant execute on function public.refresh_operations_hub_master_column_from_source_v1(text,text,uuid,boolean) to anon, authenticated;

create or replace view public.operations_hub_inbound_cost_live
with (security_invoker = true)
as
select
  stock.sellpia_sku_code,
  coalesce(master.purchase_price, stock.purchase_price) as sellpia_purchase_price,
  coalesce(master.order_unit, stock.order_unit) as sellpia_order_unit,
  coalesce(master.minimum_order_unit, stock.minimum_order_unit) as sellpia_minimum_order_unit,
  settings.manual_cost as actual_inbound_manual_cost,
  settings.formula_tag_id as inbound_cost_formula_tag_id,
  formula.tag_name as inbound_cost_formula_tag_name,
  formula.tag_color as inbound_cost_formula_tag_color,
  case
    when settings.manual_cost is not null then settings.manual_cost
    when settings.formula_tag_id is not null then public.calculate_operations_hub_inbound_cost(
      coalesce(master.purchase_price, stock.purchase_price),
      formula.multiply_value,
      formula.divide_value,
      formula.add_value,
      formula.rounding_unit,
      formula.rounding_mode
    )
    else null
  end as actual_inbound_cost,
  case
    when settings.manual_cost is not null then 'manual'
    when settings.formula_tag_id is not null then 'formula'
    else null
  end as actual_inbound_cost_mode,
  settings.updated_at as actual_inbound_cost_updated_at,
  stock.purchase_price as sellpia_source_purchase_price,
  stock.order_unit as sellpia_source_order_unit,
  stock.minimum_order_unit as sellpia_source_minimum_order_unit,
  master.purchase_price is not null as sellpia_purchase_price_is_overridden,
  master.order_unit is not null as sellpia_order_unit_is_overridden,
  master.minimum_order_unit is not null as sellpia_minimum_order_unit_is_overridden,
  master.purchase_price_version as sellpia_purchase_price_version,
  master.order_unit_version as sellpia_order_unit_version,
  master.minimum_order_unit_version as sellpia_minimum_order_unit_version,
  master.purchase_price_updated_at as sellpia_purchase_price_updated_at,
  master.order_unit_updated_at as sellpia_order_unit_updated_at,
  master.minimum_order_unit_updated_at as sellpia_minimum_order_unit_updated_at
from public.sellpia_stock_latest stock
left join public.operations_hub_sku_operational_master master
  on master.sellpia_sku_code = stock.sellpia_sku_code
left join public.operations_hub_inbound_cost_settings settings
  on settings.sellpia_sku_code = stock.sellpia_sku_code
left join public.operations_hub_inbound_cost_formula_tags formula
  on formula.tag_id = settings.formula_tag_id
 and formula.is_active;

revoke all on public.operations_hub_inbound_cost_live from public, anon, authenticated;
grant select on public.operations_hub_inbound_cost_live to anon, authenticated;

notify pgrst, 'reload schema';
