-- Safe, resumable batches for the matrix "selected cells -> source value" action.
-- The whole-database System-column refresh remains a separate operation.

create table if not exists operations_private.operations_hub_selected_source_refresh_batches (
  batch_id uuid primary key default gen_random_uuid(),
  preview_request_id uuid not null unique,
  apply_request_id uuid unique,
  retry_of_batch_id uuid references operations_private.operations_hub_selected_source_refresh_batches(batch_id),
  payload_hash text not null,
  scope_json jsonb not null default '{}'::jsonb,
  status text not null default 'previewing',
  actor text not null,
  session_id uuid not null,
  requested_count integer not null default 0,
  ready_count integer not null default 0,
  skipped_count integer not null default 0,
  failed_count integer not null default 0,
  success_count integer not null default 0,
  verified_count integer not null default 0,
  created_at timestamptz not null default clock_timestamp(),
  previewed_at timestamptz,
  applied_at timestamptz,
  completed_at timestamptz,
  constraint operations_hub_selected_source_refresh_batches_scope_check
    check (jsonb_typeof(scope_json) = 'object'),
  constraint operations_hub_selected_source_refresh_batches_status_check
    check (status in ('previewing','preview_ready','preview_blocked','applying','completed','completed_with_failures')),
  constraint operations_hub_selected_source_refresh_batches_counts_check
    check (
      requested_count >= 0 and ready_count >= 0 and skipped_count >= 0 and failed_count >= 0
      and success_count >= 0 and verified_count >= 0
    )
);

create table if not exists operations_private.operations_hub_selected_source_refresh_items (
  item_id bigint generated by default as identity primary key,
  batch_id uuid not null references operations_private.operations_hub_selected_source_refresh_batches(batch_id) on delete cascade,
  target_ordinal integer not null,
  target_key text not null,
  target_payload jsonb not null,
  target_kind text,
  sellpia_sku_code text,
  source_channel text,
  field_key text,
  price_component text,
  seller_product_code text,
  seller_option_code text,
  before_value jsonb,
  source_value jsonb,
  preview_status text not null default 'pending',
  apply_status text not null default 'pending',
  result_status text not null default 'pending',
  message text,
  error_code text,
  change_id bigint,
  cancelled_count integer not null default 0,
  verified boolean not null default false,
  result_json jsonb not null default '{}'::jsonb,
  previewed_at timestamptz,
  applied_at timestamptz,
  verified_at timestamptz,
  constraint operations_hub_selected_source_refresh_items_target_payload_check
    check (jsonb_typeof(target_payload) = 'object'),
  constraint operations_hub_selected_source_refresh_items_result_json_check
    check (jsonb_typeof(result_json) = 'object'),
  constraint operations_hub_selected_source_refresh_items_kind_check
    check (target_kind is null or target_kind in ('system','seller_stock','seller_price','seller_discount')),
  constraint operations_hub_selected_source_refresh_items_preview_status_check
    check (preview_status in ('pending','ready','skipped','failed')),
  constraint operations_hub_selected_source_refresh_items_apply_status_check
    check (apply_status in ('pending','success','skipped','failed')),
  constraint operations_hub_selected_source_refresh_items_result_status_check
    check (result_status in ('pending','success','skipped','failed')),
  unique (batch_id, target_key)
);

create index if not exists operations_hub_selected_source_refresh_batches_created_idx
  on operations_private.operations_hub_selected_source_refresh_batches(created_at desc, batch_id);
create index if not exists operations_hub_selected_source_refresh_batches_retry_idx
  on operations_private.operations_hub_selected_source_refresh_batches(retry_of_batch_id, created_at desc)
  where retry_of_batch_id is not null;
create index if not exists operations_hub_selected_source_refresh_items_batch_status_idx
  on operations_private.operations_hub_selected_source_refresh_items(batch_id, result_status, target_ordinal);
create index if not exists operations_hub_selected_source_refresh_items_sku_idx
  on operations_private.operations_hub_selected_source_refresh_items(sellpia_sku_code, batch_id);

alter table operations_private.operations_hub_selected_source_refresh_batches enable row level security;
alter table operations_private.operations_hub_selected_source_refresh_items enable row level security;
revoke all on table operations_private.operations_hub_selected_source_refresh_batches from public, anon, authenticated;
revoke all on table operations_private.operations_hub_selected_source_refresh_items from public, anon, authenticated;
revoke all on sequence operations_private.operations_hub_selected_source_refresh_items_item_id_seq from public, anon, authenticated;

comment on table operations_private.operations_hub_selected_source_refresh_batches is
  'Authenticated preview/apply/retry batches for source-restoring selected matrix cells. The request IDs are idempotency keys.';
comment on table operations_private.operations_hub_selected_source_refresh_items is
  'Per-SKU source-refresh preview, apply, and database-reread verification outcomes.';

create or replace function operations_private.resolve_operations_hub_selected_source_refresh_target_v1(
  p_target jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog
set statement_timeout = '5s'
as $$
declare
  v_kind text := lower(btrim(coalesce(p_target ->> 'kind', '')));
  v_sku text := nullif(btrim(p_target ->> 'sku'), '');
  v_source text := lower(btrim(coalesce(p_target ->> 'source', '')));
  v_field text := lower(btrim(coalesce(p_target ->> 'fieldKey', p_target ->> 'field_key', '')));
  v_component text := lower(btrim(coalesce(p_target ->> 'priceComponent', p_target ->> 'price_component', '')));
  v_product_code text;
  v_option_code text;
  v_snapshot_id uuid;
  v_matrix public.operations_hub_matrix_cached%rowtype;
  v_source_row public.seller_inventory_snapshot_rows%rowtype;
  v_active public.operations_hub_active_seller_drafts%rowtype;
  v_source_value jsonb;
  v_before_value jsonb;
  v_source_base numeric;
  v_source_option numeric;
  v_source_final numeric;
  v_current_base numeric;
  v_current_option numeric;
  v_current_final numeric;
  v_current_terms jsonb;
  v_target_base numeric;
  v_target_option numeric;
  v_target_terms jsonb;
  v_target_discounted numeric;
begin
  if jsonb_typeof(coalesce(p_target, 'null'::jsonb)) <> 'object' then
    return jsonb_build_object('status','failed','errorCode','invalid_target','message','대상 형식이 올바르지 않습니다.');
  end if;
  if v_kind not in ('system','seller_stock','seller_price','seller_discount') then
    return jsonb_build_object('status','failed','errorCode','invalid_kind','message','지원하지 않는 원본 갱신 종류입니다.');
  end if;
  if v_sku is null or length(v_sku) > 128 then
    return jsonb_build_object('status','failed','errorCode','invalid_sku','message','셀피아 SKU를 확인해주세요.');
  end if;

  select matrix.* into v_matrix
  from public.operations_hub_matrix_cached matrix
  where matrix.sellpia_sku_code = v_sku;
  if not found then
    return jsonb_build_object('status','failed','errorCode','missing_sku','message','매트릭스에서 SKU를 찾지 못했습니다.','sku',v_sku);
  end if;

  if v_kind = 'system' then
    if v_field not in ('system_base_price','system_stock','sellpia_purchase_price','sellpia_order_unit','sellpia_minimum_order_unit') then
      return jsonb_build_object('status','failed','errorCode','invalid_field','message','지원하지 않는 시스템 기준 필드입니다.','sku',v_sku);
    end if;

    select case v_field
      when 'system_base_price' then
        case
          when nullif(regexp_replace(coalesce(stock.raw_payload ->> 'sell_price',''), '[^0-9.-]', '', 'g'), '') ~ '^-?[0-9]+(\.[0-9]+)?$'
            then to_jsonb(nullif(regexp_replace(coalesce(stock.raw_payload ->> 'sell_price',''), '[^0-9.-]', '', 'g'), '')::numeric)
          else null
        end
      when 'system_stock' then to_jsonb(stock.stock::numeric)
      when 'sellpia_purchase_price' then to_jsonb(stock.purchase_price)
      when 'sellpia_order_unit' then to_jsonb(stock.order_unit)
      when 'sellpia_minimum_order_unit' then to_jsonb(stock.minimum_order_unit)
    end
    into v_source_value
    from public.sellpia_stock_latest stock
    where stock.sellpia_sku_code = v_sku;

    select case v_field
      when 'system_base_price' then to_jsonb(master.base_price)
      when 'system_stock' then to_jsonb(master.stock_quantity::numeric)
      when 'sellpia_purchase_price' then to_jsonb(master.purchase_price)
      when 'sellpia_order_unit' then to_jsonb(master.order_unit)
      when 'sellpia_minimum_order_unit' then to_jsonb(master.minimum_order_unit)
    end
    into v_before_value
    from public.operations_hub_sku_operational_master master
    where master.sellpia_sku_code = v_sku;

    if v_source_value is null or v_source_value = 'null'::jsonb then
      return jsonb_build_object('status','skipped','errorCode','source_missing','message','최신 셀피아 원본값이 없습니다.','kind',v_kind,'sku',v_sku,'fieldKey',v_field,'beforeValue',v_before_value);
    end if;
    return jsonb_build_object(
      'status', case when v_before_value is not distinct from v_source_value then 'skipped' else 'ready' end,
      'errorCode', case when v_before_value is not distinct from v_source_value then 'already_source' else null end,
      'message', case when v_before_value is not distinct from v_source_value then '이미 원본값과 같습니다.' else '원본값으로 갱신할 수 있습니다.' end,
      'kind',v_kind,'sku',v_sku,'fieldKey',v_field,
      'beforeValue',v_before_value,'sourceValue',v_source_value,
      'activeChangeId',null,
      'stateFingerprint',md5(jsonb_build_object('beforeValue',v_before_value,'sourceValue',v_source_value)::text),
      'canonicalTarget',jsonb_build_object('kind',v_kind,'sku',v_sku,'fieldKey',v_field)
    );
  end if;

  if v_source not in ('smartstore','makeshop','ably') then
    return jsonb_build_object('status','failed','errorCode','invalid_source','message','판매처를 확인해주세요.','sku',v_sku);
  end if;

  v_product_code := nullif(btrim(case v_source
    when 'smartstore' then v_matrix.smartstore_product_code
    when 'makeshop' then v_matrix.makeshop_product_code
    when 'ably' then v_matrix.ably_product_code
  end), '');
  v_option_code := coalesce(case v_source
    when 'smartstore' then v_matrix.smartstore_option_code
    when 'makeshop' then v_matrix.makeshop_option_code
    when 'ably' then v_matrix.ably_option_code
  end, '');
  if v_product_code is null then
    return jsonb_build_object('status','failed','errorCode','missing_listing','message','판매처 연결 상품코드가 없습니다.','kind',v_kind,'sku',v_sku,'source',v_source);
  end if;

  select snapshot.snapshot_id into v_snapshot_id
  from public.seller_inventory_snapshots snapshot
  where snapshot.source_channel = v_source and snapshot.upload_status = 'ready'
  order by snapshot.completed_at desc nulls last, snapshot.created_at desc
  limit 1;
  if v_snapshot_id is null then
    return jsonb_build_object('status','skipped','errorCode','source_missing','message','최신 판매처 원본이 없습니다.','kind',v_kind,'sku',v_sku,'source',v_source);
  end if;

  select source_row.* into v_source_row
  from public.seller_inventory_snapshot_rows source_row
  where source_row.snapshot_id = v_snapshot_id
    and source_row.product_code = v_product_code
    and source_row.option_code = v_option_code
  limit 1;
  if not found then
    return jsonb_build_object('status','skipped','errorCode','source_missing','message','최신 판매처 원본에서 상품·옵션코드를 찾지 못했습니다.','kind',v_kind,'sku',v_sku,'source',v_source,'productCode',v_product_code,'optionCode',v_option_code);
  end if;

  select draft.* into v_active
  from public.operations_hub_active_seller_drafts draft
  where draft.sellpia_sku_code = v_sku
    and draft.source_channel = v_source
    and draft.field_key = case when v_kind = 'seller_stock' then 'sellpia_current_stock' else 'sellpia_sale_price' end
  order by draft.updated_at desc, draft.change_id desc
  limit 1;
  if found and v_active.status = 'processing' then
    return jsonb_build_object('status','failed','errorCode','locked_change','message','내보내기 처리 중이거나 내보낸 수정안은 원본값으로 되돌릴 수 없습니다.','kind',v_kind,'sku',v_sku,'source',v_source,'productCode',v_product_code,'optionCode',v_option_code);
  end if;

  if v_kind = 'seller_stock' then
    v_source_value := to_jsonb(v_source_row.stock::numeric);
    v_before_value := case
      when v_active.change_id is not null then v_active.after_value
      else to_jsonb(v_source_row.stock::numeric)
    end;
    if v_source_value is null or v_source_value = 'null'::jsonb then
      return jsonb_build_object('status','skipped','errorCode','source_missing','message','최신 판매처 원본 재고가 없습니다.','kind',v_kind,'sku',v_sku,'source',v_source,'productCode',v_product_code,'optionCode',v_option_code);
    end if;
  else
    v_source_base := coalesce(v_source_row.base_price, nullif(v_source_row.raw_payload ->> 'base_price','')::numeric, v_source_row.price);
    v_source_option := coalesce(v_source_row.option_price, nullif(v_source_row.raw_payload ->> 'option_price','')::numeric, 0);
    v_source_final := coalesce(v_source_row.final_price, v_source_row.price, v_source_row.discounted_base_price + v_source_option, v_source_base + v_source_option);
    v_current_base := coalesce(v_active.price_base_after, v_source_base);
    v_current_option := coalesce(v_active.price_option_after, v_source_option);
    v_current_final := coalesce(v_active.price_final_after, v_source_final);
    v_current_terms := coalesce(v_active.price_discount_terms_after, v_source_row.discount_terms, '[]'::jsonb);

    if v_kind = 'seller_discount' then
      v_field := 'sellpia_sale_price';
      v_source_value := coalesce(v_source_row.discount_terms, '[]'::jsonb);
      v_before_value := v_current_terms;
    else
      v_field := 'sellpia_sale_price';
      if v_component not in ('base','option','final') then
        return jsonb_build_object('status','failed','errorCode','invalid_component','message','판매가 원본 갱신 컬럼을 확인해주세요.','kind',v_kind,'sku',v_sku,'source',v_source);
      end if;
      v_source_value := to_jsonb(case v_component when 'base' then v_source_base when 'option' then v_source_option when 'final' then v_source_final end);
      v_before_value := to_jsonb(case v_component when 'base' then v_current_base when 'option' then v_current_option when 'final' then v_current_final end);
      if v_source_value is null or v_source_value = 'null'::jsonb then
        return jsonb_build_object('status','skipped','errorCode','source_missing','message','최신 판매처 원본 가격이 없습니다.','kind',v_kind,'sku',v_sku,'source',v_source,'priceComponent',v_component,'productCode',v_product_code,'optionCode',v_option_code);
      end if;
    end if;

    v_target_base := case when v_kind='seller_price' and v_component='base' then v_source_base else v_current_base end;
    v_target_terms := case when v_kind='seller_discount' then coalesce(v_source_row.discount_terms,'[]'::jsonb) else v_current_terms end;
    v_target_discounted := operations_private.calculate_operations_hub_discounted_base(
      v_source,v_target_base,v_target_terms,null
    );
    v_target_option := case
      when v_kind='seller_price' and v_component='option' then v_source_option
      when v_kind='seller_price' and v_component='final' then v_source_final - v_target_discounted
      else v_current_option
    end;
  end if;

  return jsonb_build_object(
    'status', case when v_before_value is not distinct from v_source_value then 'skipped' else 'ready' end,
    'errorCode', case when v_before_value is not distinct from v_source_value then 'already_source' else null end,
    'message', case when v_before_value is not distinct from v_source_value then '이미 원본값과 같습니다.' else '원본값으로 갱신할 수 있습니다.' end,
    'kind',v_kind,'sku',v_sku,'source',v_source,'fieldKey',v_field,'priceComponent',nullif(v_component,''),
    'productCode',v_product_code,'optionCode',v_option_code,
    'beforeValue',v_before_value,'sourceValue',v_source_value,
    'activeChangeId',v_active.change_id,
    'stateFingerprint',md5(jsonb_build_object(
      'activeChangeId',v_active.change_id,'beforeValue',v_before_value,
      'currentBasePrice',v_current_base,'currentOptionPrice',v_current_option,
      'currentFinalPrice',v_current_final,'currentDiscountTerms',v_current_terms
    )::text),
    'sourceSnapshotId',v_snapshot_id,
    'applyContext',jsonb_build_object(
      'currentBasePrice',v_current_base,
      'currentOptionPrice',v_current_option,
      'currentFinalPrice',v_current_final,
      'sourceBasePrice',v_source_base,
      'sourceOptionPrice',v_source_option,
      'sourceFinalPrice',v_source_final,
      'sourceDiscountTerms',coalesce(v_source_row.discount_terms,'[]'::jsonb),
      'targetBasePrice',v_target_base,
      'targetOptionPrice',v_target_option,
      'targetDiscountTerms',coalesce(v_target_terms,'[]'::jsonb),
      'optionPriceSource',coalesce(v_active.option_price_source,'original'),
      'basePriceSource',coalesce(v_active.base_price_source,'source'),
      'priceRuleSetId',v_active.price_rule_set_id
    ),
    'canonicalTarget',jsonb_build_object(
      'kind',v_kind,'sku',v_sku,'source',v_source,'fieldKey',v_field,
      'priceComponent',nullif(v_component,''),'productCode',v_product_code,'optionCode',v_option_code
    )
  );
exception when invalid_text_representation or numeric_value_out_of_range then
  return jsonb_build_object('status','failed','errorCode','invalid_source_value','message','판매처 원본 가격 형식을 숫자로 해석할 수 없습니다.','kind',v_kind,'sku',v_sku,'source',v_source);
end;
$$;

create or replace function operations_private.operations_hub_selected_source_refresh_batch_result_v1(
  p_batch_id uuid
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog
as $$
  select jsonb_build_object(
    'batchId', batch.batch_id,
    'previewRequestId', batch.preview_request_id,
    'applyRequestId', batch.apply_request_id,
    'retryOfBatchId', batch.retry_of_batch_id,
    'status', batch.status,
    'scope', batch.scope_json,
    'requestedCount', batch.requested_count,
    'readyCount', batch.ready_count,
    'skippedCount', batch.skipped_count,
    'failedCount', batch.failed_count,
    'successCount', batch.success_count,
    'verifiedCount', batch.verified_count,
    'previewedAt', batch.previewed_at,
    'appliedAt', batch.applied_at,
    'completedAt', batch.completed_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'itemId', item.item_id,
        'ordinal', item.target_ordinal,
        'targetKey', item.target_key,
        'kind', item.target_kind,
        'sku', item.sellpia_sku_code,
        'source', item.source_channel,
        'fieldKey', item.field_key,
        'priceComponent', item.price_component,
        'productCode', item.seller_product_code,
        'optionCode', item.seller_option_code,
        'beforeValue', item.before_value,
        'sourceValue', item.source_value,
        'previewStatus', item.preview_status,
        'applyStatus', item.apply_status,
        'resultStatus', item.result_status,
        'message', item.message,
        'errorCode', item.error_code,
        'changeId', item.change_id,
        'cancelledCount', item.cancelled_count,
        'verified', item.verified,
        'result', item.result_json
      ) order by item.target_ordinal, item.item_id)
      from operations_private.operations_hub_selected_source_refresh_items item
      where item.batch_id = batch.batch_id
    ), '[]'::jsonb)
  )
  from operations_private.operations_hub_selected_source_refresh_batches batch
  where batch.batch_id = p_batch_id;
$$;

create or replace function public.run_operations_hub_selected_source_refresh_batch_v1(
  p_session_token text,
  p_request_id uuid,
  p_targets jsonb default '[]'::jsonb,
  p_scope jsonb default '{}'::jsonb,
  p_dry_run boolean default true,
  p_batch_id uuid default null,
  p_retry_failed_only_from uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
set statement_timeout = '45s'
as $$
declare
  v_session jsonb;
  v_session_id uuid;
  v_actor text;
  v_request_id uuid := coalesce(p_request_id, gen_random_uuid());
  v_targets jsonb := coalesce(p_targets, '[]'::jsonb);
  v_scope jsonb := coalesce(p_scope, '{}'::jsonb);
  v_batch_id uuid;
  v_existing operations_private.operations_hub_selected_source_refresh_batches%rowtype;
  v_payload_hash text;
  v_target jsonb;
  v_resolution jsonb;
  v_fresh jsonb;
  v_target_key text;
  v_lock_key text;
  v_item operations_private.operations_hub_selected_source_refresh_items%rowtype;
  v_saved jsonb;
  v_change_id bigint;
  v_cancelled integer;
  v_ready integer;
  v_skipped integer;
  v_failed integer;
  v_success integer;
  v_verified integer;
  v_internal_advance boolean;
begin
  v_session := operations_private.require_operations_hub_operator_session(p_session_token);
  v_session_id := (v_session ->> 'session_id')::uuid;
  v_actor := coalesce(nullif(v_session ->> 'username',''), 'operations_hub_operator');
  if p_request_id is null then raise exception '요청 ID가 필요합니다.'; end if;
  if jsonb_typeof(v_scope) <> 'object' then raise exception '선택 범위는 JSON 객체여야 합니다.'; end if;

  perform pg_advisory_xact_lock(hashtextextended('operations_hub_selected_source_refresh_request:' || v_request_id::text, 0));

  if coalesce(p_dry_run, true) then
    if p_retry_failed_only_from is not null then
      if not exists (
        select 1 from operations_private.operations_hub_selected_source_refresh_batches batch
        where batch.batch_id = p_retry_failed_only_from and batch.status in ('completed_with_failures','preview_blocked')
      ) then raise exception '실패 항목을 재시도할 이전 배치를 찾지 못했습니다.'; end if;
      select coalesce(jsonb_agg(item.target_payload order by item.target_ordinal), '[]'::jsonb)
      into v_targets
      from operations_private.operations_hub_selected_source_refresh_items item
      where item.batch_id = p_retry_failed_only_from
        and (item.result_status = 'failed' or (item.apply_status = 'pending' and item.preview_status = 'failed'));
      v_scope := v_scope || jsonb_build_object('retryFailedOnly',true,'retryOfBatchId',p_retry_failed_only_from);
    end if;

    if jsonb_typeof(v_targets) <> 'array' then raise exception '원본 갱신 대상은 JSON 배열이어야 합니다.'; end if;
    if jsonb_array_length(v_targets) = 0 then raise exception '원본값으로 갱신할 대상이 없습니다.'; end if;
    if jsonb_array_length(v_targets) > 50 then raise exception '선택 원본 갱신 서버 요청은 한 번에 50개 DB 대상까지 가능합니다.'; end if;
    v_payload_hash := md5(jsonb_build_object('targets',v_targets,'scope',v_scope)::text);

    select batch.* into v_existing
    from operations_private.operations_hub_selected_source_refresh_batches batch
    where batch.preview_request_id = v_request_id;
    if found then
      if v_existing.payload_hash <> v_payload_hash then
        raise exception '같은 요청 ID를 다른 선택 범위에 다시 사용할 수 없습니다.';
      end if;
      return operations_private.operations_hub_selected_source_refresh_batch_result_v1(v_existing.batch_id);
    end if;

    insert into operations_private.operations_hub_selected_source_refresh_batches (
      preview_request_id,retry_of_batch_id,payload_hash,scope_json,status,actor,session_id,requested_count
    ) values (
      v_request_id,p_retry_failed_only_from,v_payload_hash,v_scope,'previewing',v_actor,v_session_id,jsonb_array_length(v_targets)
    ) returning batch_id into v_batch_id;

    for v_target, v_ready in
      select value, ordinality::integer
      from jsonb_array_elements(v_targets) with ordinality
    loop
      v_resolution := operations_private.resolve_operations_hub_selected_source_refresh_target_v1(v_target);
      v_target_key := case when v_resolution ->> 'kind' = 'system' then concat_ws('|',
          'system',coalesce(v_resolution ->> 'sku',v_target ->> 'sku',''),
          coalesce(v_resolution ->> 'fieldKey',v_target ->> 'fieldKey','')
        ) else concat_ws('|',
          coalesce(v_resolution ->> 'kind',v_target ->> 'kind',''),
          coalesce(v_resolution ->> 'source',v_target ->> 'source',''),
          coalesce(v_resolution ->> 'productCode',v_target ->> 'productCode',''),
          coalesce(v_resolution ->> 'optionCode',v_target ->> 'optionCode',''),
          coalesce(v_resolution ->> 'fieldKey',v_target ->> 'fieldKey',''),
          coalesce(v_resolution ->> 'priceComponent',v_target ->> 'priceComponent','')
        ) end;
      insert into operations_private.operations_hub_selected_source_refresh_items (
        batch_id,target_ordinal,target_key,target_payload,target_kind,sellpia_sku_code,source_channel,
        field_key,price_component,seller_product_code,seller_option_code,before_value,source_value,
        preview_status,apply_status,result_status,message,error_code,result_json,previewed_at
      ) values (
        v_batch_id,v_ready,v_target_key,v_target,
        nullif(v_resolution ->> 'kind',''),nullif(v_resolution ->> 'sku',''),nullif(v_resolution ->> 'source',''),
        nullif(v_resolution ->> 'fieldKey',''),nullif(v_resolution ->> 'priceComponent',''),
        nullif(v_resolution ->> 'productCode',''),coalesce(v_resolution ->> 'optionCode',''),
        v_resolution -> 'beforeValue',v_resolution -> 'sourceValue',
        coalesce(v_resolution ->> 'status','failed'),'pending','pending',
        coalesce(v_resolution ->> 'message','대상 확인에 실패했습니다.'),v_resolution ->> 'errorCode',v_resolution,clock_timestamp()
      ) on conflict (batch_id,target_key) do nothing;
    end loop;

    select
      count(*) filter (where item.preview_status='ready')::integer,
      count(*) filter (where item.preview_status='skipped')::integer,
      count(*) filter (where item.preview_status='failed')::integer
    into v_ready,v_skipped,v_failed
    from operations_private.operations_hub_selected_source_refresh_items item
    where item.batch_id=v_batch_id;

    update operations_private.operations_hub_selected_source_refresh_batches batch
    set requested_count=(select count(*)::integer from operations_private.operations_hub_selected_source_refresh_items item where item.batch_id=v_batch_id),
        ready_count=v_ready, skipped_count=v_skipped, failed_count=v_failed,
        status=case when v_ready>0 then 'preview_ready' else 'preview_blocked' end,
        previewed_at=clock_timestamp()
    where batch.batch_id=v_batch_id;
    return operations_private.operations_hub_selected_source_refresh_batch_result_v1(v_batch_id);
  end if;

  if p_batch_id is null then raise exception '실행할 미리보기 배치 ID가 필요합니다.'; end if;
  select batch.* into v_existing
  from operations_private.operations_hub_selected_source_refresh_batches batch
  where batch.batch_id=p_batch_id
  for update;
  if not found then raise exception '실행할 원본 갱신 배치를 찾지 못했습니다.'; end if;
  if v_existing.apply_request_id = v_request_id and v_existing.status in ('completed','completed_with_failures') then
    return operations_private.operations_hub_selected_source_refresh_batch_result_v1(v_existing.batch_id);
  end if;
  if v_existing.apply_request_id is not null and v_existing.apply_request_id <> v_request_id then
    raise exception '이미 다른 실행 요청으로 처리된 배치입니다. 실패 항목만 재시도해주세요.';
  end if;
  if v_existing.status not in ('preview_ready','applying') then raise exception '실행 가능한 미리보기 배치가 아닙니다.'; end if;

  update operations_private.operations_hub_selected_source_refresh_batches batch
  set apply_request_id=v_request_id,status='applying',applied_at=coalesce(applied_at,clock_timestamp())
  where batch.batch_id=p_batch_id;

  for v_item in
    select item.*
    from operations_private.operations_hub_selected_source_refresh_items item
    where item.batch_id=p_batch_id and item.preview_status='ready' and item.apply_status='pending'
    order by item.target_ordinal,item.item_id
  loop
    begin
      -- Price base/option/final/discount are separate UI items but write one
      -- exact seller price target. Serialize them with the same target lock so
      -- concurrent operator batches cannot replace each other's components.
      v_lock_key := case
        when v_item.target_kind = 'system' then concat_ws('|',
          'system', v_item.sellpia_sku_code, v_item.field_key
        )
        else concat_ws('|',
          v_item.source_channel,
          v_item.seller_product_code,
          coalesce(v_item.seller_option_code, ''),
          case when v_item.target_kind = 'seller_stock'
            then 'sellpia_current_stock'
            else 'sellpia_sale_price'
          end
        )
      end;
      if v_item.target_kind <> 'system' then
        -- Match the canonical seller-target lock used by the queue guard and
        -- direct saver before either path can acquire a queue row lock.
        perform pg_advisory_xact_lock(hashtextextended(
          lower(btrim(v_item.source_channel)) || chr(31)
            || btrim(v_item.seller_product_code) || chr(31)
            || coalesce(nullif(btrim(v_item.seller_option_code), ''), '') || chr(31)
            || case when v_item.target_kind = 'seller_stock'
              then 'sellpia_current_stock'
              else 'sellpia_sale_price'
            end,
          0
        ));
      end if;
      perform pg_advisory_xact_lock(hashtextextended('operations_hub_selected_source_refresh_target:' || v_lock_key, 0));
      v_fresh := operations_private.resolve_operations_hub_selected_source_refresh_target_v1(v_item.target_payload);
      if coalesce(v_fresh ->> 'status','failed') = 'failed' then
        raise exception '%', coalesce(v_fresh ->> 'message','DB 대상 재확인에 실패했습니다.');
      end if;
      if v_fresh -> 'sourceValue' is distinct from v_item.source_value then
        raise exception '미리보기 후 원본값이 변경되었습니다. 실패 항목만 다시 미리보기해주세요.'
          using errcode='40001';
      end if;
      v_internal_advance := false;
      if nullif(v_fresh ->> 'activeChangeId','') is not null
         and nullif(v_fresh ->> 'activeChangeId','') is distinct from nullif(v_item.result_json ->> 'activeChangeId','') then
        select exists (
          select 1 from public.operations_hub_change_queue queue
          where queue.change_id=(v_fresh ->> 'activeChangeId')::bigint
            and queue.change_batch_id=p_batch_id
        ) into v_internal_advance;
      end if;
      if (
        v_fresh -> 'beforeValue' is distinct from v_item.before_value
        or nullif(v_fresh ->> 'activeChangeId','') is distinct from nullif(v_item.result_json ->> 'activeChangeId','')
        or nullif(v_fresh ->> 'stateFingerprint','') is distinct from nullif(v_item.result_json ->> 'stateFingerprint','')
      ) and not v_internal_advance then
        raise exception '미리보기 후 현재 수정안 또는 가격 구성요소가 변경되었습니다. 실패 항목만 다시 미리보기해주세요.'
          using errcode='40001';
      end if;
      if v_fresh ->> 'status' = 'skipped' then
        update operations_private.operations_hub_selected_source_refresh_items item
        set apply_status='skipped',result_status='skipped',message='실행 전에 이미 원본값으로 반영되었습니다.',
            error_code='already_source',verified=true,result_json=v_fresh,applied_at=clock_timestamp(),verified_at=clock_timestamp()
        where item.item_id=v_item.item_id;
        continue;
      end if;
      -- Preserve the latest non-selected price components. Multiple selected
      -- columns for one seller target can therefore run sequentially without
      -- a later item restoring stale preview-time values over an earlier item.
      v_resolution := v_fresh;

      v_saved := null;
      v_cancelled := 0;
      if v_item.target_kind <> 'system' then
        update public.operations_hub_change_queue queue
        set status='cancelled',cancelled_at=clock_timestamp(),cancelled_by=v_actor,
            status_message='선택 셀 원본값 갱신 배치로 대체됨',updated_at=clock_timestamp()
        where queue.source_channel=v_item.source_channel
          and btrim(queue.seller_product_code)=btrim(v_item.seller_product_code)
          and coalesce(nullif(btrim(queue.seller_option_code),''),'')=coalesce(v_item.seller_option_code,'')
          and queue.field_key=case when v_item.target_kind='seller_stock' then 'sellpia_current_stock' else 'sellpia_sale_price' end
          and queue.status in ('pending','validated','failed');
        get diagnostics v_cancelled = row_count;
      end if;

      if v_item.target_kind='system' then
        select to_jsonb(saved) into v_saved
        from public.save_operations_hub_sku_operational_value(
          p_session_token,v_item.sellpia_sku_code,v_item.field_key,(v_item.source_value #>> '{}')::numeric,
          'source_accept','operations-hub',jsonb_build_object('ui','matrix-selected-source-refresh','batch_id',p_batch_id,'item_id',v_item.item_id)
        ) saved limit 1;
      elsif v_item.target_kind='seller_stock' then
        select to_jsonb(saved) into v_saved
        from public.save_operations_hub_seller_value_draft(
          v_item.sellpia_sku_code,v_item.source_channel,'sellpia_current_stock',(v_item.source_value #>> '{}')::numeric,p_batch_id
        ) saved limit 1;
      elsif v_item.target_kind in ('seller_discount','seller_price') then
        select to_jsonb(saved) into v_saved
        from public.save_operations_hub_seller_rule_draft(
          v_item.sellpia_sku_code,
          v_item.source_channel,
          (v_resolution #>> '{applyContext,targetBasePrice}')::numeric,
          coalesce(v_resolution #> '{applyContext,targetDiscountTerms}','[]'::jsonb),
          (v_resolution #>> '{applyContext,targetOptionPrice}')::numeric,
          nullif(v_resolution #>> '{applyContext,priceRuleSetId}','')::bigint,
          p_batch_id
        ) saved limit 1;
      else
        raise exception '지원하지 않는 원본 갱신 종류입니다.';
      end if;

      v_change_id := nullif(v_saved ->> 'change_id','')::bigint;
      v_cancelled := v_cancelled + coalesce(nullif(v_saved ->> 'cancelled_count','')::integer,0);
      if v_change_id is not null and v_item.target_kind in ('seller_discount','seller_price') then
        update public.operations_hub_change_queue queue
        set base_price_source=case
              when v_item.target_kind='seller_price' and v_item.price_component='base' then 'source'
              else coalesce(nullif(v_resolution #>> '{applyContext,basePriceSource}',''),'source')
            end,
            option_price_source=case
              when v_item.target_kind='seller_price' and v_item.price_component='option' then 'original'
              when v_item.target_kind='seller_price' and v_item.price_component='final' then 'manual'
              else coalesce(nullif(v_resolution #>> '{applyContext,optionPriceSource}',''),'original')
            end,
            status_message='선택 셀 원본값 갱신 · DB 확인 대기',
            updated_at=clock_timestamp()
        where queue.change_id=v_change_id;
      end if;
      v_fresh := operations_private.resolve_operations_hub_selected_source_refresh_target_v1(v_item.target_payload);
      if v_fresh ->> 'status' <> 'skipped' or v_fresh ->> 'errorCode' <> 'already_source' then
        raise exception '저장 후 DB 재조회 값이 원본과 일치하지 않습니다.';
      end if;

      update operations_private.operations_hub_selected_source_refresh_items item
      set apply_status='success',result_status='success',message='DB 저장 및 재조회 확인 완료',error_code=null,
          change_id=v_change_id,cancelled_count=v_cancelled,verified=true,
          result_json=jsonb_build_object('saveResult',coalesce(v_saved,'{}'::jsonb),'verification',v_fresh),
          applied_at=clock_timestamp(),verified_at=clock_timestamp()
      where item.item_id=v_item.item_id;
    exception when others then
      update operations_private.operations_hub_selected_source_refresh_items item
      set apply_status='failed',result_status='failed',message=sqlerrm,
          error_code=case when sqlstate='40001' then 'stale_preview' else coalesce(nullif(sqlstate,''),'apply_failed') end,
          verified=false,result_json=jsonb_build_object('sqlstate',sqlstate),applied_at=clock_timestamp()
      where item.item_id=v_item.item_id;
    end;
  end loop;

  update operations_private.operations_hub_selected_source_refresh_items item
  set apply_status=case when item.preview_status='failed' then 'failed' else 'skipped' end,
      result_status=case when item.preview_status='failed' then 'failed' else 'skipped' end,
      verified=(item.preview_status='skipped'),
      verified_at=case when item.preview_status='skipped' then clock_timestamp() else null end
  where item.batch_id=p_batch_id and item.apply_status='pending' and item.preview_status in ('skipped','failed');

  select
    count(*) filter (where item.result_status='success')::integer,
    count(*) filter (where item.result_status='skipped')::integer,
    count(*) filter (where item.result_status='failed')::integer,
    count(*) filter (where item.verified)::integer
  into v_success,v_skipped,v_failed,v_verified
  from operations_private.operations_hub_selected_source_refresh_items item
  where item.batch_id=p_batch_id;

  update operations_private.operations_hub_selected_source_refresh_batches batch
  set success_count=v_success,skipped_count=v_skipped,failed_count=v_failed,verified_count=v_verified,
      status=case when v_failed>0 then 'completed_with_failures' else 'completed' end,
      completed_at=clock_timestamp()
  where batch.batch_id=p_batch_id;
  return operations_private.operations_hub_selected_source_refresh_batch_result_v1(p_batch_id);
end;
$$;

revoke all on function operations_private.resolve_operations_hub_selected_source_refresh_target_v1(jsonb) from public, anon, authenticated;
revoke all on function operations_private.operations_hub_selected_source_refresh_batch_result_v1(uuid) from public, anon, authenticated;
revoke all on function public.run_operations_hub_selected_source_refresh_batch_v1(text,uuid,jsonb,jsonb,boolean,uuid,uuid) from public, anon, authenticated;
grant execute on function public.run_operations_hub_selected_source_refresh_batch_v1(text,uuid,jsonb,jsonb,boolean,uuid,uuid) to anon, authenticated;

comment on function public.run_operations_hub_selected_source_refresh_batch_v1(text,uuid,jsonb,jsonb,boolean,uuid,uuid) is
  'Requires an operator session. Creates an idempotent selected-cell source-refresh preview, applies ready items with explicit per-item outcomes and DB reread verification, or creates a failed-only retry batch.';

create or replace function operations_private.prune_operations_hub_selected_source_refresh_details_v1()
returns integer
language plpgsql
security definer
set search_path = pg_catalog
set statement_timeout = '30s'
as $$
declare
  v_deleted integer;
begin
  delete from operations_private.operations_hub_selected_source_refresh_items item
  using operations_private.operations_hub_selected_source_refresh_batches batch
  where batch.batch_id=item.batch_id
    and batch.status in ('completed','completed_with_failures')
    and batch.completed_at < clock_timestamp() - interval '90 days';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function operations_private.prune_operations_hub_selected_source_refresh_details_v1()
  from public, anon, authenticated;
comment on function operations_private.prune_operations_hub_selected_source_refresh_details_v1() is
  'Deletes completed per-target details after 90 days while preserving batch summaries and counts.';

do $$
declare
  v_job_id bigint;
begin
  for v_job_id in
    select jobid from cron.job where jobname='operations-hub-selected-source-refresh-retention'
  loop
    perform cron.unschedule(v_job_id);
  end loop;
end;
$$;

-- pg_cron uses UTC. 18:43 UTC is 03:43 KST the next day.
select cron.schedule(
  'operations-hub-selected-source-refresh-retention',
  '43 18 * * *',
  $cron$select operations_private.prune_operations_hub_selected_source_refresh_details_v1();$cron$
);

notify pgrst, 'reload schema';
